== Selection from the Journal of John Banks

I came of honest parents; my father`'s name was William, and my mother`'s name was Emme.
I was their only child, born in Sunderland, in the parish of Issell,
in the county of Cumberland.
My father, having no real estate of his own, took some land to farm,
and by trade was a fell-monger^
footnote:[One who deals in hides or skins.]
and glover.
Some years later, he moved within the compass of Pardshaw meeting,
where both my parents received the truth some time after me, and lived and died in it,
according to their measures.
I belonged to this meeting more than forty years.

Though my parents had not much of this world`'s riches,
yet according to their ability and the manner of the country in which they lived,
they brought me up well and in good order.
They were careful to restrain me from such evils
as children and youth are apt to run into,
especially my dear mother, she being a zealous woman.
Their care in this way had a good effect on me;
and so it will have (we may hope) on all who perform
their duty to their children as they ought;
if not, I fear they will be found guilty in the day of account.

I was put to school when I was seven years of age and kept there until I was fourteen,
during which time I learned both English and Latin, and could write well.
When I was fourteen years of age,
my father put me to teach school one year at Dissington,
and after that at Mosser Chapel near Pardshaw,
where I also read Scripture and the homily (as it was called)
to the people who came there on the first-day of the week,
and also sang psalms and prayed.
I had no liking to this practice, but my father, with other people, persuaded me to it.

For this service,
my wage from the people was twelve pence a year from
every house of those who came there to hear me,
and a fleece of wool, and my food for free,
besides twelve pence a quarter for each of my twenty-four students.
This chapel was called a chapel of ease, for the parish steeple-house^
footnote:[Early Friends used the word steeple-house to refer to the large parish meetinghouses,
being unwilling to use the word _church_ to refer to a building of wood and stone.]
was some miles off.
Amongst the rest of the people who were indifferent about where they attended worship,
came one John Fletcher, a great scholar, but a drunken man.
He called me aside one day, and said I read very well for a youth,
but I did not pray in form as others did,
and he said he would send me a letter to teach me how to pray, which he did.

When it came, I went out of the chapel and read it; and when I had finished,
I was convinced it was evil by the light of the Lord Jesus,
which immediately opened to me the words of the apostle Paul concerning
the Gospel he was given to preach--that it was "`not from man,
neither was he taught it, but it was received by the revelation of Jesus Christ.`"^
footnote:[Galatians 1:12]
In response to which it arose within me, "`But you have this prayer from a man,
and are taught it by man, and he being one of the worst of many!`"
So the dread of the Lord fell upon me, with which I was struck to my very heart,
and said in myself, "`I shall never pray in this way.`"
Then it opened in me, "`Go to the meeting of the people in scorn called Quakers,
for they are the people of God.`"
And so I went to the meeting at Pardshaw the very next first-day.

This took place near the end of the year,
when I was soon to receive wages from the people for the services I performed.
But I could take nothing from them, being now convinced of the evil thereof,
nor did I ever read any more at the chapel.

Just prior to this time, when about sixteen years of age, in the tenth month, 1654,
it had pleased the Lord to reach to my heart and conscience by His pure living Spirit,
in His blessed appearance in and through Jesus Christ;
whereby I received the knowledge of God and the way of His blessed truth,
by myself alone in the field, before I ever heard anyone called a Quaker preach,
and before I had been at any of their meetings.
But the first day that I went to one (which was at Pardshaw, as before mentioned),
the Lord`'s power so seized upon me in the meeting,
that I was made to cry out in the bitterness of my soul,
in a true sight and sense of my sins, which appeared exceeding sinful.
And then, the same day,
as I was going to an evening meeting of God`'s people scornfully called Quakers,
while on the way I was struck to the ground with the weight of
God`'s judgment for sin and iniquity which fell heavy upon me,
and I was taken up by two Friends.
Oh, the godly sorrow that took hold of me that night in the meeting!
Truly I thought to myself that everyone`'s condition was better than mine.
A Friend, who was touched with a sense of my condition and greatly pitied me,
was made willing to read a paper in this meeting,
which was so suitable to my condition that it helped me a little,
and gave some ease to my spirit.

I was now very much bowed down and perplexed, my sins being set in order before me.
The time I had spent in wildness and carelessness, out of the fear of God, in vanity,
sports, and pastimes, came into my view and remembrance.
The book of my conscience was opened, for I was wild and careless by nature.
And though good desires had stirred in me many times,
and something within had judged and reproved me,
often striving with me to restrain me from evil, yet not being sensible what this was,
I had gotten over it.
Yes, I was like those who make merry over the slain witness of God,^
footnote:[Revelation 11:10]
even the witness and testimony of His Holy Spirit, in and through Jesus Christ His Son,
made known in God`'s great love to the sons and daughters of men.
This was that, by which the Lord many times strove with me,
until at last He prevailed upon me.
So that I may say, as a true witness for God,
and for the sufficiency of His power and quickening Spirit:
I not only came to be convinced by the living appearance of the Lord Jesus of the vanity,
sin, and wickedness of the world (of which I was a partaker), but by taking heed thereto,
through watchfulness and fear,
I came to a discernible experience of His work in my heart,
in order to subdue and bring down the wild nature in me,
and to wash and cleanse me from sin and corruption,
that I might be truly changed and converted.

But before I came to witness this work effected,
oh the days and nights of godly sorrow and spiritual
pain I travelled through for some years!
The exercise I was under bore down so hard, both upon my body and mind,
that I left off the practice of teaching school, which, although good and lawful,
yet was not agreeable to me in my current condition.
I put myself to learn my father`'s trade, along with something of husbandry,
which I followed with diligence; and I lived with my parents,
who some time after came to receive the truth,
which was a matter of great rejoicing to my soul.

As I travelled under the ministration of condemnation and judgment for sin and transgression,
great was the warfare I had with the enemy of my soul, who, through his subtlety,
sought to betray me from the simplicity of the truth, and persuade me to despair,
as though there was no mercy for me.
Yet in some small measure, I knew the Lord had shown mercy to me,
which He mixed with judgment for my many past sins.
But the experience I had gained in the travail of my soul,
and the faith begotten by God in my heart,
strengthened me to withstand the enemy and his subtle reasonings.
I overcame the wicked one through a diligent waiting in the light,
and keeping close to the power of God, waiting upon Him in silence among His people,
in which exercise my soul delighted.

Oh! the comfort, and divine consolation we were made partakers of in those days!
And in the inward sense and feeling of the Lord`'s power and presence with us,
we enjoyed one another, and were near and dear one unto another.
But it was through various trials and deep exercises, with fear and trembling,
that we were made partakers of these things.
Truly blessed and happy are they who know what the truth has cost them,
and who hold it in righteousness.

Waiting diligently in the light,
and keeping close to the power of God which is therein received,
I came to experience the work of His power going on in my heart,
in order to effect my freedom from bondage,
which by degrees continued and prospered within me.
I gained more and more ground against the enemy of my soul,
through faith in that power without which no victory can be obtained.
And I always found that my prosperity in the truth came
by being faithful to the Lord in whatever He made manifest,
though in the smallest of things.
For unfaithfulness in little things is the cause of great
loss and hurt to many in their growth in the truth.

After I had passed through great tribulation,
weeping and mourning in woods and solitary places alone, where I often desired to be,
I came to more settlement in my spirit, and peace began to spring in my soul,
where trouble and sorrow had been.
Then at times,
I would be ready to think that I should never again meet
with such combats and besetments by the enemy of my soul,
as I had passed through.
But the more I grew in experience of the dealings of the Lord with me,
so much the more did the enemy transform himself;^
footnote:[2 Corinthians 11:14-15]
and as he could not prevail by his former presentations, so in his subtlety,
he would invent new ones.
Thus I came clearly to see that it was not safe for
me to sit down satisfied with what I had passed through,
or in the victory I had already obtained, but I had to travel on in faith and patience,
and watch diligently in the light of Jesus Christ,
where the true power is still received.
For notwithstanding the many deliverances,
and the strength and victory I had experienced, the Lord,
according to the greatness of His wisdom,
was pleased to make me sensible of my own weakness,
and that there was no strength to stand, nor a place of safety for me to abide in,
except in His power; and under a sense thereof, I was humbled, bowed, and laid low.

Therefore I took up a godly resolution in His fear,
"`I will rely upon the sufficiency of Your power, O Lord, forever.`"
About six years after I had received the truth, through great exercise and godly sorrow,
I came to be settled in the power of God, and made weighty in my spirit thereby.
I had some openings from the Spirit of Truth in silent waiting upon the Lord,
which tended to minister comfort and satisfaction to my soul,
in a renewed experience of the dealings of the Lord with me,
and the Lord then opened my mouth with a testimony in the fresh spring of life,
which I was to give forth to His children and people.
But oh, the great combat I then had through reasoning, that I was but a child,
and that others were more fit and able to speak than I. But the Lord, by His power,
brought me into willingness, and with fear and trembling I spoke in our blessed meetings.

At one time,
as I was sitting in silence waiting upon the Lord
in a meeting of Friends in Pardshaw Crag,
a weighty exercise fell upon my spirit,
and it opened in me that I must go to the steeple-house at Cockermouth,
which was hard for me to give up to.
But the Lord, by His power, made me shake and tremble, and by it I was made willing to go.
But when I had given up, I desired to know what I was to do there,
which was the cause that, for a little time,
I was shut up within myself and was in some measure darkened.
So I cried unto the Lord, that if it was His will I should go, I would give up to it;
and being made sensible it was, I went in faith and quietness of mind and spirit.

As I was going, it appeared to me as if the priest were before me,
and it opened in me to say to him, "`If you are a minister of Christ,
stand to prove your practice;
and if it be the same as the apostles and ministers of Christ, in doctrine and practice,
I will acknowledge you; but if not, I am sent of God this day to testify against you.`"
And as soon as I entered the place where the hireling priest, George Larcum,
was preaching, he cried out, "`There is one come into the church like a mad-man,
with his hat on his head.
Churchwardens, put him out!`"
For he could not preach after I came into the steeple-house.
So they put me out, as he bid them.
This was in Oliver Cromwell`'s time,
and not long after the government was changed and
the priest himself was turned out of the place.
Sometime after I was put out, I was moved of the Lord to go in again,
and had strength given me to stay until the priest had finished;
but his preaching was burdensome and confused.
Then, with the aforesaid words, I opened my mouth in the fear of God,
which made the hireling go out with all the haste he could,
at a different door than he generally used;
and the people were in a great uproar--some to beat me,
and some to save me from being beaten.

When they had hauled me out of the house,
I was enabled by the power of God to declare the truth among the people,
and also to manifest the deceiver they followed.
And having obeyed the requirings of the Lord,
I came away in sweet peace and spiritual comfort in my heart.

At a certain time being at a meeting of Friends upon the Howhill, near Coldbecke,
in Cumberland, George Fletcher of Hutton Hall, a justice of the peace (so called),
came into the meeting in a rude manner,
riding among Friends who were sitting upon the ground,
and trodding with his horse`'s feet upon a woman`'s gown.
I was moved of the Lord to kneel down in prayer at the head of his horse,
and as a wicked persecutor of God`'s people,
he struck me bitterly over my head and face with his horse-whip.
When he saw he could not move me, he called his servant, being near by, to take me away,
who came in great fury and took me by the hair of my head, and drew me down the hill.
But I got upon my feet, and said to his master,
"`Do you pretend to be a justice of peace, and yet break the peace, and disturb,
persecute, and abuse God`'s peaceable people, and set your servant to do the same?`"
He said, "`You will know I am a justice of peace before I am done with you!
Could no place serve to meet in, but under my nose?`"
Yet this meeting was at a great distance from his dwelling, upon the common.
He committed me and three more to the common jail at Carlisle,
it being at the time when that act was in force which
imposed a penalty of five pounds for the first offence;
ten pounds for the second, and for the third, banishment.^
footnote:[Partly because of the political instability of the times
and the widespread fear of armed uprisings against the government,
and partly due to the envy and influence of the national clergy,
a law was passed (called the _Act Against Seditious Conventicles_)
forbidding all religious gatherings of five or more people,
besides the established meetings of the Church of England.]
By his warrant he caused one cow and a horse, worth six pounds ten shillings,
to be seized from my father (with whom I lived), for my fine of five pounds,
this being the first offence (so judged by him),
and he kept me in prison some weeks too.

George Martin, a wicked and hard-hearted man, being jailer,
put us in the common jail for several days and nights without either bread or water,
because we could not satisfy his covetous desire
by giving him eight pence a meal for our food.
So when he put us in the common jail,
he threatened that he would see how long we could live there without food,
and allowed no one that he could hinder from helping us,
nor would he allow any of our friends to bring us any bedding,
not so much as a little straw.
We had no place to lie upon but the prison window, upon the cold stones,
for the wall was thick, but there was room for only one at a time.
And when he saw he could not prevail, notwithstanding his cruelty,
he removed us from the common jail into a room in his own jailhouse,
where he kept several Friends prisoners for non-payment of tithes,
at the suit of the aforementioned George Fletcher.
The jailer was often cruel, wicked, and abusive in his behaviour to Friends;
but in a few years he was rewarded according to his doings,
for he himself was cast into prison for debt, and there ended his days.

When the quarter sessions began,
which was in about two weeks after our commitment at Carlisle,
we were called and examined by Philip Musgrove, a man of that city, called a justice,
but an old persecutor, who,
under a great pretence of love to us said that if we would but conform,
and come to the national church, they would show us all the favour they could.
And when any of us would try to answer his questions or proposals, he would say,
"`You must be silent, unless you will conform, for you may not preach here.
But,`" he would tauntingly say, "`When you are banished beyond the seas,
then you may preach there.`"
One of us replied, "`We are not afraid to be banished beyond the seas; for we do believe,
and have good cause so to do, that the Lord our God, whom we worship and serve,
and who by His great power has preserved us all along until now on this side the sea,
would also preserve us on the other side,
if we stand faithful in our testimony for Him.`"

We were set at liberty by the court that sessions, goods being taken for all our fines;
but the sheriff of the county, Willfrid Lawson, of Issel Hall, being there,
said to the jailer, "`If they will not pay fees, put them into the common jail again,
and keep them there until they rot.`"
So the jailer put us into the common jail again because we could not pay him fees,
where at that time there was a madman, and four with him for theft,
and two notorious cattle thieves called Redhead and Wadelad,
and also a woman for murdering her child.
Several of the relations and acquaintances of these were permitted
to come to see them after the court sessions were over,
who gave them so much to drink that most of them were basely drunk;
and the prison being a very small, nasty place,
they did so abuse themselves and us with their filthiness,
that it was enough almost to stifle some of us.
On the next day, we let the jailer know how we were abused,
whereupon he bid the turnkey to bring us to the room where we were before,
saying he hated to keep us there, for we were honest men, setting our religion aside.
One of us answered, "`If the fruit be good, the tree cannot be evil.`"
And in a little time after we had been in his house, he gave us our liberty,
without paying fees.
This was in the fifth month, 1663.

Here follows a letter I wrote while I was a prisoner at Carlisle.

[.embedded-content-document.letter]
--

[.salutation]
Dear Father and Mother,

My duty is hereby remembered to you; and my dear and tender love,
both naturally and spiritually, does hereby reach unto you both;
and as you are faithful according to what the Lord has made known unto you,
by His pure light, the Lord will preserve you.

Dear parents, as it is thus ordered that I am called to suffer,
for no other cause than worshipping God among His people, I desire you to be content,
and do not murmur or complain.
Rather, live in love, quietness, and all unity with each other,
that the blessing of the Lord may be upon you, and prosper what you go about;
for they that truly fear the Lord shall lack no good thing.
Let your faith stand here, dear hearts, and be patient and content in your minds,
and not too much concerned for me and my welfare.
For I am persuaded, feeling the evidence of Truth in my heart,
that I suffer not for evil-doing, but for obeying the requirings of the Lord, yes,
for worshipping and serving Him in spirit and in truth.
Therefore it is, and it shall continue to be well with me,
as I keep faithful unto the end.
Be not at all dejected or cast down in mind concerning me, but rather rejoice with me,
that the Lord has not only counted us worthy to believe in His name,
but also to suffer for the same.

From the city of Carlisle in Cumberland, the 8th day of the Fifth month, 1663.

[.signed-section-closing]
Your obedient son,

[.signed-section-signature]
John Banks.

--

Some time after, I had drawings in my spirit to visit some neighbouring counties,
such as Westmoreland and Lancashire, and when I was clear of those counties,
I returned home to my parents, and lived with them about a year more.

Upon the 26th day of the sixth month, 1664,
I took a Friend by the name of Ann Littledale as my wife,
in a public meeting of God`'s people in scorn called Quakers,
in a Friend`'s house in Pardshaw town, before many witnesses,
feeling freedom and liberty in the Lord so to do.
This was indeed a blessing and mercy that I received from His hand,
for which I am bound in duty to give Him the praise,
and to return all honour and glory to Him who lives forever.

About four years after I was married,
the Lord called me forth to travel in the work of the ministry,
and I was made willing to leave all in answer to His requirings,
and go into the south and west of England.
Yes, I was made willing to leave my dear wife and sweet child,
though very near and dear unto me,
and went forth in the power and Spirit of the Lord Jesus.
Our friend John Wilkinson of Cumberland and I travelled
together in the Lord`'s work and service.
We took our journey in the second month, 1668, travelled into Yorkshire,
and visited many meetings in various places,
where we had good service for the Lord and His truth.
From Yorkshire we travelled into Nottinghamshire, Leicestershire, and Warwickshire,
where we had many blessed meetings, and where I wrote the following letter to my wife.

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

Unto whom I am truly united;
I dearly salute you in the pure love and unity of the Spirit of Truth,
wherein the Lord has made us truly one, and let you know that I am well in all respects;
blessed and praised be the Lord our God forevermore.

In my heart I reach forth a hand unto you; give me yours,
and let us go along together in the work and service of the Lord,
so that we may be a strength and encouragement to each other to go on in faithfulness,
and finish a faithful testimony for the Lord in what He requires of us,
in doing or suffering, and giving up whatever we have or enjoy in this world.

My dear heart, give all up freely, as to the Lord our God,
in order to be ordered and disposed of by Him who is wise and wonderful in counsel,
and to be admired by all who truly love and fear Him,
and wait for His glorious appearance of light and life.
Take no thought nor care for me except in the Lord,
who has a care and tender regard unto us, and all His people,
as our hearts are kept near to Him.

We came this day to see our dear friend William Dewsbury,
and intend to travel through the county, visiting of the seed of God, towards Bristol,
and then however the Lord may order us.

So with the remembrance of my duty to my parents, and my love to Friends,
as though I named them, I remain your dear and loving husband,

[.signed-section-signature]
J+++.+++ B.

[.signed-section-context-close]
Warwick, the 4th of the Fourth month, 1668.

--

My wife`'s letter to me.

[.embedded-content-document.letter]
--

[.salutation]
Dear Husband,

After long expectation to hear from you, I have, before the writing of this,
received two letters, whereby I was much satisfied and refreshed;
but in your last from Somersetshire,
I observed that you have been under weakness of body for some time.
At the first hearing of this I was sad in my spirit,
but considering the greatness and sufficiency of the Lord`'s love and power,
in whom is our strength, I rest satisfied,
hoping that all things will work for good in the end.
Dear husband, I have been, and still am brought very low in body by a strong fever,
but am well in mind, blessed be the Lord.
It was one month last fifth-day when the sickness took me,
and in about two weeks time I received some strength, but then became worse again,
and am now very weak.
I greatly desire this letter may come safe to your hand,
that you may understand how it is with me, and that, in the wisdom of God,
you may consider what may tend most for the glory of God in this matter.
I can truly say, in a sense of the Lord`'s love and truth (according to my measure),
that whether ever I see your face again or not,
I desire nothing more than that the will of the Lord may be done in all things,
whether in life or death; to whose care and fatherly protection I commit and commend you,
and dearly salute you, with love to your companion John Wilkinson, and bid you farewell;
and am your dear and loving wife,

[.signed-section-signature]
Ann Banks

[.signed-section-context-close]
Whinfell-Hall, in Cumberland, the 19th of the Fifth month, 1668.

--

From here we travelled westward, through part of Devonshire, and into Dorsetshire,
Hampshire, Wiltshire, and so up to London.
The Lord was with us; and Friends were greatly refreshed and comforted with us,
and we with them.

There was great openness and tenderness in those days among Friends,
and among many other people where we came,
and the witness of God was soon reached in their hearts.
We had very large and full meetings in most places where we travelled,
and many were convinced and are yet alive in the truth, standing witnesses for God.
At London, I wrote the following letters to my wife and to my apprentice, Peter Fearon:

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

Yours I have received, whereby I understand the great weakness you have been in,
which has been a near trial and great exercise to me.
But when I consider the large love of God to you,
in preserving you in faith to believe in Him,
with patience and true contentedness to give up unto Him under your great weakness,
it has eased my burden and lessened my exercise.

Wait daily to feel the Lord to be your strength, in the time of your greatest weakness.
Rely wholly upon Him, trust in Him, believe in Him, and He will never fail you.
He can be more to you than a husband, and to your child than her father.
May you know your portion increased in Him, and your inheritance to be enlarged,
that you may dwell in the borders of His sanctuary,
in the sight of His glorious Son forevermore, and may feel your faith increase,
and your patience and contentedness to remain in Him, by the sufficiency of whose power,
safety and preservation are known.
As we abide in Him, whether we live or die, we are the Lord`'s,
and it shall be well with us forevermore.
And it matters not what we suffer or undergo in this life, if that be attained unto.

Remember my dear and tender love, and also my duty, to my parents;
for still I find myself bound to be tender over them,
and to do for them whatever lies in my power,
under the consideration of what they have done for me.
With the salutation of my true love to yourself, in the remembrance of our little one,
and my love to Friends, and relations and neighbours, I remain your loving husband,

[.signed-section-signature]
J+++.+++ B.

[.postscript]
====

And now Peter Fearon, my apprentice: Mark, and take good notice what I say to you;
lay it to heart, and consider these things well, now in my absence.
My true and unfeigned love is to you,
and I desire your prosperity and welfare in all that is good,
both inwardly and outwardly;
but first of all and chiefly in that which pertains to the salvation of your soul;
the way whereof, the Lord, in His love, has in some measure made manifest unto you.
Therefore, be watchful to walk in it; that is to say,
take heed to the light of Christ Jesus in you, the measure of the Spirit of Truth,
which will lead you into all truth and out of all deceit as you do obey and follow it.
Whatever this pure light in you makes manifest to be evil and reproves you for,
depart from it, though it be that which no other eye can see nor any man know of,
yet you must forsake it,
and wait and watch daily against it in the light that makes it manifest,
and you will receive power to cast it off and depart from it.
The light, which is Christ Jesus--the way, the truth,
and the life--teaches to be sober and lowly-minded.
It teaches that our words ought to be few and savoury,
and that we be gentle and easily entreated, not high-minded,
but fearing the living God continually.
This keeps the heart clean as you abide in it, keeping low and humble in self-denial,
and willing to take up and bear the daily cross; and as this goes on in the heart,
you thereby come to depart from all iniquity.
"`All things that are reproved are made manifest by the light,
and whatsoever makes manifest, is light;`"^
footnote:[Ephesians 5:13]
and that which the light makes manifest to be sin and evil, either in word or action,
you must forsake and deny yourself in.
For this is the will and mind of the Lord, by His blessed Spirit;
and he that knows his master`'s will and does it not,
according to the Scriptures of truth, must be beaten with many stripes.^
footnote:[Luke 12:47-48]

As to things appertaining to your work and service, be patient and content,
and go quietly about your business in the fear of God.
And do not say in yourself that I will think you have not done enough,
for it is far from me to think in this way.
My only desire is, that if you do ever so little, be careful to do it well.
But, above all things, be truly willing and obedient unto your mistress,
for whatsoever you do to her, I take it as done to myself.
And mind to carry yourself in love, and be a good example in my family,
that so you may all live in love and unity together; in which the Lord preserve you all.

====

[.signed-section-closing]
Your loving master,

[.signed-section-signature]
J+++.+++ B.

[.signed-section-context-close]
From Whitechapel in London, the 3rd day of the Sixth month, 1668.

--

From there I proceeded in my journey westward,
but my greatest exercise was in Westmoreland, and at Hartford as I came up to London,
and afterward at Reading, Wycombe, Charlcote, Bristol, and through Wiltshire,
where I had fifteen meetings in three weeks,
at all which meetings there were many of those unruly separate-spirited people,^
footnote:[Banks`' reference to this "`separate-spirited
people`" is probably a reference to followers of John Perrot,
who in the name of promoting a "`more spiritual dispensation`" of Christianity,
opposed some of the order and discipline in the Society of Friends,
and went off into imaginations and fleshly liberties.]
though none of them had power to oppose me.
Yet after most meetings they would be greatly enraged against me behind my back,
and threaten what they would do at the next meeting,
but never had power to open their mouth in a meeting to oppose;
for it pleased the Lord to be with me in a wonderful manner,
to His praise and glory I speak it with reverence and humility before Him.
For my testimony was as a flame of fire among briars and thorns,
as many of God`'s people could witness.

My companion, Christopher Story, was a help and comfort to me,
though little involved in that exercise; yet he greatly sympathized with me in spirit,
and had a good service to Friends,
and continues a solid weighty man in the work of the ministry, both at home and abroad.

Oh! great was the exercise I travailed under many times, both in body and spirit;
for the weight and wickedness of the separate spirit bore hard upon me,
but the Lord`'s power chained and limited it.
I had little benefit of either food or sleep, especially in Wiltshire;
for they who were of that spirit followed me from meeting to meeting.

[.offset]
The following letter I wrote to my daughter, after she was placed at service in London,
in the year 1682.

[.embedded-content-document.letter]
--

[.salutation]
Sarah Banks, my eldest daughter,

You have been near and dear to me ever since the day you were born,
and I have felt a godly care as a tender father,
that you might be nourished up in your young and tender years for your preservation;
with many desires in my heart to Almighty God, that as you grew in years,
He would be pleased to make you sensible and give you an understanding
of those things which make for your everlasting peace,
and the salvation of your soul in the kingdom of glory, when time here shall be no more.

And now, dear child, the Lord having thus far answered my desires,
and enabled me to perform my care towards you;
I have a further concern upon my mind for the good of your soul; which,
if you are truly mindful of it, will tend to your good,
and will never hinder you from anything that is really needful for you.

First of all I would put you in mind, that God,
according to His Divine Wisdom and Providence, gave you life and breath,
which you ought to prize and value as a mercy,
among many more you have received from Him.
And you have also come to an understanding, in some degree,
how to behave yourself as a child of God,
by the light and grace of our Lord Jesus Christ,
which He has placed in the secret of your heart for a teacher in all things.
My concern now is to stir you up unto this by way of remembrance,
to be faithful and obedient to its requirings, whether great or small.

This light and grace of our Lord Jesus Christ teaches you your duty towards God,
to your parents, and to all men and women.
It first teaches you to fear and love God, and to wait upon, worship,
and serve Him with all your mind and strength, that He alone,
by His Spirit manifested in and through Jesus Christ,
may be your chiefest love and delight.
It will teach you as you are watchful, to deny all ungodliness and worldly lusts,
to take pleasure and delight in meeting together with God`'s people,
to worship Him in spirit and truth,
so that you may come more and more to have unity and fellowship with His faithful children,
according to your measure.

This pure light of the Son of God teaches you to be lowly-minded,
sober and watchful over your words, carriage, and behaviour, in your life and conduct,
and to choose such as these for your companions, and not those,
who though they profess the truth, are light, careless, and high-minded,
following the fashions of the world, tattling and tale-bearing,
and meddling with other men`'s and women`'s matters which do not concern them.
Be sure you are found only in what concerns you, and what is appropriate to your place,
as a servant.

This is the way to grow in grace and saving knowledge,
and to have the beautiful adornment which is the ornament of a meek and quiet spirit,
which is better than costly attire and is precious in God`'s sight.
This is the way to be beloved of God and His people, to grow up a good woman,
and to make a blessed and happy end.
This blessed way and course of life, my soul desires for you, my dear child,
that you may carefully live and keep in it, to the end of your days.
Amen.

The light of Jesus Christ, which thus teaches you your duty towards God,
will also teach you your duty towards all men, women, servants, and children,
especially now in your place where you are a servant.
It will teach you to be faithful, willing,
and obedient to your master and mistress in all things that are fitting and right,
to be careful that nothing is wasted under your hand
that has been committed to your trust,
and to watch with an eye for good over all in the family where you serve.
If you see anything amiss, tell it not abroad to any whereby it may cause dissension;
but first tell the individual in love, for so you would desire to be dealt with.
This is according to the righteous law of God, which is light,
that teaches to do unto all as we would have them do unto us.
And when anything happens amiss with yourself,
and you are spoken to and reproved for it (as Paul counselled Titus concerning servants),
I exhort you in tenderness to murmur not, nor answer back,
except to say that the wrong shall be amended.

My dear child, the desire of my heart is unto Almighty God,
that this my counsel and advice may be made effectual unto you,
and that in the serious consideration thereof,
with honest desires raised in you to perform and answer the same,
your heart may be truly broken and tendered before the Lord,
and so kept in all lowliness and humility before Him, unto the end of your days.
Amen.

[.signed-section-closing]
So prays your tender and affectionate father,

[.signed-section-signature]
John Banks.

--

This year I went to Ireland again, from which I wrote the following letter to my wife:

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

In that which opens my heart to the Lord, and makes me truly tender before Him,
I am at this time enlarged in tenderness towards you,
with our dear children and servants,
desiring to the Lord that by the same power your
heart may be kept open in tenderness before Him,
that you may increase more and more, and that thus we may have a sense one of the other,
of our growing up together by the living virtue that
springs out of the Root which bears us.
For so long as our habitation and dwelling is here in the Root,
though our work and service are not the same,
because of the diversity of the gifts given to us,
yet we shall grow up together as do all the faithful in Christ Jesus.

May the Lord preserve you in His fear, and guide you in His wisdom,
that you may be a good example before your children and servants,
being careful to train them up in the same fear,
to walk according to the truth in all things, always having a tender regard over them,
chiefly for the good of their souls, as well as their bodies; for,
you have many opportunities wherein you may do good unto them, which I do not have.
So, my dear, be concerned for their good as they grow up in understanding,
for they are quick and apprehensive,
and can quickly see if they are indulged in anything which they ought not to have.
And if we thus indulge them, we lose our dominion and authority over them.
Let our care be to reach unto and have the testimony of the Witness of God in them,
even the Witness of His gracious Spirit, which most of them have come to a sense of,
and by which they know what they should do, and what they should leave undone.
And as this Witness rises up in them and is minded, it will make good children of them;
but much lies in the examples that we are before them.

For this reason,
I am still more and more concerned in my mind how to behave towards them,
to the end that I may be found clear of my charge and duty concerning them,
especially for the good of their souls.
The Lord has richly blessed us with them as manifold mercies,
but there remains a great care and concern on our parts to be performed;
for lack of which, I clearly see that many children who might have brought honour to God,
His truth, and their parents are, on the contrary, a dishonour to all,
though they may have great possessions in the earth, and fulness, ease,
and great preferment (as it is called).
But having lost the Truth, what good are these things,
though many look too much at such things,
and neglect the weightier matters which ought to be the greatest part of their concern.

And now, dear children, you may understand something of our care and concern for you.
You that have come to this understanding, I admonish you as a tender father,
in the love of God, that you take upon yourselves this good resolution, and say:
"`How should I behave myself in all things, both in word and deed, conduct and behaviour,
as an obedient child,
both to my dear father and mother who have such a
care for my good and preservation every way,
and now especially to my mother, because my father is absent?`"
And in order that you may act in such a way, now to her, and to me when I am present,
let all be subject and condescending one unto another.
Live in love, quietness, and good-will towards one another;
and be sober-minded in the fear of God,
keeping out of all company except that which is sober.

And by no means be idle at any time, but give yourselves to some good employment,
such as your body and understanding are able to perform,
with a willing and ready mind to be helpful to your mother in her concerns,
and be careful to mind your books when you have time for it.
Read the holy Scriptures, and Friends`' books,
and be diligent in your course and order to keep to meetings,
weekdays as well as first-days, that so the work of your hands may be made more easy,
sweet, and comfortable unto you, and that God may have the praise, honour,
and glory for all His blessings and mercies, who is eternally worthy.

Peter Fearon, who was my servant for seven years,
is now my acceptable companion in the work of the Gospel.

[.signed-section-context-close]
Mountmellick in Ireland, the 23rd of the Fourth month, 1682.

--

In the beginning of the second month of the year 1684,
I was committed to prison at the suit of the aforementioned George Fletcher,
impropriator,
because for conscience sake I could do no otherwise than
bear my testimony against that great oppression of tithes;
being first subpoenaed, and afterwards arrested,
because in obedience to Christ`'s command I could
not put in my answer upon oath to his bill.
On the same day that I was taken to prison,
there came twelve men with a warrant from George Fletcher,
who seized and took away seven pounds and ten shillings worth of my goods,
for part of a fine of twenty pounds for a Friend in the
ministry who spoke in our meetinghouse at Pardsay-Crag,
it being in the time of the penal act against conventicles.
The goods were sold by him, or by his order,
and so much more taken from other Friends for the said fine,
as amounted to thirty-five pounds.

My imprisonment continued six years and nine months,
when I was freed by King William`'s Act of Grace.^
footnote:[In May of 1690, a year after coming to power,
William III declared a general pardon for a large
number of political and religious prisoners.]

Here follows a true relation of the abuses and cruelty that myself
and some of my fellow-prisoners suffered from the jailer,
George Lancake, and the turnkey, Alexander Richardson,
for no other cause than worshipping God in our prison-house,
and in obedience unto the Lord, speaking in His name in exhortation and prayer,
and sometimes by way of warning to people as they passed by our prison-window,
seeking to turn them to the Lord by a speedy repentance and the amendment of their ways.

On the 20th day of the fifth month, 1684, a little before the time of our meeting,
there being five other Friends prisoners with me, the jailer said to me,
"`Unless you promise me that you will not preach this day, I will take you away.`"
I answered, "`I can make you no such promise,
neither do I know before the time comes whether I will preach.`"
"`Then,`" said he, "`I have prepared another place for you.`"
He took me by my arm, and led me along, and put me in a foul-smelling, smokey room,
under which they brewed beer, and locked me in,
where I remained three days and two nights, without any bed.

The first-day in the evening after I was put there, the turnkey came and opened the door,
and said, "`My master has sent me to tell you to come out and go to your friends.`"
But I answered, "`Go tell your master, I shall not come out of this place to another,
until the one who put me here fetches me himself.`"^
footnote:[By what follows,
it appears that John Banks was given to see that the jailor desired to ensnare him,
seeking grounds to charge him with escaping from there on his own.]
He went and told him, and the jailer then bid his servant, "`Tell him,
he will stay in there until he rots before I will fetch him.`"
But I took no notice of that, knowing well what I did.
There were several prisoners in his house for debt,
who had wastefully spent most of their estates, who then said to the jailer,
"`The Quaker says he will not come forth till you fetch him,
and you say he shall stay there till he rots before you will do it;
we will see who will get the victory!`"

That night and the next day and night passed over,
and on the third day towards the evening the turnkey came again,
and told me his master had sent him to pull me out by force,
if I would not come willingly, that being the fourth time he had sent him.
The turnkey was a bulky, strong, rugged-spirited fellow.
Being seated, I stood up before him and said, "`If you can take me by force, do it;
here I am,`" stretching forth my arms.
He took me by one arm and pulled with all his strength but could not move me at all,
and then wickedly said, "`God bless me, I think the devil is in the man,
I cannot move him!`" "`No,`" said I, "`the devil is in you,
and I am stronger through the power of God than both you and the devil.
Go, tell your master that.`"

All this while I felt his master was in torment,
being troubled in his conscience both day and night, as afterwards he confessed.
So the turnkey went and told him what he had done, and what I said, and then said,
"`I think he is as strong as twenty men,
for I could not move him any more than if he had been a tree.`"
But in a little time after the jailer himself came to me and said, "`What now, John,
what is the reason you will not come forth?
I have sent my man so often to let you go to your friends`" I answered,
"`Because it was your will and pleasure to lead me here,
you shall also lead me back again, or here I intend to stay.
I shall be a faithful prisoner to you, I shall not make an escape.`"
After some more words had passed between us, he took me by the arm, saying, "`Well,
come then, if nothing else will do, I will lead you back again;`" which he did,
down the stairs through the court, to the door from which he brought me,
and then thrust me in, saying, "`Go your way, I wish to God I had never seen your face.`"
Then the prisoners for debt who were standing at his door,
looked upon us and laughed and said, "`The Quaker has got the victory!`"

After this, for seven meetings in a row,
the turnkey hauled me out into the jailer`'s house,
being urged on by the jailer with many threatening words,
charging his servant not to let one of us go out at the gate of his court.

On the 13th day of the seventh month, our friend Peter Fearon came to visit us prisoners.
We sat down together to wait upon the Lord,
and after a short time Peter Fearon began to pray.
But the turnkey soon came in in a great rage, and asked our friend,
"`Where did you come from? Get out of here!`"
And so began to pull him in a most cruel manner,
taking him by the scarf and throwing him back into a bed,
saying he would either hang him, or pull out his throat.
He continued shaking and pulling him by his scarf, or neckcloth,
dragging him out of the door into the jailer`'s house
with curses and oaths about what he would do to him.
For this I reproved both the jailer and turnkey sharply,
and in a little time they let him go.
This day I wrote to my wife and children the following letter.

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

You are truly so to me--even so near that we are truly one,
to help bear each other`'s burdens, sympathize,
and be truly concerned for one another`'s preservation, both at home and abroad,
in prison or at liberty, in sickness or health; and not only for the body,
but for the eternal happiness and well-being of the soul.
This is the right concern of husband and wife who are truly joined together,
and who have come to know the true marriage which is God`'s joining.
Oh, how this helps and strengthens, encourages and bears me up,
in the times of the greatest exercise.

And now, my dear, as to my present state under suffering, it is well,
though I am not altogether well in body, yet in the Lord`'s time I hope I shall be so.
I say it is well, though my condition is what it is;
for I am well assured that this is according to His will,
and in doing His will I have great peace and satisfaction,
although the wrath and cruelty of ungodly men are still much bent against me.
But I believe it will not be long until the Lord, by His power, will bring them down;
for I see, in the light of the Lord,
that their strength grows weak and their expectation concerning me begins to fail.
Howbeit, whatsoever the Lord may yet allow them to inflict upon my body,
I consider all that may be endured or passed through here as but a light affliction,
because of the evidence and assurance of that far more exceeding
weight of eternal glory which I have in view,
through faith in Jesus Christ,
and I am travelling in the way that will bring me to the everlasting possession.

And so, my dear,
let us freely and faithfully follow those things which will
make for our everlasting peace and joy with the Lord,
whereby we may have the full assurance of the salvation
of our souls in the kingdom of happiness and glory,
when time here shall be no more, regardless of what else we may enjoy of this world,
be it more or less.
The Lord gives and takes away, or allows it so to be,
according to His good will and pleasure, blessed be His holy name,
and reverenced be His glorious power, now and forevermore.
Amen!

And now, my dear children, concerning whom my heart is often made tender,
my heart yearns for your preservation from evil,
and that you may grow and increase in all that is good.
Give ear every one of you and take good notice what I have to say unto you.

John, my son, and dear child: God in His love, according to His Divine wisdom,
has given you a measure or manifestation of His good Spirit, grace, or light,
which He has placed in your heart and conscience
as a witness against every appearance of evil.
This, in some degree, you have come to the knowledge of;
whereby you know you should do that which is good, and shun all that is evil.
This light of the Lord Jesus Christ teaches you not to be wild or careless,
or given to any idle talking or unsavoury words; and if you should do or act contrary,
this pure light will reprove and judge you for it.
This is that, my child, which you must mind and love,
and then it will not only discover all sin and every evil to you,
but as you take heed to its checks, reproofs, and manifestations,
you will receive power over those things, one after another,
which the light makes manifest unto you,
and will keep you from all light and airy company,
to have your mind kept in the fear of God to serve Him.
Above all love the truth, and those who are in it.
And love to go to Friends`' meetings, and delight in their company;
so will you come to be weaned from every appearance of evil, and to be sober and solid,
as is fitting in the truth.
This is your duty towards God, be careful to be found walking in it;
and as you are found in the performance of this,
the pure light and grace of our Lord Jesus Christ,
which teaches you your duty towards God, and how to obey Him,
will also teach you your duty to your parents, and in particular to your dear mother,
and also to your sisters and brother.
You being the eldest at home, I expect your care and diligence in this,
in love and tenderness to your dear mother,
that so you may be a strength and help to her now in my absence.
I charge you look to it, as you expect a blessing from the Lord,
and my favour and countenance.
Also be careful that there be no strife between you
and your sisters and brother upon any occasion,
neither in words nor actions; but be tender and loving to one another.

And now to you Ann and Mary, my daughters and dear children, whom I dearly love,
with all the rest: be sure you speak no evil of one another, nor do wrong to anybody.
Carry no tales from one house to another, and when you are sent on an errand,
go and return quickly.
Be loving, kind, and respectful one to the other, and to your brethren,
sister and servants, and help one another willingly in all things,
but especially your dear mother.
Be dutiful and obedient unto her in all things that she bids you to do; I charge you,
do it readily and willingly, without murmuring.
My dear children, keep these my words in mind daily,
that you may all serve one another in love.

And to you, little William and Emme, the youngest.
My dear children, be sure you love one another;
do not go out of the way when you go to school, or when you return home.
Do no hurt to any, and mind your books well that you may be good students.
Be sure you remember what I say to you,
and above all things be careful to do what your mother bids you,
and to love your brother and sisters.
Dear children, all of you mind your books; read the holy Scriptures;
and may the Lord bless and preserve you all in love, unity, peace, and quietness,
fearing, serving, and loving God with all your hearts, and then all will be well.

I find a great alteration in my body,
because of the cruelty and abuse of the jailer and his turnkey,
together with the scarcity of fresh air;
for I have had no liberty to walk abroad these several months.
The jailer does not permit me to speak or pray in any meetings once he hears my voice;
for which, the Lord will assuredly meet with him by His judgments.

I am your loving husband, my dear wife, and your tender father, my dear children,

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
From my prison-house, in Carlisle, the 13th of the Seventh month, 1684.

--

On the 15th of the same month, in the evening,
the jailer came and ordered Thomas Hall and myself to the common jail,
because we could not accede to his unreasonable demands; however,
there was not room in the common jail,
for it was wholly taken up with poor debtors and thieves.
Having been sick for some time, and not well recovered, a Friend said to the jailer,
"`If this our friend dies through your cruelty and abuse,
his blood will be required at your hands.`"
He answered, "`I do not care if he ever stands upon his feet again;
I will put him in the common jail.`"
I asked him, "`Is the place fit for us to be put in, especially myself, not being well?`"
He said, "`It is what I have for you, and you may sit or lie as you can;
and if there is not room for you to lie one by the other, you may lie one upon the other;
and if there was not room elsewhere, you may go into the sink`" which was a nasty,
stinking hole, filled up with excrement and straw; which fulfils that saying,
"`The tender mercies of the wicked are cruel.`"^
footnote:[Proverbs 12:10]

Accordingly, he put us two among the debtors in the common jail,
where there was no room either to sit or lie,
and we were forced to sit in our clothes all night by the sink.
But the next day the jailer brought out one of the
poor debtors and removed him to his house,
where he lodged him.
Then we got some straw and bedding to lay on the ground in the debtor`'s place,
which was very raw and wet, and got stones for our bedstead, head and feet,
and we were for the most part locked up there for thirteen days and nights together.
But notwithstanding the weakness that attended me when I was put there,
and the nastiness of the place,
the Lord was pleased to make it as a place of healing
and restoration of health and strength to me;
so that when the jailer took me from that place again,
as I was going down the street to the place from which he took me,
several people coming forth to look upon me said,
"`He looks better than he did when they put him into the
common jail,`"--which was cause of rejoicing to me;
praises, honour, and glory be given to the most high God, who by His own healing,
restoring, preserving power, can bring to pass whatsoever seems good in His eyes!

One thing more is fit to be taken notice of,
to set forth the cruelty and hard-heartedness of the jailer.
My dear wife, with other Friends, came to visit me during this time in the common jail,
which was a journey of above twenty miles from my house.
She requested the jailer that he would be so kind
as to permit me to come out of the common jail,
and to be with her in some other place; but there being no compassion in him,
he would not allow me to come to her;
but sent word by his turnkey that if she desired to be with me,
she might do so in the common jail, but in no other place.
So there she did contentedly abide with me until the next day,
rather than leave me and stay in a better place.

One time when I was doing some work in the common jail,
the jailer came to me and said mockingly, "`John,
you have scarce enough light to see your work,`"
(there being very little light in the prison),
"`but what does that matter?`"
said he, "`you have light enough within.`"
I answered, "`Yes, blessed be the Lord my God forever, so I do;
but you have little of it, for if you had more,
you would see your way and know what to do better than you now do.`"
So he turned from me and said no more, but took my fellow prisoner, Thomas Hall,
away from me at the end of thirteen days, and kept me there three more days and nights,
and then removed me as aforesaid.

[.asterism]
'''

_As mentioned previously,
John Banks continued a prisoner for nearly seven years,
but was finally released by an act of King William III in 1690.
The year following his release his wife passed away,
about which painful event he wrote the following:
"`Though our separation by death was the greatest trial I ever met with,
yet the Lord in whom I trust was and is my preserver,
in both that and many other deep trials and exercises;
to whom I am deeply engaged in all humility to give the praise,
and to return unto Him honour and glory, who is God over all; blessed forever. Amen!`"
He continued a faithful servant and a useful minister in the body of Christ,
traveling and strengthening the church for the next twenty years,
as the remainder of his journal recounts in detail.
A few hours before he died, he said to those who were with him, "`It is well with me,
and I am assured it will be well; I have nothing to do but to die,
and I shall end in the truth as I began.`"
He was very sensible to the end,
and after a life devoted to the furtherance of the kingdom of Jesus Christ,
he died in peace, the 6th of the eighth month, 1710, aged seventy-three years._
