== Preface by William Penn

[.salutation]
Friendly Reader,

The labors of the servants of God ought always to be precious in the eyes of his people,
and for that reason the very fragments of their
services are to be gathered up for edification.
It is this which induces us to exhibit the following pages to public view,
as well as the hope that it may please God to make them
profitable to such as seriously peruse them.

We have always found the Lord ready to second the services of
his worthies upon the spirits of their readers,
not permitting that which is his own to go without a voucher in every conscience.
I mean those divine truths which it has pleased him to reveal by his own blessed Spirit,
without which no man can rightly perceive the things of God or be spiritually-minded,
which is life and peace.
This indeed is the only saving evidence of heavenly truths,
which made that excellent apostle say,
"`We know that we are of God, and that the whole world lies in wickedness.`"

In that day,
true and undefiled religion before God and the Father consisted in visiting the
fatherless and widows in their affliction and keeping unspotted from the world,
not merely a godly tradition of what others have enjoyed,
but the experiential enjoyment and knowledge thereof by
the operation of the Divine power in their own hearts,
which makes an inward Jew and an accomplished Christian,
whose praise is not of men but of God.

Such are Christians of Christ's making, who can say with the apostle,
"`It is not we that live, but Christ that lives in us,`"
dying daily to self and rising
up through faith in the Son of God to newness of life.
Here formality bows to reality, memory to feeling, letter to Spirit, and form to power;
which brings to the regeneration, without which no man can inherit the kingdom of God,
and by which he is enabled in every state to cry Abba, Father.

You will see a great deal of this in the following author's writings,
and that he rightly began with a just distinction
between true wisdom and the fame of wisdom,
between what was of God and taught by God,
and what was of man and taught by man--which last at best is
but a sandy foundation for religion to be built upon,
or rather the faith and hope of man in reference to religion and salvation by it.

Oh! that none who make profession of the dispensation of the Spirit may build apart
from the work of Jesus Christ in their own souls in reference to his prophetical,
priestly, and kingly offices.
For God his Father gave him as a tried stone, elect and precious, to build by and upon,
in which great and glorious truth we do most humbly beseech the Almighty,
who is the God of the spirits of all flesh, the Father of lights and spirits,
to ground and establish all his visited and convinced ones,
that so they may grow up unto a holy house and building to the Lord.
So shall purity, peace,
and charity abound in the house and sanctuary which he has pitched and not man.

As to this worthy man, the author of the following treatises,
I may say that his memorial is blessed, having known him above forty-four years.
He was a heavenly minister of experiential religion,
of a sound judgment and pious practice, valiant for truth upon the earth,
and ready to serve all in the love and peace of the Gospel.
He was among the first in Cumberland who received the
glad tidings of it and then readily gave up,
with other brethren, to declare unto others what God had done for their souls.

Thus I first met him, and as I received his testimony through its savor of life,
so I was kindly encouraged by him in the belief of the blessed doctrine of the light,
spirit, grace, and truth of Christ in the inward parts, reproving, instructing,
reforming, and redeeming those souls from the evil of the world,
who were obedient thereunto.
He was a means of strength to my soul in the early days of my convincement,
together with his dear and faithful brother and fellow-traveler,
John Wilkinson of Cumberland, formerly a very zealous and able Independent minister.

Before I take my leave of you, reader,
let me advise you to hold your religion in the Spirit, whether you pray, praise,
or minister to others.
Go forth in the ability that God gives you.
Presume not to awaken your Beloved before his time.
Be not your own in your performances, but the Lord's,
and you shall not hold the truth in unrighteousness, as too many do,
but according to the oracle of God,
who will never leave nor forsake those who will take counsel of him;
which that all God's people may do, is, and has long been,
the earnest desire and fervent supplication of their
and your faithful friend in the Lord Jesus Christ,

[.signed-section-signature]
William Penn

[.signed-section-context-close]
London, the 23rd of the Twelfth month, 1711.
