== Supplement to his Journal / With an Account of his Latter End and Dying Words

After settling in Somersetshire as aforesaid, by marriage with his second wife,
Hannah Champion, an honest woman of Mear in the said county, in the eighth month, 1696;
he travelled in the work of the ministry in the western and adjacent counties,
while he was of ability; particularly into Devonshire and Cornwall,
with Paul Moon of Bristol, in 1697.
The same year he went to visit Friends in his native county of Cumberland,
and usually went to the Yearly Meeting at London, as long as he was able,
and several times into the north.
In the year 1704, he was at the Yearly Meeting in London, and had good service there,
which was the last time he attended it.
He dwelt fourteen years in the county of Somerset, from the time of his settling there,
till his death; and was very serviceable in that county, not only as to his ministry,
but in helping Friends in establishing the good
order of truth in Monthly and Quarterly Meetings.
Though I must needs say for the honor of that county, they had been long,
even from the year 1660,
in the practice of the wholesome order of truth in their meetings,
which were set up by the power of God for the well-regulating of our religious Society,
and which Friends generally through the nation are in the practice of; yet he,
with several other worthy elders,
were instrumental in improving and confirming Friends in it,
for the honor of truth and our holy profession, not only by word and doctrine,
but by life and practice.

About the sixth month, 1705, he was taken very ill and weak,
being much afflicted with the gout, so that he was confined to his bed,
in which condition I found him when I went to see him at Mear,
in the beginning of the third month, 1707; yet very fresh and living,
and clear in his understanding.
He disclosed his mind to me in some particulars to my satisfaction,
and I was comforted to find the Lord so with him.
He continued weak about two years, so that he could not travel as in times past;
but afterwards he somewhat recovered again, and went abroad; and in the year 1708,
removed from Mear to Street, near Glastonbury, for his health's sake,
and to be near his friends and meetings,
where he enjoyed his health better for some time;
but was still often very much afflicted with his old distemper and other infirmities,
as age came on.
Some time after his removal to Street, he wrote me a loving letter,
of which I shall transcribe some part.

[.embedded-content-document.letter]
--

[.salutation]
Dear Friend,

That which makes us near and dear one to another is,
because we have received a certain knowledge that we
are children of one Father who is holy and heavenly,
begotten again to a lively hope, in and through Jesus Christ,
by the quickening of his eternal Spirit,
to serve him the true and living God in newness of life.
He has instructed us by the teachings of his all-sufficient grace and holy Spirit,
how we may wait upon, worship, and serve him, and in what;
even in the spirit and seed of life, by which, we can cry, 'Abba Father.'
In a day never to be forgotten by us, he did not only bring to the birth,
but gave power to bring forth; and as a tender Father, from the time of our infancy,
by his helping hand, has always waited to be good and gracious unto us,
giving us rain and heavenly dew, which he has caused many times to descend upon us,
that we might grow from one stature and degree of holiness and strength to another;
that so, in our day and time,
we might come to answer the good end for which he has made us a people.
This was not only that we should meet together to wait upon, worship,
and serve him in Spirit and Truth, though chiefly therein,
but that we might grow up together, according to our several gifts of his holy,
pure Spirit, to the degree of elders and fathers,
to do work and service in the church of Christ;
and in a more public manner amongst God's people, where there is much to be done.
Happy are they who can say in truth, what they do in that service,
they do it unto the Lord, and for his worthy name and glory;
great shall be their peace and comfort here, with a heavenly blessing in Christ Jesus,
and more abundantly and eternal in the heaven of heavens.

But why should I write of these things to you;
only that we delight to be telling one another
what the Lord our God has done for our souls;
who, by his mighty power, has been our preserver and upholder,
ever since he was pleased to give us the knowledge of himself;
in and through various trials, deep exercises, temptations, and afflictions,
both without and within; and all for the end that we may be helpful one to another,
in building up, and strengthening one another in the most holy faith,
which works in the heart;
as living members which make up that body which is complete in him our holy head,
the Lord Jesus Christ; as those who have a fellow-feeling,
and sympathize one with another, under all our exercises; for how can it otherwise be,
but that members of one body, which are living and sensible ones,
should have a true feeling of one another,
and a godly care and true tenderness that no one be hurt.

My heart is open to you,
in that same love in which our brotherly unity and fellowship did first begin;
in which you are truly near unto me,
even in the love of God and unity of his blessed Spirit,
in which the Lord preserve us little and low in our own eyes,
near to him and one unto another, faithful unto the end and in the end.
Amen!

Great has been my affliction, even more than I am able to express;
and even so has the tender care of my heavenly Father been over me, beyond my utterance,
in preserving me in and through it all to himself, sensible of my inward condition,
with my understanding open and clear; praises, living praises,
unto him the living and eternal God, who has all power in his own hand,
and is able to bring to pass whatsoever seems good in his eyes!
For when I was in the midst of my affliction,
and my neighbors were called in to see me pass out of this troublesome world,
as it was thought by all outward appearance; I having a little recovered,
it livingly rose in me, "`You must not go hence yet,
you have not wholly finished the work of your day.`"
It was the word to me, and I believed it;
and thus far the Lord my God has made it good and fulfilled it to me,
who never breaks covenant with his people,
nor alters the word that is gone out of his mouth.

Yes, thus far the Lord has been pleased to raise me up again, though but weak still,
so that I can sit-in a meeting, and bear testimony to his name, and return the praise,
honor and glory of all unto him who lives forever.
Friends, in condescension to my weakness, keep the meeting in its course at my house,
both for worship, and the men's Monthly Meeting also,
which is cause of great refreshment and comfort to me.
The gout, which bears hard upon me often, has left such a cold numbness in my feet,
that I can go but little and lamely; and there is such a weakness and pain in my joints,
that when I stand I shake like a leaf; all my fingers are so crippled,
I can write but little, and sometimes none;
howbeit I was willing once at least to give you some hints,
how it has been and is with me.
Yet, notwithstanding all my infirmities, I can tell you in so many words,
though I undergo pain and weakness without, I have peace, comfort, and strength within,
and that makes amends for all my needs.
So I shall conclude in love; and do remain

Your friend and brother, in the truth that is living and precious.

[.signed-section-signature]
John Banks

[.signed-section-context-close]
Street, in Somersetshire, the 29th of the Seventh month, 1708

--

But though he was somewhat recovered, yet not to go far abroad; and not long after,
his distemper and weakness returning, he was again reduced to his bed.
I visited him in the fifth month, 1709, being the last time I saw him;
and found him as I did two years before,
in a living freshness and sense of the Lord's love and mercy to him,
and he discoursed very cheerfully of many things.
He got up while I was there, but could hardly go without help,
and continued weak for the most part of his time after.

The 5th of the third month, 1710, after giving account of his weakness, he wrote,
"`Howbeit all is well, I live to God through it all,
and that as a full cup supplies all my needs,
and sweetens and makes my afflictions easier to be borne; glory, honor,
and everlasting praises unto him who lives forever!`"
About two months before he died,
he was raised beyond expectation in a more than ordinary manner,
so as to travel to some neighboring meetings; which was to admiration,
considering his weakness.
At a Monthly Meeting at Somerton, the 6th of the sixth month, which was very large,
he stood about an hour and a half,
when it could hardly have been expected he could have sat so long in a meeting;
and bore a sound and faithful testimony to truth, with such presence of mind,
and distinction of doctrine, that it was admirable to those who knew his weak condition,
which is not mentioned to exalt man but the power of God;
and gave demonstration that his memory was strong, his understanding quick,
and judgment sound in things spiritual,
which was comfortable and refreshing to the meeting.
He earnestly pressed Friends to a holy zeal for God,
that they might be faithful in the small appearances of truth;
encouraging such as were weak, and putting Friends in mind to prize the present liberty,
for it had been a summer season, and that a winter might follow.
After the meeting he was so very weak,
that it was a task for two men to get him to his lodging.
He was very cheerful,
signifying his great satisfaction in being so capable of enjoying his friends' company,
by being so free from pain; and had an evening meeting the same day,
with Friends and many others in the town.
Next day he went to Long Sutton, to visit Friends, and the following day to Knole;
then to Puddimore, and the day after to their Monthly Meeting,
and had a very large testimony to Friends.

Next day he went to Samuel Bownas's at Lymington; there to Sock,
and to a meeting at Yeovil, which was very large, many Friends being there.
He was very weak, but his senses were lively and quick,
and he had a good discerning of the state of the meeting, and several particulars in it;
and was well accepted by Friends.
This was the extent of his journey,
after which he returned home the 15th of the same month, having been out about ten days.
Many Friends thought he would not have been able to undertake such a journey,
but he could not be satisfied in his mind without it,
although it was thought it much weakened him.

About two weeks after, on the 2nd of the seventh month, as he was walking in his orchard,
he was struck with a pain in his back, so that he was scarcely able to go in;
which proved very trying to him for several days before his death.
Yet he often said, that notwithstanding all his pain,
his soul did praise and magnify the Lord for his goodness towards him,
though his pain was so great sometimes, that he thought it sharper than death.
He expressed his belief that the Lord had provided a place for him in heaven;
and how well it would be if the Lord would be pleased to remove him.
Many Friends and others came to visit him while he lay sick;
and oftentimes he had a large testimony to them, by way of exhortation, counsel,
and advice On the 22nd of the seventh month, several Friends being present;
after a time of waiting in silence upon the Lord, he said to this effect:

"`Dear Friends, I counsel you in the love and fear of God to keep to your meetings,
for the worship and service of God, both first-days and week-days;
and also Monthly and Quarterly Meetings, which were set up by the power of God,
to keep things in good order amongst us.--Friends of Glastonbury and Street,
my love to you has been so great,
that I have ventured my life in riding through deep waters to come to visit you,
when I have had a concern from God upon my mind; so that you can say,
I have been a good example to you in keeping meetings, as well as in other things.
Although I am weak in body, and do not know whether I may live much longer or no,
I am however strong in the Lord and in the power of his might,
and have nothing to do but to die; for I am rich in faith towards God,
and my cup is full of the love of God.
Whether I live or die, it will be well with my soul; for blessed be the Lord!
I can say with the wise and holy apostle Paul,
that I have fought a good fight and kept the faith,
and henceforth there is laid up for me a crown of eternal life:
and did the apostle say for himself only; no, he was wiser than so,
but for all them that love the blessed appearance of the Lord Jesus Christ.`"

Some Friends of Somerton taking their leave of him, he said,
"`Give my dear love to Friends, and tell them that my soul is alive unto God.`"
Amongst them there was a young man lately convinced of the blessed truth,
to whom he said, "`The Lord be with you;
and I desire you in his love to give up in obedience to
the workings of the Spirit of God in your heart,
and then he will do great and glorious things for you; and do not stumble at the cross,
for the more you look at it and put it off, the harder it will be for you to take up.`"
A Friend taking him by the hand, he said, "`My dear love is to you,
and all that are faithful to God.`"
Another took him by the hand and bid him farewell; he answered,
"`I do fare well in the Lord; my love is to you and all the faithful in Christ;`" adding,
"`Joseph is yet alive, and that is enough.`"

He earnestly desired Friends to keep in the unity of the Spirit,
which is the bond of perfect peace;
with a great deal more good advice and counsel to Friends,
it being attended with Divine power; which tendered the hearts of many of those present,
and caused tears to run down their eyes.
The 24th, Thomas Freeman went to see him, and asked how it was with him?
he answered, "`Very sick, and full of pain, but the Lord helps me,
else I should cry out aloud; truth helps me, and ever has since I believed in it.`"
A few days before his death, he said to some who were with him,
that he could say as the woman of Samaria did,
that he had met with one who told him all that ever he did;
and that He was one who would not sew pillows to all arm-holes,
nor daub with untempered mortar, nor cry as priests and some other professors do, peace,
peace, when there is sudden destruction.
Some few hours before he died, he said to those who were with him,
"`Well is it to have nothing to do but die.`"
Another time he said, "`It is well with me, and I am assured it will be well,
and I have nothing to do but to die, and shall end in the truth as I began.`"

He was very sensible to the last, and after all his violent pains,
had a very easy passage; and died in peace, the 6th of the eighth month, 1710,
aged seventy-three years and two months,
and was buried the 12th of the same in Friends' burying ground at Street, where he died.
His body was accompanied to the grave by many Friends from several parts,
and several living testimonies were borne to the truth and power of God,
that raised him up and preserved him to the end,
to the honor of God and the praise of his great name;
and in commemoration of the deceased,
who is undoubtedly entered into that rest which is prepared for the people of God.
The Lord fit us and prepare us all more and more for the entering thereinto;
through the alone merits and mediation of his dear Son, our Lord and Savior Jesus Christ.
Amen!
The blessed end of the righteous who die in the Lord,
and such as are faithful to the truth in their day,
so different from that of loose and careless professors,
should be an encouragement to all who have any desires after the Lord,
to embrace the truth and be faithful to it, that their latter end may be like his;
for whose sakes and the truth's, I have faithfully collected the foregoing account,
from such as were eye and ear witnesses of it.

[.signed-section-signature]
J+++.+++ W.
