== The Journal of John Banks.

[.chapter-subtitle--blurb]
Showing the manner of my education and convincement,
how I came to receive the knowledge of God, and of his blessed truth;
the travail of my soul under judgment; how I came through the same,
to obtain mercy at the Lord`'s hand, for sin and transgression: and how in his time,
I was called forth into the ministry;
of my travels and exercises in that work and service;
together with my imprisonments and sufferings: also an abstract of letters to my wife,
children, and servants, and my wife`'s to me.

=== Of My Education.

I came of honest parents--my father`'s name was William, and my mother`'s name Emme.
I was their only child, born in Sunderland, in the parish of Issell,
in the county of Curnberland; and my father having no real estate of his own,
took land to farm; and by trade was a fell-monger^
footnote:[One who deals in hides or skins.]
and glover.

In some years after, he removed within the compass of Pardshaw meeting,
where both my parents received the truth some time after me, and lived and died in it,
according to their measures.
To this meeting I belonged above forty years.

Though my parents had not much of this world`'s riches,
yet according to their ability and the manner of the country, they brought me up well,
and in good order;
and were careful to restrain me from such evils
as children and youth are apt to run into;
and especially my dear mother, she being a zealous woman.
Their care therein for my good, had a good effect on me; and so will it have,
we may hope, on all who perform their duty as they ought to their children; if not,
they will, it is feared, be found guilty in the day of account.

I was put to school when I was seven years of age and kept there until I was fourteen;
in which time I learned both English and Latin, and could write well.
When I was fourteen years of age,
my father put me to teach school one year at Dissington;
and after that at Mosser Chapel near Pardshaw,
where I read the Scriptures to people who came there on the first-day of the week,
and the homily, as it is called, and also sung psalms and prayed.
I had no liking to the practice; but my father, with other people, persuaded me to it.

For this service my wages from the people was to be twelve pence a year from every house,
of those who came there to hear me, and a fleece of wool, and my table free,
besides twelve pence a quarter for every scholar I had, being twenty-four.
This chapel is called a chapel of ease, the parish steeple-house being some miles off.
Amongst the rest of the people who were indifferent where they went for worship,
came one John Fletcher, a great scholar, but a drunken man;
and he called me aside one day, and said, "`I read very well for a youth;
but I did not pray in form,
as others used to do,`" and that he would teach me how to pray;
and send it me in a letter, which he did.

When it came, I went out of the chapel and read it; and when I had done,
I was convinced of the evil thereof, by the light of the Lord Jesus,
which immediately opened to me the words of the apostle
Paul concerning the Gospel he had to preach,
that he had it not from man, neither was he taught it,
but by the revelation of Jesus Christ.
In answer to which it rose in me: "`But thou hast this prayer from man,
and art taught it by man, and he one of the worst of many.`"
So the dread of the Lord fell upon me, with which I was struck to my very heart,
and I said in myself, I shall never pray on this wise.
It opened in me, Go to the meeting of the people in scorn called Quakers,
for they are the people of God: and so I did the next first-day after,
which was at Pardshaw.

This being before the end of the year,
when I was to receive wages of the people for such service as I did,
I could take none of them, being convinced of the evil thereof;
nor did I ever read any more at the chapel.

When about sixteen years of age, in the tenth month, 1654,
it pleased the Lord to reach to my heart and conscience, by his pure living Spirit,
in the blessed appearance thereof in and through Jesus Christ;
whereby I received the knowledge of God, and the way of his blessed truth,
by myself alone in the field, before I ever heard any one called a Quaker preach;
and before I was at any of their meetings.
But the first-day that I went to one, which was at Pardshaw, as aforesaid,
the Lord`'s power so seized upon me in the meeting,
that I was made to cry out in the bitterness of my soul,
in a true sight and sense of my sins, which appeared exceeding sinful: and the same day,
as I was going to an evening meeting of God`'s people, scornfully called Quakers,
by the way,
I was smitten to the ground with the weight of God`'s
judgment for sin and iniquity which fell heavy upon me,
and I was taken up by two Friends.
Oh! the godly sorrow that took hold of me that night in the meeting;
so that I thought in myself every one`'s condition was better than mine.
A Friend, who was touched with a sense of my condition and greatly pitied me,
was made willing to read a paper in the meeting, which was so suitable to my condition,
that it helped me a little, and gave some ease to my spirit.
I was now very much bowed down and perplexed, my sins being set in order before me;
and the time I had spent in wildness and wantonness, out of the fear of God, in vanity,
sport, and pastime, came into my view and remembrance.
The book of my conscience was opened, for I was by nature wild and wanton;
and though there were good desires stirring in me many times,
and something that judged me and reproved me,
and often strove with me to restrain me from evil, yet not being sensible what it was,
I had got over it.

I was like those who make merry over the witness of God,
even the witness and testimony of his Holy Spirit, in and through Jesus Christ his Son,
made known in God`'s great love to the sons and daughters of men.
This was that, whereby the Lord many times strove with me,
until at last he prevailed upon me.
So that I may say, as a true witness for God,
and the sufficiency of his power and quickening spirit,
I did not only come to be convinced by the living appearance of the Lord Jesus,
of the vanity, sin, and wickedness which the world lies in,
and that I was partaker thereof; but by taking heed thereto,
through watchfulness and fear, I came to be sensible of the work thereof in my heart,
in order to subdue and bring down the wild nature in me,
and to wash and cleanse me from sin and corruption,
that I might be changed and converted.
But before I came to witness this work effected,
oh the days and nights of godly sorrow and spiritual
pain I travelled through for some years!
The exercise I was under bore so hard, both upon my body and mind,
that I left off the practice of teaching school, which, although good and lawful,
yet was not agreeable to me in my condition then.
I put myself to learn my father`'s trade, with something of husbandry,
which I followed with diligence; and lived with my parents, who some time after,
came to receive the truth, which was great rejoicing to my soul.
As I travelled under the ministration of condemnation and judgment,
for sin and transgression, great was the warfare I had with the enemy of my soul, who,
through his subtlety, sought to betray me from the simplicity of the truth,
and to persuade me to despair, as though there was no mercy for me;
yet in some small measure, I knew the Lord had showed mercy to me,
which he mixed with judgment, for my sins past.
But the experience I had gained in the travail of my soul,
and the faith begotten of God in my heart,
strengthened me to withstand the enemy and his subtle reasonings.

I overcame the wicked one, through a diligent waiting in the light,
and keeping close to the power of God, waiting upon him in silence among his people,
in which exercise my soul delighted.

Oh! the comfort, and divine consolation we were made partakers of in those days;
and in the inward sense, and feeling of the Lord`'s power and presence with us,
we enjoyed one another, and were near and dear one unto another.
But it was through various trials and deep exercises, with fear and trembling,
that thus we were made partakers.
Blessed and happy are they who know what the truth has cost them,
and hold it in righteousness.

Waiting diligently in the light, and keeping close to the power of God,
which is therein received, I came to experience the work thereof in my heart,
in order to effect my freedom from bondage, which by degrees went on and prospered in me,
and so I gained ground more and more against the enemy of my soul,
through faith in the power of God; without which no victory is obtained.

My prosperity in the truth I always found was by being faithful to the Lord,
in what he manifested, though but in small things; unfaithfulness in which,
is the cause of loss and hurt to many in their growth in the truth.

After I had passed through great tribulation,
weeping and mourning in woods and solitary places alone, where I often desired to be,
I came to more settlement in my spirit, and peace began to spring in my soul;
where trouble and sorrow had been.
Then at times, I would be ready to think,
that I should not again meet with such combats and besetments by the enemy of my soul,
as I had passed through.
But the more I grew in experience of the dealings of the Lord with me;
so much the more did the enemy transform himself,
and as he could not prevail by his former presentations, so in his subtlety,
he would invent new ones.
Thus I came clearly to see that it was not safe for me
to sit down satisfied with what I had passed through,
or the victory I had already obtained; but to travel on in faith and patience,
and watch diligently in the light of Jesus Christ,
where the true power is still received.
For notwithstanding the many deliverances, and strength, and victory, I had experienced,
the Lord, according to the greatness of his wisdom,
was pleased to make me sensible of my own weakness,
and that there was no strength to stand, nor place of safety for me to abide in,
but in his power, and under a sense thereof, I was humbled, bowed, and laid low.

Wherefore I took up a godly resolution in his fear,
"`I will rely upon the sufficiency of thy power, O Lord, for ever.`"
About six years after I had received the truth, through great exercise and godly sorrow,
I came to be settled in the power of God, and made weighty in my spirit thereby;
and had some openings from the Spirit of Truth, in silent waiting upon the Lord;
which tended to minister comfort and satisfaction to my soul,
in a renewed experience of the dealings of the Lord with me;
and the Lord opened my mouth with a testimony in the fresh spring of life,
that I was to give forth to his children and people.

Oh! then a great combat I had through reasoning, that I was but a child,
and others were more fit and able to speak, than I. But the Lord, by his power,
brought me into willingness, and with fear and trembling I spoke in our blessed meetings.

At one time, as I was sitting in silence waiting upon the Lord, in a meeting of Friends,
upon Pardshaw Crag, a weighty exercise fell upon my spirit, and it opened in me,
that I must go to the steeple-house at Cockermouth, which was hard for me to give up to.
But the Lord by his power, made me shake and tremble, and by it I was made willing to go;
but when I had given up to go, I would have known what I was to do there,
which was the cause that for a little time, I was shut up within myself,
and was in some measure darkened; so that I cried unto the Lord,
that if it was his will I should go, I would give up.
And being made sensible it was, I went in faith and quietness of mind and spirit.
As I was going, it appeared to me, as if the priest had been before me;
and it opened in me to say to him, "`If thou be a minister of Christ,
stand to prove thy practice;
and if it be the same as the apostles and ministers of Christ, in doctrine and practice,
I will own thee; but if not, I am sent of God this day, to testify against thee.`"
And so soon as I entered the place where the hireling priest, George Larcum,
was preaching, he cried out, "`There is one come into the church like a mad-man,
with his hat on his head.
Churchwardens, put him out!`"
For he could not preach after I came into the steeple-house.
So they put me forth, as he bid them.
This was in Cromwell`'s time,
and not long after the government was changed and he himself turned out of the place.
Some time after I was put forth, I was moved of the Lord to go in again,
and had strength given me to stay until the priest had done;
but his preaching was burdensome and confused.
Then, with the words aforesaid, I opened my mouth, in the fear of God,
which made the hireling go out with all the haste he could,
at a contrary door than he used to do; and the people were in a great uproar,
some to beat me, and some to save me from being beat.

When they had haled me out of the house, I was enabled by the power of God,
to declare the truth amongst the people and to manifest the deceiver they followed:
and having obeyed the requirings of the Lord,
I came away in sweet peace and spiritual comfort in my heart.

At a certain time being at a meeting of Friends upon the Howhill, near Coldbecke,
in Cumberland, George Fletcher of Hutton Hall, a justice of the peace, so called,
came into the meeting in a rude manner, riding among Friends,
who were sitting upon the ground, and trod with his horses feet upon a woman`'s gown,
I was moved of the Lord, to kneel down to prayer, at the head of his horse;
and as a wicked persecutor of God`'s people,
he struck me bitterly over my head and face with his horse-whip.
When he saw he could not move me, he called his man, being near by, to take me away;
who came in great fury, and took me by the hair of my head, and drew me down the hill;
but I got upon my feet, and said to his master,
"`Dost thou pretend to be a justice of peace, and breakest the peace; and disturbs,
persecutes, and abuses God`'s peaceable people, and sets on thy servant so to do?`"
He said, we should know he was a justice of peace before he had done with us;
could no place serve us to meet in, but under his nose?
Yet it was at a great distance from his dwelling, upon the common.
He committed me and three more, to the common jail at Carlisle;
it being at the time when that act was in force,
which imposed a penalty of five pounds for the first offence; ten pounds for the second;
and for the third, banishment.
By his warrant he caused one cow and a horse, worth six pounds ten shillings,
to be distrained of my father, with whom I lived, for my fine of five pounds;
it being the first offence (so adjudged by him,) and kept me in prison some weeks too.
George Martin, a wicked hard hearted man, being jailer, put us in the common jail,
for several days and nights, without either bread or water;
because we could not satisfy his covetous desire,
by giving him eight pence a meal for our meat; so he threatened,
when he put us in the common jail,
that he would see how long we could live there without meat;
and suffered none that he could hinder, neither would he allow any of our friends,
to bring us any bedding, not so much as a little straw.
We had no place to lie on, but the prison window, upon the cold stones,
the wall being thick, there was room for one at a time;
and when he saw he could not prevail, notwithstanding his cruelty,
he removed us from the common jail, into a room in his own house,
where he had several Friends prisoners, for non-payment of tithes,
at the suit of the said George Fletcher.

The jailer was often cruel, wicked and abusive in his behaviour to Friends;
but in a few years he was rewarded according to his doings;
for he himself was cast into prison for debt, and so ended his days.

When the quarter sessions began, which was in about two weeks after our commitment,
at Carlisle, we were called and examined by one Philip Musgrove, of the said city,
called a justice, an old persecutor, who, under a great pretence of love to us,
said that if we would but conform, and come to the church,
they would show us all the favour they could;
and when any one of us would have answered his questions or proposals, he would say,
we must be silent, except we would conform, for we might not preach there,
but would tauntingly say, "`When you are banished beyond the seas,
then you may preach there.`"
One of us replied, "`We were not afraid to be banished beyond the seas;
for we did believe, and had good cause so to do, that the Lord our God,
whom we worship and serve,
and who by his great power had preserved us all along until now, on this side the sea,
would also preserve us on the other side,
as we stood faithful in our testimony for him.`"

We were set at liberty that sessions; goods being taken for all our fines;
but the sheriff for the county, Willfrid Lawson, of Issel Hall, being there,
said to the jailer, "`If they will not pay fees, put them into the common jail again,
and keep them there until they rot.`"
So the jailer put us into the common jail again, because we could not pay him fees;
where was a Bedlam-man, and four with him for theft and two notorious thieves,
called Redhead and Wadelad; two moss troopers, for stealing cattle; and a woman,
for murdering her child.
Several of the relations and acquaintances of these, were suffered to come to see them,
after the sessions was over, who gave them so much drink,
that most of them were basely drunk; and the prison being a very close nasty place,
they did so abuse themselves and us with their filthiness,
that it was enough almost to stifle some of us.
On the morrow, we let the jailer know how we were abused,
whereupon he bid the turnkey bring us to the room where we were before;
saying he scorned to keep us there, for we were honest men, setting our religion aside.
One of us answered, "`If the tree be good, the fruit cannot be evil.`"
So in a little time after we had been in his house, he gave us our liberty,
without paying fees.
This was in the fifth month, 1663.

Here follow some letters I wrote whilst I was a prisoner at Carlisle.

[.embedded-content-document.letter]
--

[.salutation]
Dear Father and Mother,

My duty is hereby remembered to you; and my dear and tender love,
both naturally and spiritually, doth hereby reach unto you both:
and as you are faithful according to what the Lord hath made known unto you,
by his pure light, the Lord will preserve you.

Dear parents, as it is thus ordered, that I am called to suffer, for no other cause,
than worshipping God among his people, I desire you to be content,
and do not murmur or complain: but live in love, quietness,
and all unity with each other, that the blessing of the Lord may be upon you,
and prosper what you go about; for they that truly fear the Lord,
shall want no good thing.
Let your faith stand here, dear hearts, and be patient, and content in your minds,
and not too much concerned for me and my welfare; for I am persuaded,
feeling the evidence of Truth in my heart, that I suffer not for evil-doing,
but for obeying the requirings of the Lord: yea,
for worshipping and serving him in spirit and in truth; so that it is,
and shall be well with me, as I keep faithful unto the end.
Be not at all dejected, or cast down in mind concerning me: but rather rejoice with me,
that the Lord hath not only counted us worthy to believe in his name,
but also to suffer for the same.

From the house of our friend, Mungo Bewly, one of the prisoners,
(being five) where the constables are ready to take us away to prison,
in the city of Carlisle in Cumberland, the 8th day of the Fifth month, 1663.

[.signed-section-closing]
Your obedient son,

[.signed-section-signature]
John Banks.

--

My second letter to my parents; with a few words to Friends.

[.embedded-content-document.letter]
--

[.salutation]
Dear Father and Mother,

My dear and tender love, as a dutiful and obedient child,
I do most dearly and tenderly remember to you;
and if I should not write one word more to you, as to that,
I do not question but that you believe and are sensible
that my love is large and dear to you both,
for your good in all respects; and this I can say of a truth,
that all I desire of you is, that you would be patient and truly content;
that you may come to say in truth, the will of the Lord be done,
both concerning you and me.
So, dear hearts, keep the faith, and hold fast the word of his patience;
and in that suffer, as one with me,
though you be at liberty and give up freely unto the Lord, for what we have is his;
and if he bless, who can curse?
Blessed, praised, and magnified be his holy name for evermore.

[.signed-section-closing]
Your dutiful son,

[.signed-section-signature]
John Banks.

[.salutation]
Dear Friends,

in the precious Truth, to whom my love in the same is beyond expressions;
we are with our Friends at present who are in prison for tithes;
and are like to be retained after the sessions for fees, if we get our liberty then,
all our fines being levied.

But be it as the Lord sees good, we can truly say he is near to support us;
for his presence is even in the midst of us,
and we are at true peace with him in our suffering, and are bound together with,
and in the bond of love, peace, and unity.
This, indeed, my heart rejoices to tell you,
and I do believe you will be glad and rejoice with me, who am,
and do remain your brother, and fellow-sufferer,
who never knew the worth of a prison so much before,
to my sweet peace and inward consolation, though I have yet tasted but a little thereof.

[.signed-section-signature]
J+++.+++ B.

[.signed-section-context-close]
From the prison-house in Carlisle, the 18th of the Fifth month, 1663.

--

Some time after, I had drawings in my spirit to visit the neighbouring counties,
as Westmoreland, Lancashire, and some part of Yorkshire,
several times before the Lord sent me forth into other countries;
so when I was clear of those counties, I returned home to my parents,
and lived with them about a year more.

Upon the 26th day of the sixth month, 1664, I took a Friend, by name Ann Littledale,
to wife, in a public meeting of God`'s people, in scorn called Quakers,
in a Friend`'s house in Pardshaw town, before many witnesses,
as having freedom and liberty in the Lord so to do;
which as a blessing and mercy I received from his hand,
wherefore I am bound in duty to give him the praise,
and to return him the honour and glory, who lives for ever.

About four years after I was married,
the Lord called me forth to travel in the work of the ministry,
and I was made willing to leave all, in answer to his requirings,
to go into the south and west of England.
Yea, I was made willing to leave my dear wife and sweet child,
though near and dear unto me, and went forth in the power and Spirit of the Lord Jesus.
Our friend John Wilkinson and I travelled together in the Lord`'
s work and service (this was Cumberland John Wilkinson).
We took our journey in the second month, 1668, and travelled into Yorkshire,
and visited many meetings in divers places,
where we had good service for the Lord and his truth.

A letter to my wife, written upon my journey towards the west and south of England.

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

Thou art dear unto me, together with our little one,
in the nearness of that pure spirit by which the Lord hath joined us together,
as one heart and mind; from a sense of whose pure love felt to abound in my heart,
I dearly salute thee, and do hereby let thee know I am very well at present,
both in body and spirit,
for which I can do no less than bless and praise the
holy name and great power of the Lord for ever,
who hath thus far preserved me in my journey, in true peace and comfort;
whereby it is confirmed unto me that I am in my place,
and that the work and service I have to perform is for the Lord,
and the furtherance of his blessed truth.
Blessed be that day in which I was made sensible of the same,
that the Lord should count me worthy to do any service for him.

Wherefore, my dear, be thou encouraged to trust in the Lord more and more,
and put thy confidence in him in all things,
who is able to do whatsoever he pleaseth and seemeth good in his sight;
for he can make all things work together for good, to them who truly love and fear him,
and are concerned for the prosperity of his blessed truth;
though we must expect to meet with various exercises in
the way to come to be made partakers thereof.

Remember my love and due respect to my parents,
and let them know that I am well every way; and to Friends without respect of persons,
as they inquire of me.

The desire of many people hereaway, is after the Lord; and they flock to our meetings,
like doves to the windows, when they hear of any that have the way of truth to declare.
We have had a meeting every day this week, and shall have one tomorrow, if the Lord will.

Thy dear and loving husband, according to my measure of the truth received.

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
Written near Bradford, in Yorkshire, the 14th of the Third month, 1668.

--

From Yorkshire we travelled into Nottinghamshire, Leicestershire, and Warwickshire,
where we had many blessed meetings, and where I wrote the following letter to my wife.

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

Unto whom I am truly united; in the pure love and unity of the Spirit of Truth,
wherein the Lord hath made us truly one, do I dearly salute thee,
and let thee know that I am well in all respects;
blessed and praised be the Lord our God for evermore.

In my heart I reach forth a hand unto thee; give me thine, and let us go along together,
in the work and service of the Lord;
that so we may be a strength and encouragement to each other, to go on in faithfulness,
and finish a faithful testimony for the Lord, in what he requires of us,
in doing or suffering, and giving up whatever we have or enjoy in this world.

My dear heart, give all up freely, as to the Lord our God,
to be ordered and disposed of by him, who is wise and wonderful in counsel,
and to be admired of all them who truly love and fear him,
and wait for his glorious appearance of light and life.
Take no thought nor care for me, but in the Lord,
who hath a care and tender regard unto us, and all his people,
as our hearts are kept near to him.

We came this day to see our dear friend William Dewsbury,
and intend to travel through the county, in visiting of the seed of God, towards Bristol,
and then as the Lord may order us.

So with the remembrance of my duty to my parents, and my love to Friends,
as though named, I remain thy dear and loving husband,

[.signed-section-signature]
J+++.+++ B.

[.signed-section-context-close]
Warwick, the 4th of the Fourth month, 1668.

--

From Warwickshire we travelled into Gloucestershire, and so to Bristol,
where the Lord made our service acceptable to Friends and other people;
and we travelled through Somersetshire,
from whence I wrote the following letter to my wife.

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

In that love which still endureth, and increaseth in my heart to thee, do I feel thee;
and the further I am separated from thee, the nearer thou art unto me,
even in that which length of time or distance of place shall never be able to wear out,
or bring to decay.
Feel the reach of my love in thy heart,
and be thou broken and tendered in the sense thereof,
even of the heart-breaking love of God: in which my heart abounds in love to thee;
with breathings to God, that we may be kept living to him,
through all our various exercises,
that so we may daily learn with the blessed and wise apostle,
in all conditions to be content; and that patience may have its perfect work in us;
for patience gains experience, and experience hope, that never makes ashamed,
but anchors the soul both sure and stedfast unto God.

My dear, give me freely up to the will and disposing of Him,
into whose hand I am freely given up, both soul and body.
Keep near the Lord at all times, and pray for me in spirit,
that I may be preserved faithful to the Lord, to finish a good testimony for him;
and that I may not return to thee until his time,
that so we may enjoy each other in the Lord,
and be made partakers of his blessings upon us and ours, and all we take in hand,
without which, it will not prosper; for it is in vain to strive against the Lord,
before whom all nations are but as the drop of a bucket: if he bless, none can curse:
blessed and praised be his holy name for evermore.
Amen.

By this, thou and the rest of my family and friends, may understand,
that I am pretty well in health at present, through the goodness of the Lord,
though I have been under weakness of body, at times, since I wrote my last from Warwick;
but the Lord by his power strengthens me many times, far beyond what can be expected,
considering my own weakness.
I have faith to believe, and that upon good ground,
that whatsoever the Lord is pleased to exercise me in, or call me to,
he will give me strength to perform and go through,
and nothing shall be able to hinder it.
I am truly content, whatsoever the Lord may suffer to come upon me,
because hitherto he hath kept and preserved me, to his praise and glory,
and to my sweet peace and comfort; endless praises to Him who lives for ever!

Remember my dear and tender love, as also my duty and tender regard, to my parents,
for they are very near and dear to me; with my love also to Friends, neighbours,
and relations, as if named.
My companion and fellow-labourer in the Gospel
desires to have his love remembered to thee.

And so I bid thee farewell.
The Lord keep and preserve thee, with all his people, faithful in this trying day,
which possibly may have the effect to try the faith of many.

[.signed-section-signature]
J+++.+++ B.

[.signed-section-context-close]
Puddimoore-Milton, in Somersetshire, the 28th of the Fourth month, 1668.

[.postscript]
POSTSCRIPT.

The truth of our God prospers and gaineth a good report in these parts,
and many other places where we have travelled; and many are coming in to partake thereof.
For people in many places are weary of the hireling priests,
and dead formal worship of the world, and their assemblies grow thin.
The Lord, by the all-sufficiency of his power, hath made our service effectual unto many,
both Friends and other people,
and very full and peaceable meetings we have had in several counties and shires;
wherefore we cannot but return the praise, honour, and glory unto Him,
whose the work and power are; and count nothing too hard for us,
so that we may bear a faithful testimony for Him, to the good of souls;
that he over all may be glorified;
and that we may feel true peace with Him in the end for our reward.

[.signed-section-signature]
J+++.+++ B.

--

My wife`'s letter to me.

[.embedded-content-document.letter]
--

[.salutation]
Dear Husband,

After long expectation to hear from thee, I have, before the writing hereof,
received two letters, whereby I was much satisfied and refreshed;
but in thy last from Somersetshire, I observe,
that thou hast been under weakness of body for some time.
At the first hearing of which I was sad in my spirit;
but considering the greatness and sufficiency of the Lord`'s love and power,
in whom is our strength, I rest satisfied,
hoping that all things will work for good in the end.
Dear husband, I have been and am brought very low in body, by a strong fever,
but am well in mind, blessed be the Lord therefor.
It was one month last fifth-day, since the sickness took me,
and in about two weeks time I received some strength, but became worse again,
and am very weak.
I greatly desire this may come safe to thy hand,
that thou mayest understand how it is with me; and that, in the wisdom of God,
thou mayest consider what may tend most for the glory of God in this matter,
I can truly say, in a sense of the Lord`'s love and truth, according to my measure,
whether ever I see thy face again or no,
I desire nothing more than that the will of the Lord may be done in all things,
whether in life or death;
to whose care and fatherly protection I commit and commend thee, and dearly salute thee,
with love to thy companion, J. W., and bid thee farewell;
and am thy dear and loving wife,

[.signed-section-signature]
Ann Banks

[.signed-section-context-close]
Whinfell-Hall, in Cumberland, the 19th of the Fifth month, 1668.

--

From hence we travelled westward, through part of Devonshire, and into Dorsetshire,
Hampshire, Wiltshire, and so up to London.
The Lord was with us; and Friends were greatly refreshed and comforted with us,
and we with them.

Great openness and tenderness there was in those days among Friends,
and many other people where we came, and the witness of God was soon reached.
We had very large and full meetings in most places where we travelled,
and many were convinced and are yet alive, standing witnesses for God.
At London, I wrote to my wife as follows:

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

Thine I have received, whereby I understand the great weakness thou hast been in,
which hath been a near trial and great exercise to me.
But when I consider the large love of God to thee,
in preserving thee in faith to believe in him,
and patience and true contentedness to give up unto him, under thy great weakness,
it hath eased my burden and lessened my exercise.

Wait daily to feel the Lord to be thy strength, in the time of thy greatest weakness;
rely wholly upon him, trust in him, believe in him, and he will never fail thee.
He can be more to thee than a husband, and to thy child than her father.
Mayest thou know thy portion increased in Him, and thy inheritance to be enlarged,
that thou mayest dwell in the borders of his sanctuary,
in the sight of his glorious Son for evermore; and mayest feel thy faith to increase,
and thy patience and contentedness to remain in him, by the sufficiency of whose power,
safety and preservation is known.
As we abide in Him, whether we live or die we are the Lord`'s,
and it shall be well with us for evermore, world without end:
and no matter what we suffer or undergo in this life, if that be attained unto.

Remember my dear and tender love, and also my duty, to my parents;
for still I find myself bound to be tender over them, and to do what in me lies for them,
under the consideration of what they have done for me.
With the salutation of my true love to thyself, in the remembrance of our little one,
and my love to Friends, and relations and neighbours, I remain thy loving husband,

[.signed-section-signature]
J+++.+++ B.

[.salutation]
And now Peter Fearon, my apprentice:

Mark, and take good notice what I say to thee;
lay it to heart, and consider well now in my absence.
My true and unfeigned love is to thee, and I desire thy prosperity and welfare,
in all which is good, both inwardly and outwardly; but first of all, and chiefly,
in that which appertains to the salvation of thy soul; the way whereof, the Lord,
in his love, hath in some measure made manifest unto thee.
Therefore be watchful to walk in it; that is to say,
take heed to the light of Christ Jesus in thee, the measure of the Spirit of Truth,
which will lead thee into all truth, and out of all deceit,
as thou dost obey and follow the same.
Whatever this pure light in thee maketh manifest to be evil, and reproveth thee for,
depart thou from it; if it be that which no eye can see, nor no one knows of,
yet thou must forsake it; wait and watch daily against it,
in the light that makes it manifest,
and thou wilt receive power to cast it off and depart from it.
The light, which is Christ Jesus, the way, the truth, and the life,
teacheth to be sober and lowly-minded; our words to be few and savoury;
gentle and easy to be entreated; not to be high-minded,
but fear the living God continually.
This keeps the heart clean; and as it is abode in, low and humble in self-denial,
and willing to take up and bear the daily cross; and as this takes place in the heart,
such thereby come to depart from iniquity.
All things that are reproved are made manifest by the light,
and whatsoever makes manifest, is light;
and that which the light makes manifest to be sin and evil, in word or action,
thou must forsake and deny thyself in; for this is the will and mind of the Lord,
by his blessed Spirit; and he that knows his master`'s will, and doth it not,
according to the Scriptures of truth, must be beaten with many stripes.

As to things appertaining to thy work and service, be patient and content,
and go quietly about thy business in the fear of God; and say not in thyself,
I will think thou hast not done enough, for it is far from me so to think;
only my desire is, if thou do ever so little, be careful to do it well.
But, above all things, be truly willing and obedient unto thy mistress,
for whatsoever thou dost to her, I take it as done to myself:
and mind to carry thyself in love, and be a good example in my family,
that so you may all live in love and unity together; in which the Lord preserve you all.

[.signed-section-closing]
Thy loving master,

[.signed-section-signature]
J+++.+++ B.

[.signed-section-context-close]
From Whitechapel in London, the 3rd day of the Sixth month, 1668.

--

We travelled in the work and service of the Lord from London,
through those counties before named, again to Bristol,
where we were greatly comforted in the Lord, in truth`'s prosperity,
with other of the brethren we met with there;
where I wrote the following letter to my wife.

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

I received thine at Bristol,
which was cause of great refreshment and satisfaction unto me,
because of thy recovery from thy sickness, which I should be glad to know doth continue.

I cannot give thee a certain account of my return home at present.
The day this letter was written in Bristol, we set our faces towards our own country,
having been to the end of our journey at this time, for anything we know;
but how long we may be in coming home I know not,
for great is the work which the Lord hath to do, and is doing,
and the labourers are not many, considering the greatness thereof.
Blessed are they that are faithful therein, though ever so little;
for if they continue unto the end, they shall not lose their reward.
Greatly doth the truth of our God prosper and increase,
to the encouragement of the faithful,
and many are they who have a good desire to know the way thereof,
in most places wherever we have come.
Meetings are very large, peaceable, and quiet, almost everywhere,
and a great calm there now is; what will be the end thereof, the Lord knoweth.
We have had a sweet and precious time all along in our journey,
blessed be the Lord for the same,
who hath been pleased to bless our weak endeavours for the good of his people,
and our great comfort and satisfaction in him.

[.signed-section-closing]
I am thy dear and loving husband,

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
Bristol, the Seventh month, 1668.

--

We travelled through the nation homeward,
and at the end of six months from the time of our going forth,
we got well there with sheaves in our bosoms,
for our faithfulness in our Lord and Master`'s work,
which we had freely and faithfully performed through the ability of his power;
and we were very careful to give way one to the other in our testimony,
that so we might be preserved in unity and fellowship together,
as we were to the end of our journey: everlasting praises, honour,
and glory be given unto the Lord alone, for he is eternally worthy!

The length of this journey was twelve hundred and sixty-eight miles.

I do not intend nor desire to make a great volume,
or to give a full account of my journies in England, Scotland, and Ireland;
but in as much brevity as I can, notice what may be most material.

I have travelled and gone over sea between England, Scotland, and Ireland, twelve times,
and often not without great difficulty and danger of life by many tempestuous storms.
Yet I was never at any time above two nights together at sea, insomuch,
that when I have taken shipping at Whitehaven,
the seamen would be very desirous who should have me in their vessel; saying,
I was the happiest man that ever they carried over sea,
for they always got well along when they had me, though sometimes through great tempests.
That God over all may have the praise of his own works,
and the faithful be encouraged to rely upon the sufficiency of his power for ever,
is the intent of my writing.

With reverence, humility, and godly fear,
I may say that my labours and travels in these nations,
in preaching the everlasting Gospel in the demonstration of the Spirit,
with which the Lord was pleased to attend me; though through many exercises,
both without and within; perils at sea, robbers by land, bad spirits and false brethren;
yet notwithstanding all these, I hope, I may say without boasting,
I have been made instrumental to turn many unto righteousness;
a considerable number of whom are yet alive to witness to the truth of what I say.
In my native county in Cumberland, and also in many places elsewhere,
it is well known to Friends, with what diligence I laboured among them,
in the work of the Gospel, early and late, far and near,
through much hardship to my body, in heat and cold; and yet,
through the strength and ability given me of God, I was preserved in and through all,
having faith therein.
And with all diligence, when I was at home, I laboured with my hands,
with honest endeavours and lawful employments, for the maintenance of my family.

About the beginning of the year 1670, was the first time I went for Ireland,
and our ancient friend John Tiffin, having drawings thither also,
we took shipping at Whitehaven, and landed at Carrickfergus, in the North of that nation,
for the North was most before us.
And after we had visited meetings thoroughly, and were well satisfied in our service,
we visited Friends along to Dublin, and thereabout;
and having had good and refreshing times with Friends in that city and elsewhere,
and being clear, we returned to our own country.

It was not long until the Lord required of me to go to Ireland again;
and in the third month, 1671, I was made willing to go,
in obedience to the requirings of the Lord, and his presence was with me.
My desire was to be at the Half-year`'s meeting at Dublin,
which began the fifth-day of the week.
I went to Whitehaven the third-day before, with intent to take shipping there;
and my dear wife, and several friends, went along with me;
but the wind that day was quite contrary,
so that my wife and friends would have persuaded me to go home again, being ten miles,
because the wind was not likely to serve.
But I told them I could not then;
I must rely upon him who had power to command the wind and seas, even the Lord alone.
They went home, and I went that evening to a vessel which was ready to go,
and told the owner I was willing to go with him to Dublin; and I desired some of his men,
if the wind was fair ere the morning, to call me at such a house.
They answered, "`Yes, with all their heart;
but asked if I thought the wind would serve so soon, that was now so contrary?`"
I said, it was possible with the Lord that it might: for I had faith in the thing,
according to what was revealed to me.

About the dawning of the day, being fourth-day morning, one came calling aloud to me,
to make haste and come soon, the wind was fair, and the ship nearly ready to sail.
We had a ready passage; so that according to my desire,
I got to the meeting aforesaid on fifth-day, within half an hour after it was set;
and a glorious heavenly meeting it was,
where many faithful brethren from all parts of the nation came;
and the Lord`'s power was over all, and several living testimonies given,
to show forth the greatness and sufficiency thereof;
wherefore we had cause of rejoicing in the prosperity of the Lord`'s work,
and our unity and brotherly fellowship one with another.

Next day, in the evening, as I was waiting upon the Lord,
a great weight came upon my spirit, under which exercise I patiently abode,
until it opened in me, that I was to go southward, to a place called Wicklow,
though I knew it not then, being twenty-four miles south from Dublin,
where no meeting of Friends before that time had been, that I could hear of,
and only one or two friendly people in it.
But before I went, I wrote the following letter to my wife:

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

That nearness of love I still feel in my heart towards thee,
is beyond what I can express;
yet I find an engagement upon me to show forth the same in some expressions at this time.
It is in my heart to say unto thee, my dear, be stedfast in thy mind,
and in the lowliness thereof watch and wait, to be preserved near to the Lord;
so wilt thou feel thy peace and unity to increase with him and his people,
and assuredly with me, thy husband: in whose work and service, which is weighty,
I am concerned; and the prosperity thereof is become my chiefest joy and delight;
and for which I am willing and in measure able, through the goodness of the Lord unto me,
to spend and be spent--may he have the praise, honour, and glory returned to him,
who is worthy for ever; whose the work is, and who is mighty by his own power,
for carrying on the same.

My dear one, my daily cry and secret breathings are to the Lord for thee,
that thou mayest be preserved in faithfulness to him, even to what thou knows of him,
made manifest by his pure light in thee, by which the enemy,
with all his cunning and subtlety, and reasoning which darkens, is discovered,
and the outgoings of the mind judged; and the power received by waiting in the light,
brings all things into good order, both within and without.

Be of good cheer, for my soul dearly loves thee,
and in my heart thou art written not to be forgotten; together with our dear babes,
whom it greatly tenders my heart to think of.
The Lord preserve you all in the bosom of his love;
who can be more to thee and thine than I ever can be:
into his fatherly protection I commit thee, with myself and all that we enjoy,
to be ordered and preserved.

It is but reasonable he should have all offered up unto him: for what we are,
and what we have, we are by him, and have received from him,
that he may have the praise of all, who is eternally worthy, God blessed for ever.
Amen.

By this thou, with Friends, may know that I am well every way,
and have had comfortable and good service among Friends and friendly people in this city,
where there is great need of faithful labourers; yea, even all over this nation;
because many are inquiring the way to Sion:
wherefore God`'s faithful servants are concerned to visit city and country,
that the gathered may be established, and they that are not yet gathered,
may be brought in.
I came to this city on the fifth-day, where we had a heavenly meeting,
and on sixth-day evening, as I was waiting upon the Lord,
an exercise came upon my spirit and it opened in me that I was
to go to a place southward to have a meeting next first-day,
I knew of no place where any meeting had been kept;
but the exercise remained weighty upon me;
so I inquired of Friends if they knew of any meeting kept that way next first-day;
but none could tell me of any.
At last I told William Edmundson of my exercise, and he named Wicklow to me,
and an answer was in me, that that was the place I was to go to;
being twenty-four miles off, where a meeting had never been before; of which hereafter.

[.signed-section-closing]
So I rest thy loving husband,

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
Dublin in Ireland, the 22nd of the Third month, 1671.

--

Accordingly I went on seventh-day, and two Friends with me,
and gave word that I intended to have a meeting in that town next day,
being the first-day of the week.
The report going forth, that an English Quaker was come to preach,
there was a mighty noise of it in the place, the people being stirred up by the priest.
The governor, one Hammond, lived at the castle, a garrison of soldiers being kept there;
and the priest laboured much with the governor aforehand, as I was told,
to put me in prison.

One of the friendly men I have mentioned, being a carpenter,
was willing to let us have the benefit of his workhouse to meet in;
there being several Friends and friendly people come out of the country:
and as I was ready to go from the inn where we lodged, the landlady said to me,
"`For God`'s sake, go not along the street,
for there is a guard of musketeers waiting at the cross
to take you--I will show you a back way.`"
I said, "`I accept of thy love, but I must not go any private way,
but along the town street; for I have a testimony to bear for the Lord in this town,
in love to the souls of people.`"
So by the time we were well seated in the place as aforesaid, before my mouth was opened,
came a sergeant with a halbert, and a guard of musketeers with him;
and the sergeant said, I must go along with him before the governor.
I answered, "`What authority hast thou to take me?
If thou hast a warrant so to do, I shall go.`"

He held out his halbert, and said, "`This is my warrant.`"
I said, "`You need not have come to us with your swords and guns,
as those who came against Christ with swords and staves;
we are known to be a peaceable people: howbeit I shall go with thee.`"
They took me to a house where the priest, his wife, the governor, and his man,
and some more were collected.
The priest being in a rage when I came in, said to the governor, "`Sir,
this is the deceiver; this is the deluder who is come from England,
to delude people here; I hope you will do justice, and execute the law.`"
The governor being pretty moderate, said nothing for some time; but walked to and fro,
being in a large room; and the people in an uproar, pressed in at the door.
I was willing to let the priest rage on a little, till he had vented himself,
that he might be the more manifest to the people.
At last, I said to him, "`Thou sayest I am a deceiver, and a deluder.`"
He answered in fury, "`So thou art; so thou art.`"
But I said, "`Have patience,
and let thy moderation appear unto all men and hear what I have to say,
to clear myself from thy false accusation; for I shall not take thy assertion for proof:
I have had patience to hear thee; art thou a minister of Christ?`"
"`Yes;`" said he, "`I am.`"
I replied, "`But if I prove thee a liar, as by the witness of this people thou art,
in charging me with that of which thou canst bring no proof;
thou art out of the doctrine of Christ, and so no minister of Christ, but of antichrist,
and of thy father the devil; and therefore thou art the deceiver,
and the deluder of the people.`"

Upon this the priest`'s mouth was stopped, and he made to get out at the door;
but the people were so thronged, he could not; then I turned to the people,
"`You hear,`" said I, "`that your minister hath charged me without proof,
that I am a deceiver and a deluder; did you ever see my face before?
or did you ever hear me speak before now?
Which of you, or who have I deceived or deluded?`"
But they were all silent: some more words I spoke, to manifest to the people,
that their minister was no minister of Christ, according to the holy Scriptures;
at which the priest cried out to the governor, "`I pray you, sir, take him away;
I hope you sent not for him to let him preach here.`"

All this time the governor was silent,
and I declaring God`'s everlasting truth to the people.
At last the priest`'s wife said to the governor, "`I pray you, sir,
let him not preach here; commit him to jail;`" it being near by, and the jailer present.
Then the governor spoke to me, in answer to the priest`'s wife`'s request, and said,
"`I am here in place to do justice, in executing the law, which you have broken,
in coming to this town to keep an unlawful meeting and
conventicle in the time of Divine service.`"
I said, I knew no such service performed in the town,
neither did I understand that I had broken any law.
"`How can it be, that I and my friends have broken the law, who were not found preaching,
reading, praying, or performing any exercise that is looked upon to be worship to God;
only we were met in a peaceable manner in silence, wailing upon, worshipping,
and serving the Lord our God in spirit and in truth.`"
"`It is no matter,`" said the governor, "`what you pretend; you were met,
as before I have said, and I must commit you to jail.
Jailor, take him away.`"
A Friend, newly convinced, spoke some few words to the priest,
about his accusing me falsely; and the priest`'s wife said, "`Sir,
commit that man too;`" which he did.
Another friendly man also speaking to the priest, his wife said again to the governor,
"`I pray you, sir, commit that man too;`" and so he did.
We three were committed to prison (the priest standing all the while silent,
and trembling still); and when we came forth of the house,
there was a great multitude of people, and the jailer said to us,
"`Come after me:`" (he lived above stairs, and the prisoners were underneath).
He took us into a room beyond his own dwelling, which was pretty large,
and the people came in and filled up our room, the jailer`'s, and a part in the third,
and the jailer hindered none.
In a little time my mouth was opened in the demonstration of the power and Spirit of God,
and I preached the way of life and salvation to the people,
in and through Jesus Christ his Son, by believing in his pure light,
and walking answerably to the teachings of his grace,
and the reproofs of his holy Spirit,
by which they might receive power to become the sons of God,
and to strengthen the faith of those who believed therein.

It was a blessed day for the Lord and his truth,
for his heavenly power broke in upon many, and several were convinced,
and received the truth in the love of it; and many made confession thereunto,
and told the priest they were satisfied, by what they had heard me speak,
that I was no such man as he said I was,
and that we were not the people he had persuaded them to believe.
The truth was cleared from his aspersions,
by which the witness of God was reached in peoples`' consciences,
and they would not let the priest alone,
till they got him to promise that he would dispute with me; he having boasted,
that if he might but have the opportunity to manifest that deceiver, he would.
The hour was set next morning by eight o`'clock;
and they agreed that I was to go to the priest`'s house, and the jailer with me, who said,
before we did go, "`I thank you, Mr. Banks, for the good sermon you have preached to us;
for our minister never preached us such a one in his time;
and I believe you are no such man as he said you were.`"

Before the hour came the priest broke his word;
for instead of staying to dispute with me,
he made it his business timely in the morning to go to the sheriff`', about two miles off,
to tell him what a numerous meeting the jailer had suffered to be in the county jail,
above stairs, such an one as never was in the county itself; and, said the priest,
"`I entreat you, sir, either take some course in time,
or else I fear all the town of Wicklow will be Quakers,
and then there will be no abiding for me.`"
A sober man being present, made it his business to come and tell me and the jailer;
and that the sheriff said, if he had known it,
the utmost door of the house should have been shut against us all,
and we kept there till we had been delivered by due course of law;
and also said to the priest, "`If the jailer, or any other, suffer the like again,
come and inform me and I shall take a course with them.`"
When the news came to the jailer, who was a man of a pretty noble spirit,
"`What,`" said he, "`have I been a jailer eight years,
and know not what belongs to my place?
So that I have my prisoners when there is occasion for them, I`'ll set my doors open,
and they shall go and come who will.`"
And accordingly he did so, while I was there, which was but three days,
he keeping a public house.
During the time I was there, as I remember, except when I was in bed,
I was scarcely one hour without some people coming to see me,
and discourse with me about the principles of religion; so that I was sorry for nothing,
but that I had no longer time there, the truth having prevailed so much upon the people,
and begotten true love in them to it in so little time.
Everlasting praises unto the Lord alone, whose the work is,
and by his own power he is the carrier on and manager of it.

In a little time, the jailer, with some others of the town, who persuaded him to it,
when the priest had failed and broken his word,
so that his own people even hissed at him, agreed to speak to the governor,
to have me brought before him, and told him they did believe I was an honest man,
and they would have him let me go out of prison.
He bid the jailer bring me up next morning to his chamber, being the third-day,
at eight of the clock, and he would examine me, seeing the priest had failed.
Accordingly, with the two Friends committed with me, I was brought before him;
and in great moderation the governor reasoned with me for about an hour,
about our manner of meeting, and the worship of God,
and what we believed concerning Christ, and of honour to men in authority;
all which was cleared to his satisfaction.
He confessed to the truth of what I spoke,
and said he was satisfied with the answers I had given him,
and asked what I would have him to do for me,
being I was the first of our people he ever had to do with, he would willingly let me go,
if he could be clear and answer the law.
I told him it was my liberty I desired and prized;
and I believed it was in his power to set me and my friends at liberty.
He said, he believed well concerning me, and thought I was an honest man:
so if I would promise him to appear at the assize or sessions, when there was occasion,
or get any to do it for me, that he knew, I should have my liberty.
I told him, I neither could do it myself, nor desire another to do it for me.
"`Well,`" said he,
"`if you will promise me you will never come to keep any more meetings at Wicklow,
I will let you go.`"
I answered, "`I cannot do that; but if I do, if thou hast power so to do,
thou mayest put me in prison again, and I believe I shall be as willing to suffer then,
as now.`"
So he set us all at liberty, and said to me, "`God keep you in the mind you are now in,
for I think you are in a good mind.`"
So I took leave of him, and said, "`Governor, fare thee well; and in so saying,
I truly desire thy welfare, both of thy body and soul.`"
We came down with the jailer to his house, and I said to him, "`Now we have our liberty,
we may take our leave of thee.`"
"`Yes,`" said he, "`and pay me my fees.`"
"`Fees,`" said I, "`what is that?`"
"`Oh,`" said he, "`it seems you never have been prisoner before.`"
"`Yes,`" said I, "`I have.`"
"`And,`" said he, "`did you never pay fees?`"
I answered, "`No.`" He replied, "`Well,
being you are the first that ever I had in my custody of your people,
I will not keep you; because the governor is pleased to set you at liberty;
but if any more of you come here, I will put you in the dungeon,
if you will not pay fees.`"
"`Well,`" said I, "`we must leave that to what time will bring forth.`"
So he gave us our liberty, and we called for drink to give him, he keeping ale to sell;
we also had some victuals of his wife,
and laid in his beds for I saw our time was like to be so short,
that we made no provision for ourselves; so, in consideration of these things,
when we came away, each of us gave the jailer twelve pence,
with which he seemed to be well pleased.
I went to Dublin again, where Friends were glad to see me,
and we were refreshed together in the enjoyment of the Lord`'s presence:
and from thence we travelled into the north, visiting Friends,
where the Lord hath a good people: from whence I sent the following letter to my wife.

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

The truth of our God is exceedingly precious,
and very desirable--blessed be his name for evermore,
who hath made us sensible of the same, to the gladdening of our hearts.
I feel true unity with thee therein,
and it is cause of comfort to me in all my travels and
exercises for the Lord and his truth`'s sake,
that thou drawest with me in true subjection, and with a willing mind under his yoke;
to the end that his will may be done by us.
Oh! that we may carefully keep here; for then surely great will be our reward,
if we continue unto the end: for great is and shall be the reward of the faithful.

Having been this day at a very large precious meeting,
where many people besides Friends were present, I have not time to write what I would,
and partly because of the haste of the bearer; but in a word, I am well,
and the Lord is with me; and I am freely given up, and made willing to follow him.
Since I came from Dublin, I have visited Friends`' meetings,
and been into the Scot`'s country, as it is called,
where I had the company of three Friends,
but George Grigson hath been more with me than any other Friend in the ministry.

After the next first-day`'s meeting,
which is the Province Meeting kept every six weeks near Lurgan, I intend,
if the Lord will, to go towards Dublin again, and it may be three weeks ere I get there.
When I am clear of that city, as the Lord makes way, I intend for Wicklow, Wexford,
Clonmell, Tallow, Youghall, and so on to Cork and the West,
where the Lord is bringing forth a people,
notwithstanding all Sion`'s enemies and opposers.
Truly may I say, as being an eye-witness, the harvest is very great in this nation.
Oh! that the Lord would be pleased to fit and
prepare and send forth more labourers into it.

[.signed-section-closing]
Farewell, my dear wife, with my sweet babes.

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
Near Lurgan, in the North of Ireland, the 21st of the Fourth month, 1671.

--

In my return, after ten weeks, it came upon me that I must go to Wicklow again;
and when I came to Dublin, there was a letter from Wicklow,
informing that the people desired another meeting,
and that the sergeant who took me before the governor,
was willing we should meet in his house.
The priest hearing thereof, threatened him and he was afraid,
so that when I and Friends came there the man durst not let us meet in his house.
We got another house, but it would not contain all that came; yet there we met,
and it was a blessed heavenly peaceable meeting,
without any disturbance at all--praises unto the most high God,
who has all power in his own hand, and thereby can do whatsoever seems good in his eyes,
notwithstanding the determination of wicked and ungodly men.
Not long after, so soon as the priest had an opportunity,
he began to prosecute and imprison Friends for tithes and such like things,
and got several put in prison, who came to visit that place;
but the truth prospered so much the more,
and a meeting of God`'s people was set up in that town, and continueth.

From Dublin, before I went to Wicklow the second time,
I wrote the following letter to my wife.

[.embedded-content-document.letter]
--

In the nearness of that love which remaineth in my heart without change,
I write unto thee; and my prayers are to the Lord for thee, and all with thee;
that you may all live in love, and in the fear of God; so will all go well,
and be kept in good order, both within and without.

My dear heart,
as the Lord has been pleased to work a willingness in
thee to give up and part with me freely,
for his name and Gospel`'s sake, have thine eye to the recompense of reward,
even peace with him; and treasure it up in thy bosom,
that it may be thy everlasting portion, when time here shall be no more.

The breathing of my soul is for thee, as for myself, for he hath made us one:
the Lord preserve thee unto the end, in faithfulness to do his will,
that thou mayest be kept in true unity and fellowship with his people,
in keeping to meetings on first-day and the weekday.
Neglect no opportunity that may make for the good of thy soul,
and then nothing for the body will be wanting.
Exercise thyself in his law written in thy heart,
that so thou mayest feel the streams of his love in thy inward part;
let truth be the girdle of thy loins, and faithful waiting in his light, thy dwelling;
that although we be far separated as to the outward,
we may be made witnesses more and more of the joy of his salvation therein;
partakers of that peace which the world can neither take nor give.

Thou and my dear children are so near and dear unto me,
that many times the remembrance of you draws tears from me;
for the further I am separated from you, the nearer you are unto me in spirit;
and at this time my heart is broken into tenderness, being sensible,
according to the exercise which attends me,
that the Lord will yet draw me farther from you, who knows my heart,
that if I might tomorrow with clearness, return to thee, oh,
how gladly would I embrace it!
But truly, my dear, the Lord requires of me,
and I cannot forbear to give some hint thereof, that after I am clear of this nation,
I must go for the West of England.
From Cork, I intend to take shipping for Minehead in Somersetshire, and so farther,
as the Lord is pleased to order me when I come into that nation.
Truly the harvest is great in most places;
and as the Lord hath been pleased to count me worthy to be called,
and sent forth into his work and service, amongst his ministers and messengers,
though but one of the least of many, I am freely given up to his blessed requirings,
to labour and travail what in me lies, that in the end I may receive a penny.

Therefore, my dear,
as the Lord hath counted me worthy to bear a public testimony for him,
in preaching the everlasting Gospel, pray with me, that in faith and patience,
and with a heart undaunted, I may bear it faithfully unto the end,
to the praise and glory of him whose the work is, who is worthy for evermore.
That when in this my intended voyage and journey I have performed what the Lord requires,
I may return to thee with true peace, in the joy of his salvation;
and that we may live and enjoy one another while we live,
as those who enjoy one another in the Lord, where is the peaceable and quiet habitation;
until which time, the Lord God of life and glory keep and preserve thee,
with our little ones, myself,
and all his faithful people-- who is a faithful keeper and preserver,
and withholds no good thing from his dear children, who can be more to wife,
than husband, and to children, than father and mother; who is alone worthy of praise,
honour, and glory, both now, and for evermore.
Amen.

[.signed-section-closing]
I am thy dear husband, with love to thee still renewed,

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
Dublin, the 14th of the Fifth month, 1671.

--

In about two years after, the Lord required of me to go and visit Ireland again;
and coming to Wicklow, I went to the jailer`'s, to see Friends in prison,
and to have a meeting in the town.
When the jailer saw me, he said, "`Oh, Mr. Banks (as he called me,) are you come again?
I think you need not have come any more;
you did your business the last time you were here,
for I think all the town of Wicklow will be Quakers.`"

"`But notwithstanding what is done,`" I said,
"`it is my business to come to see how the Lord`'s work prospers; for the work is his,
we are no more than instruments in his hand, which he is pleased to make use of;
and more than that, thou hast got many of my friends in prison,
and I must needs visit them.`"

The next time I came to visit this nation, I came to this place again,
which was in about two years more, and the priest of Wicklow was dead,
the governor gone for England, and no soldiers there, truth still prospering,
and Friends`' meeting settled and established by the power of God in peace and quiet,
and Friends well preserved in and through their sufferings.
This makes me say there is none like unto the true and living God, who has wrought,
and is working wonders in the earth, and bringing strange and mighty acts to pass.
And when I had travelled through most of the nation, visiting Friends and other people,
being in the north, in that part called Scot`'s country, I came up to Antrim,
with eight Friends more,
intending to have a meeting at our friend James Greenwood`'s house.
When we came, there was a constable with his staff, and a company of people with him;
and he stood at the Friend`'s door, and said he had an order from the lord Mazarine,
that we should not meet there.
I bid him produce his order, and we would give him an answer.
He holding out his staff, said that was his order, and we should not meet there,
meet where we would.
I answered, "`Keep to thy word;
we shall be content to meet in the King street,`" being a market town,
and Friends and many people being come together,
my mouth being opened in a testimony for the Lord,
and in love to the souls of the people,
in turning their minds to the teachings of God`'s Spirit in themselves.

The constable, who was a Presbyterian, came with his staff, in a rage,
to pull me out of the meeting; and I said to him,
"`Art thou not ashamed to manifest thyself a liar before so many people?
Didst thou not say we should meet where we would, except in our friend`'s house?`"
So he was smitten, and could do no more himself,
but went among the people and got a butcher, a man picked out for his purpose,
to pull me away.
And he came in a most rigid manner, and took me by one arm,
and haled me down the street a little way; and there came a Friend out of the meeting,
and said to him, "`Cease from persecuting the innocent,
lest the judgment of God fall upon thee.`"
Which did immediately seize upon him, and his hands were loosed from me,
that he had no power to pull me any further,
but stood trembling by me (I being declaring the
truth still,) and he went home and took his bed,
and never got from under the judgment till he died.
In a little time I saw it my place to be silent, and our friend George Grigson said,
"`Oh,
you people of the town of Antrim! is this the entertainment which you give to strangers?
Some in the days of old, by entertaining strangers in true love,
entertained angels unawares.`"
A glorious heavenly day it was for the Lord and his blessed truth,
in strengthening the faith of his people,
for his power and heavenly presence was livingly manifested in the meeting,
and many were convinced, and several came to own and receive the truth in the love of it.

In the time of our meeting, there was a sudden storm of wind and rain, the like of which,
for the time it continued, I have very seldom or never seen,
for the water with the dirt ran in a stream amongst us,
so that all or most of us were wet to the skin.
The storm of wind and rain, was a figure of their raging persecuting spirit;
and when it was over, the sun broke forth, and shined very clear;
a true figure of the victory the Truth obtained, through the power thereof.

This year, going to London, to the Yearly meeting,
I wrote the following letters to my wife:

[.embedded-content-document.letter]
--

[.salutation]
My dear and loving Wife,

Have faith in and through all thy exercises,
and know thy faith to stand in the power of God,
which gives victory over all that is contrary to it.
It is good and safe to trust the Lord in every condition,
who undoubtedly will provide things needful every way, both for us and ours,
as he sees we stand in need, if we are freely given up to do his will,
and are content therewith.
He hath given us an understanding, blessed be his name for ever, and in temporal things,
as well as spiritual, diligence must be used, with a godly care and honest endeavours,
with what labour and pains the body is able to answer; which always was my concern,
when at home; but still in and through all, to have a true regard to God in our hearts;
this is the way to bring a blessing and increase upon all our endeavours.

By this, thou, with all thine, and Friends, may know that I am well every way;
I am bowed in humility before the Lord for the same.
In company with my acceptable companion, Thomas Langhorn,
I came here the last seventh-day night.
John Burnyeat is now with me; things here are all quiet and well at present,
and meetings full and large.

[.signed-section-closing]
Farewell in the Lord.

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
London, the 11th of the Third month, 1675.

--

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

In the feeling of the love of God, my heart is truly open towards thee and thine,
with a true desire that thou and they may live in the holy, pure fear of the Lord God,
with a true willingness in thy heart, freely to give up whatsoever the Lord doth require,
be it in doing or suffering; that so he may be reverenced,
worshipped and served in all things, with delight.
And that upon no account, wherein his truth and glory is concerned, we may say,
Why is it thus?
For with him all fulness dwells, and if he bless, none can curse;
blessed and praised be his holy name for evermore!
The way to bring a blessing upon us and ours,
is in all his blessed requirings freely to give up to do his will,
though it be ever so much in the cross to ours; for this brings the blessing, peace,
and lasting gain in all respects.

For thy comfort I may tell thee, that since the time I parted from thee,
I have been made so much a witness of the enjoyment of the power and presence of God,
among my brethren, that I would not have missed it,
for all that can be mentioned to me in the world.
Oh, the in-breakings of the love and melting power of God,
and the shining of his glorious light amongst us, in this our Yearly Meeting,
where Friends in the ministry were, from most parts through this nation!
How were our hearts broken, and our souls comforted and consoled!
The Lord did certainly evidence unto us, that our meetings,
and what we there offered to him, were acceptable and well pleasing before him.
Oh, the sweet harmony of life that was amongst us! the streams whereof flowed,
and many living testimonies were borne,
to the greatness and sufficiency of the power of God that overshadowed us!
And oh, the subjection, brotherly tenderness,
and godly care that were amongst us one over another, that we might speak one by one,
as the Lord, by his Spirit, moved and gave utterance!
How near were we to the Lord, and how dear one unto another,
in the unity and fellowship of his blessed holy Spirit!
What a blessed communion was there held,
and how richly was the table of the Lord spread amongst us!
What thanksgiving, praises, honour and glory, were many made to ascribe unto him therefor!
And there was a godly care also for the prosperity of the truth,
and spreading abroad thereof,
together with the establishing of Gospel order and discipline in the churches of Christ.

May I never forget this glorious, heavenly appearance of our God amongst us,
by his power and life-giving presence;
but that it may be of lasting remembrance to me while I have a being:
for it hath not only been to me, but to many brethren,
a day of great joy and spiritual comfort,
to the building of us up together in the most holy faith.
My dear, my heart is overcome in the love of God,
with a desire that thou mayest feel the same to thy comfort, with all thine.
The Lord keep and preserve you all, and all my dear friends thereaways,
to whom is my sincere love remembered.
And let all be encouraged to go on in the way of truth and righteousness,
though we may meet with various trials and exercises;
for of a certain truth the Lord is with us, and by his power goes before us,
as our king and captain, who pleads our cause, and fights our battles for us,
with all Sion`'s enemies and opposers.

Blessed and happy are all they who bear a faithful testimony for him,
while they have a day and time so to do.

[.signed-section-closing]
Thy faithful husband,

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
London, 29th of Third month, 1675.

--

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

By this thou mayest understand that I am well in all respects,
blessed be the Lord my God for ever, who by his power hath preserved me.
I am now clear of this city and country,
having faithfully discharged my duty in what the Lord my God hath required of me,
and tomorrow intend to set my face towards home.
I have passed through a troublesome country, by wicked informers and other officers;
but the Lord hath so ordered it in his wisdom,
that no Friend has suffered two-pence upon my account, at any meeting in all my journey;
though the Lord knows I never held my peace for fear of suffering,
but did as he ordered me, whether to speak more or less, or to be silent.
Bless thou the Lord, O! my soul,
in so ordering and preserving me in this and many other great exercises and tribulations,
both in body and spirit, among these wicked informers, where Friends have suffered much,
by what they call the Conventicle Act.
I had seventeen meetings among them.
So having not much more in my mind to write,
I bid thee farewell in the Lord Jesus Christ,

[.signed-section-closing]
And remain thy husband in that which changeth not,

[.signed-section-signature]
J+++.+++ B.

[.signed-section-context-close]
Bristol, 30th of the Sixth month, 1676.

--

In the year 1676, I went into Ireland again;
from whence I wrote the following letters to my wife, giving some account of my travels.

[.embedded-content-document.letter]
--

[.salutation]
My dear,

My love in the strength of God`'s power reacheth unto thee,
and in that I dearly salute thee and all thine;
and my prayers are put up unto him for thee, with all thine.
The Lord encourage thee by the continuance of
his love in faithfulness to follow and obey him;
that so the sense of his love in thy heart,
may constrain thee to meet often among his people;
and with all diligence to wait upon the Lord in true silence,
to feel refreshment from his presence; that so in the life which is pure and precious,
thou mayest more and more increase,
that as the blessing of the Lord is unto the seed of the righteous,
so thou mayest feel it to be upon thee and thine.

In this living exercise the Lord preserve thee, low in his fear,
that in all godliness of life and conversation
thou mayest be a good example to thy family,
and with godly care mayest train up thy children, now when they are young,
as becomes the truth.
When they do amiss, correct them according to the fault, in the fear of the Lord,
laying aside and keeping down all passion and heat of spirit;
that they may be a comfort to us in our time,
and that we may be found clear in discharging our duty concerning them,
before the Lord and all people; that if they live to the age of men and women,
and have children, they may have cause to remember our godly care concerning them,
and tell of it in like counsel unto their children,
and so from one generation to another.

Let not a foolish pity or foolish fondness tie our hands from correction,
when there is need of it, as too many do,
for this has more regard to the body than the soul;
though surely that which hurts the soul, must needs injure the body also.
Let us not be too careful for their bodies, or for portions or worldly preferment,
but using honest endeavours, leave the issue to the Lord,
who I fully believe will provide what shall be sufficient for them;
as we are chiefly concerned for the good of their souls, and there leave it.
Let every one of them as they grow up,
and have ability of body and a capacity accordingly,
be employed with all diligence in some work or business,
that so they may be helpful unto thee, and become serviceable in the creation.
This I could not pass with clearness,
being often under a weighty exercise to have our
children trained up in the fear of the Lord;
that they may be preserved in the way thereof,
that none oi them might wander or go astray into the broad way of the world,
either for husbands or wives, though ever so rich;
nor anything else this world can afford, as I see too many do, to the grief of my soul.

By this thou with thine and Friends may know that I am well,
together with my companion John Watson,
whose company and service is very acceptable to me and God`'s people;
and our travels and exercises are made very comfortable unto us,
because of the presence of the Lord that doth go along with us;
and many precious and heavenly meetings we have had in many places of this nation,
both among Friends and other people, who are very open to receive the truth,
as also in this city, where many are inquiring the way to Sion,
with their faces thitherward.
Because of this the devil is stirred up in great wrath, and the heathen rage,
and the wicked imagine vain things against the Lord and his anointed,
and come rushing into the meetings in great disorder,
like so many wild beasts out of the forest, especially the collegians; but the Lord,
by his power, is pleased so to tame them, that they are put to silence,
and made to be quiet.
Oh! how powerfully and effectually hath the Lord our God appeared among us,
in this our Half-year`'s Meeting, which began last fourth-day,
and kept twice every day to the week`'s end; also two yesterday,
and the women`'s meeting this day.
The men`'s meeting will be held tomorrow, and their week-meeting on fifth-day.

After the next first-day we intend for Mount-Melick, and so towards the north,
being clear of this nation, through diligence and hard travel.
The Lord, by his power, hath mightily appeared amongst us in our meetings,
uniting our hearts together and prospering his work;
the praise of it for ever belongs unto him.
For what he has already done, my soul praise thou the Lord.

Oh! that Friends might live in love and unity together,
that as the Lord hath been good in preserving a remnant alive to himself unto this day,
they may continue so unto the end;
and whatsoever would arise among them that in anywise tends to
break their heavenly unity and brotherly fellowship,
and sows dissension in the churches of Christ, may be nipped in the bud; for if it grow,
the effects of it will be bad, and do great hurt among the plantation of God.
The Lord keep and preserve all watchful,
that the envier of our happiness and truth`'s prosperity may be kept out and prevented.

It still remains with me to go out of the north of this nation into Scotland,
because of which, I have travelled very hard.
When we came here first, we staid but one week,
and took our journey through the counties of Wicklow, Wexford, Clonmell, Tallow,
Youghall, and so to Cork, and into the west, and back by Cork again,
and so by Charleville and Mallow, down to Limerick,
from whence Friends came with us to this Half-year`'s Meeting.

We travelled very hard three hundred and sixty miles to get to it,
in which time we had good service for the Lord in many blessed heavenly meetings.
With the remembrance of my love to thee, and my dear children, and Friends,
not forgetting my duty to my father, I conclude, and remain,

[.signed-section-closing]
Thy ever loving husband,

[.signed-section-signature]
J+++.+++ B.

[.signed-section-context-close]
Dublin in Ireland, 13th of the Ninth month, 1676.

--

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

In that love which many waters cannot quench, neither floods drown, I write to thee,
and have thee daily in my remembrance, together with our dear and tender children,
who are always near and dear to my heart, and I hope ever will be unto the end of time,
however the Lord may be pleased to dispose of me.

We intend to go from this sea-port town, in order for Portpatrick in Scotland.
We are both well every way;
praised and magnified be the worthy name of the Lord our God for evermore.

To the Lord and the word of his patience I commit and commend thee,
that in him thou mayest be preserved, with all thine, unto the end, in all faithfulness,
to receive the crown of life, and of immortal glory.

[.signed-section-closing]
Farewell, my dear heart.

[.signed-section-signature]
J+++.+++ B.

[.signed-section-context-close]
Donaghadeo in Ireland, the 22nd day of the Tenth month, 1676.

--

When my friend John Watson and I had travelled through the nation of Ireland,
visiting Friends therein, and been much comforted and refreshed together with them,
a concern came upon us to visit Friends in Scotland;
and we sailed in a half-decked boat from Donaghadee in Ireland,
and landed at Portpatrick in Scotland.
From Portpatrick we travelled seventy miles in cold, frost, and snow, in the tenth month,
before we came among Friends, which was at Douglas.
The evening before we came there, night came on while we were upon a mountain,
where no way was to be seen, for there was so much snow and ice that we could not ride;
and being much wearied with going on foot and leading our horses, we lost our way.
But at last Providence so ordered it, that we found a house,
and two men came forth and willingly set us into our way;
so that we got to a Friend`'s house, late at night, at Douglas,
whose name was William Michaell, and had a meeting there next day.
Though there were but few Friends belonging to that place,
we were sweetly refreshed and comforted together,
in the enjoyment of the Lord`'s presence,
whereby it is evident that with him there is no respect of persons, time, place,
or number.

From Douglas we travelled to Hamilton, and so to Drumboy, Badcow, Lithgow, and Edinburgh,
where we visited Friends and other people, and had good service for the Lord;
then to Prestonpans, Leith, and Edinburgh again, where we had two heavenly meetings,
though there were some wild scoffing people among them,
yet the Lord`'s power chained them down.
From thence to Kelso, Onter, Whittingem, Thrambleton, and so to Morpeth,
and Newcastle-upon-Tyne; and thence homeward into Cumberland.
The Lord was effectually with us in our travels and exercises,
and we were sweetly preserved together in true love and unity,
in our service for the Lord.

About this time a pain struck into my shoulder
and gradually fell down into my arm and hand,
so that I was wholly deprived of the use of it; the pain increased both day and night.
For three months I could neither put my clothes on nor off,
and my arm and hand began to wither, so that I applied to some physicians,
but could get no cure by any of them.
At last, as I was asleep upon my bed, in the night time, I saw in a vision,
that I was with dear George Fox, and I thought I said to him, George, my faith is such,
that if thou seest thy way to lay thy hand upon my shoulder,
my arm and hand shall be whole throughout.

This remained with me two days and nights, that the thing was a true vision,
and that I must go to George Fox, until at last, through much exercise of mind,
as a great trial of my faith, I was made willing to go to him,
he being then at Swarthmore in Lancashire,
when there was a meeting of Friends on the first day of the week.
Some time after the meeting, I called him aside into the hall,
and gave him a relation of my dream, showing him my arm and hand; and in a little time,
we walking together silently, he turned about and looked upon me,
and lifting up his hand, laid it upon my shoulder, saying,
"`The Lord strengthen thee both within and without.`"
I went to Thomas Lower`'s, of Marsh Grange, that night; and when I was set down to supper,
immediately before I was aware, my hand was lifted up to do its office,
which it could not do for long before.
This struck me with great admiration,
and my heart was broken into tenderness before the Lord; and the next day I went home,
with my hand and arm restored to its former use and strength, without any pain.

The next time that George Fox and I met, he said, "`John, thou mended;`" I answered,
"`Yes, very well in a little time.`"
"`Well,`" said he,
"`give God the glory;`" to whom I was and still am bound in duty so to do,
for that and all other his mercies and favours.
He hath all power in his own hand,
and can thereby bring to pass whatsoever seems good in his eyes; who, by the same,
prepares instruments and makes use of them as pleaseth him,
who is alone worthy of all praise, honour, and glory, both now, and for evermore.
Amen!

In the year 1678, as I was travelling in the West of England, in Somersetshire,
one evening I had a meeting at our friend William Thomas`'s house at Dullverton,
into which meeting came an informer, and some others with him,
and took several Friends`' names.
He was also wicked and abusive, both to me and Friends;
and being engaged in testimony for the Lord, I stopped, and said, "`Friends and people,
mark and take notice of the end of that wicked man;`" for it
was clearly manifested to me that he would make a bad end.
Some time after a Friend wrote to me, that he killed his wife,
and was hanged for it at Ilchester.
The Friend W. T., was fined by the information of this wicked informer;
but he swore against one who was not at the meeting,
and so his wicked intention came to nought.

Some time after my return home,
the Lord laid a necessity upon me to go forth with a testimony
against that spirit of separation which had sown discord,
and made division in the churches of Christ,
casting stumblingblocks in the way of the weak,
making the cross of Christ of none effect through a false liberty,
and setting up separate meetings.

But before I went, I was moved of the Lord to give forth a paper to go before me;
and I caused copies to be taken,
and sent to those places where this spirit had got the most entrance.
It was read in divers men`'s meetings,
and those who were of that spirit which the paper testified
against were enraged and cried out at some places,
"`He means us.`"
A copy of which paper follows:

[.embedded-content-document.letter]
--

[.blurb]
=== A true and faithful Testimony for the living God, and the all-sufficiency and unchangeableness of his power and spirit; against the devil and his dark power and spirit, by which he rules in the hearts of the children of disobedience, with all his cunning and subtlety in his instruments. Also a few words of counsel and advice to Friends everywhere, to keep to their first love, and to meet often together in the name of the Lord.

The Lord our God, even the true and living God,
hath promised that he will never break his covenant with his people,
nor alter the word that is gone out of his mouth.
This covenant which he hath made with, and renewed unto his people,
is an everlasting covenant of life and peace, even the sure mercies of David,
of which he daily makes those witnesses, who break not covenant with him,
but retain their first love and zeal for his name and truth.
His name is above every name, his truth is as precious as in the beginning,
and his glory shines over all in this day: endless praises unto him!
He hath gathered many into this unchangeable covenant, and made them nigh unto himself,
who are his true-born sons and daughters; children of the promise,
quickened and raised up from a state of death, to serve him in newness of life.
The work is his own, and the praise and glory belongs unto him for ever.

Herein are the sure mercies known, the durable riches, and the living substance fed upon.
He nourished us by the virtue of his word of life, when we were young and tender,
which made us grow up before him in stature and in strength,
with our hearts filled with love to him, our Father,
and in love and unity one with another.
All our life long, to this day,
hath he been ready to hand forth a suitable supply to our conditions,
as we in faithfulness waited upon him.
His word is made good and his promise fulfilled, '`I will never leave thee,
nor forsake thee,`' worm Jacob, who art little and low in thine own eyes,
that dwellest in the low valley, abiding in thy tent,
and dost not hunt abroad upon the mountains of imagination.
The promise is yea, and amen, for ever, to the seed of Abraham, Isaac, and Jacob.
The blessing that makes rich is obtained and partaken of,
in the seed and covenant of life, Christ Jesus.
I will give thee for a covenant unto the people, and for a light unto the Gentiles,
that thou mayest be my salvation unto the ends of the earth.
This is he whom God hath given unto us, and we have believed on, and received him,
so that he is become our light, life, and everlasting salvation;
the high priest of our profession; our redeemer and restorer; our captain, king,
and law-giver; our everlasting shepherd;
who by his mighty power hath brought us unto his fold of rest, where true peace is;
magnified be his name for ever.

Dear Friends everywhere, whom God hath quickened, and raised from death to life,
by the effectual working of his power,
be ye all stirred up in a holy zeal and true tenderness,
to consider what manner of persons you ought to be;
being mindful what the Lord hath done for you, ever since you were a people;
whom he hath made to be his people, who were not his people--I say,
let your consideration be serious in this matter, that so every one of you,
in this day of his power, may bear a faithful testimony for the living God,
and the sufficiency of his power and holy Spirit,
against the old enemy and adversary the devil, and his dark power and spirit.
For truly, good is the Lord, and faithful in all his promises to them who wait upon him,
as you yourselves are witnesses.
Although our travels in times past, were under great exercise and deep affliction,
with weeping and mourning, with our hands upon our loins;
and although many have been our trials both within and without, the Lord,
by the all-sufficiency of his power, hath wrought our deliverance,
as we relied upon the same, so that sorrow and sighing are fled away,
and everlasting joy is sprung up; yea, endless joy is known here,
endless comfort and satisfaction;
where we can praise the Lord together in the beauty of holiness,
being arrayed with the clothing of his spirit, which makes us all comely before God,
even the Spirit of Truth, the Comforter.

Our unity and fellowship stands in the spirit and in the truth,
that comes from the God of truth, who is light, and in him is no darkness at all;
in which, as we live and dwell, we have unity one with another,
and all the powers of hell and death are not able to break us asunder,
nor an unclean spirit to hurt us; for we have salvation for walls and bulwarks,
and there is no destroying in all God`'s holy mountain.
For the destroying, wasting, and dividing spirit, and cunning deceit,
is upon Esau`'s mountain and in Cain`'s field, out from the life and power,
the true light and fear of the living God; who is a God of order,
and preserves all his children and people, in a comely order,
living a godly life and holy conversation in all their undertakings;
to the end that they may honour and glorify him in their day,
by bringing forth much fruit, faithfully waiting upon, and worshipping and serving him.

Oh! the love of our God unto us; the great care and tenderness he hath had over us,
ever since we were a people, that we might be faithful labourers in his vineyard.
Did he call us to be idle?
Surely nay.
Did he give a gift unto male and female, that we should hide it in the earth,
and not improve it to his glory?
Oh! nay.
Hath he done so much for us, that we should always be as children,
and neither speak nor act as men?
Surely nay; but that we should grow up in stature and strength before him,
as perfect men and women in Christ Jesus our holy head, that we might all work together,
as a body fitly framed in holy order, in his heavenly power and spirit,
which leads into purity and holiness, love and true unity, which stand in the spirit,
where no rent is, and where no strife nor separation can enter.

Through the blessed working of his all-sufficient power,
the Lord in his love brought us together and made us a people, and hath preserved us so,
to his praise and our eternal comfort.
And it is the work of the devil, by his evil power and dark spirit,
and wicked instruments actuated thereby, to divide and scatter us asunder.
But my testimony for God, to you my friends, which still lives in my heart,
is to the all-sufficiency of his power.
Keep close to that which first gathered you near to the Lord and one unto another,
who hath placed his name amongst you; and then not all the powers of hell and death,
or any unclean spirit, shall be able to separate, or hurt, or break you asunder,
for the power of God is your foundation.
Settle upon this, for it stands sure, and is of God`'s own laying;
be ye as weighty stones of his building,
and then you cannot be moved by all the strength of man`'s reasoning,
nor by all the cunning of the fallen wisdom of satan;
but as your dwelling is in the pure light,
and as you retain the feeling sense of the Divine life, and keep close to the power,
you will be enabled to say, The Lord our God is the true and living God,
and besides him there is not another;
and therefore we will trust in him and rely upon his power and holy Spirit,
which is all-sufficient for ever.

And now, dear Friends, although the devil, the old liar, be at work in this day,
in a great mystery, even the mystery of iniquity, by his evil power and rending spirit,
heed him not, nor his instruments, for the power of God is over him and them all, yea,
over all that is contrary unto it.
For he that was the first, will be the last, who said, I am Alpha and Omega,
the beginning and the end; and he will tread down satan shortly,
and all his agents of mischief.
He has promised to bruise the serpent`'s head,
which daily is fulfilling by the dominion of his power and holy Spirit, over hell, death,
and the grave, and every foul, unclean, quibbling spirit;
for these are appointed for the fire of wrath and judgment,
whose end is to kill and destroy, and make rents and breaches among God`'s people,
where it gets an entrance, of which I warn Friends to beware.
It is one of the devil`'s last shifts, to appear in the name of light,
and ancient power and truth as it was in the beginning;
a transformation to cover his dark power and spirit, which creeps cunningly in the dark,
to deceive the simple.

But he will not now be called the devil, he will be called God;
he will not be called an adversary, but he will be called a friend,
by those who are his subjects, though under another pretence:
for if any call him otherwise, then he rageth in his instruments;
but we must tell him plainly, he is the old liar, the same that deceived Adam and Eve,
and the greatest enemy and adversary the Lord, his truth, and people have at this day;
and they who take part with this evil spirit, and suffer it to rule in their hearts,
so that by its strength they become open opposers,
these are also great enemies to the Lord, his truth, and people;
but no weapon formed against them shall prosper.

But endless glory to the true and living God! this subtle serpent with all his times,
cunning and subtlety,
in the pure light is seen and discovered in all his wicked works and workers,
and cunning contrivances:
and that power is risen in the hearts of all who keep faithful and close to it,
which will tread him down,
and preserve in the pure unity and Gospel-fellowship
which stand in the Spirit and in the Truth.
But this wicked spirit hath no share in it, that would make breaches and rents,
and let in the wild beasts of the field to devour God`'s heritage,
and so scatter abroad the sheep of his pasture,
and drive them back again into spiritual Sodom and Egypt,
where the Lord of life and glory is crucified and slain, and made merry over.
This spirit is not of the Father but of the world, and will lead into looseness,
lightness, and false liberty, where it gets an entrance.
This subtle spirit hath induced too many, through its cunning craftiness,
to slight men and women`'s meetings, and the power of God by which they were set up,
and are more and more established, which would bind this separating, dividing spirit,
so that it cannot abide it, to wit,
the power and authority of the men`'s and women`'s meetings,
and the holy order therein practised, and the good effects thereby brought forth;
which tend to set up truth and righteousness, and sweep out all deceit, hypocrisy,
uncleanness, and false liberty, that the house may be made clean throughout,
and a godly care held that it be kept so.
This disquiets that wicked spirit, and it rages in some of its instruments,
though it appears in others more subtly,
being not content with the liberty the truth allows, and with the order it hath set up,
there being not room enough for their wills and sensual wisdom.

The Lord in his love, and by his light, hath clearly given me to see its way,
that it leads to the chambers of death and of hell,
and he hath delivered my soul from its snare, who once was in danger to be taken by it,
when men`'s and women`'s meetings were first set up, by entering into reasoning with it;
and this is the way it gathers strength, and draws a veil over the mind of the simple.

Wherefore rejoice thou, O my soul, and praise the Lord with all his ransomed ones,
because he, by his glorious power, is treading down satan,
and the redeemed of the Most High shall rejoice,
and sing praises unto him who sits upon the throne, and unto the Lamb for evermore.

And let none say, Who is able to make war with the beast, and the number of his name,
but live by faith; and let your faith stand in the sufficiency of God`'s power,
as those who in the victory and dominion of it can say,
Who is able to make war with the Lamb and his followers,
for the Lamb must have the victory,
and the crown shall be set upon the heads of all those who continue unto the end;
the weapons of whose warfare are not carnal but spiritual, and mighty through God,
to whom be the glory and honour for ever.

Dear Friends everywhere, to whose hands this may come,
give ear to the advice of your brother; as the Lord hath done for my soul,
every one beware and take heed of touching, tasting, or handling this spirit,
or entering into reasoning with it, lest thereby you be overcome.
I say as one who have a necessity upon me to warn you in the name of the Lord;
take heed and beware of the spirit, that bringeth forth these evil fruits,
and works such bad effects, though under a fair pretence,
lest you be betrayed and beguiled thereby, as the serpent beguiled Eve;
but keep your zeal, retain your integrity and first love for the Lord,
his truth and people.
Beware and take heed of giving way to that mind which would cause you
to forsake the assembling of yourselves together amongst God`'s people,
or to slight or make a light matter of men`'s and women`'s meetings; but be faithful,
careful, and diligent in keeping all your meetings in the name and power of God,
first-day and weekday, and men`'s and women`'s meetings; and cry not.
My business, my business, my work and my trade,
when you should go and wait upon and worship, or do any service for the Lord;
but mind the Lord`'s work and business, and live by faith,
and you will have time enough to do your own;
lest your love be so much to perishing things,
that you be not found worthy of Christ Jesus;
to whom let every soul be subject in all things,
who is worthy of glory and honour for ever.
Amen.

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
Moorgate, in Cumberland, the 16th day of the Seventh month, 1678.

--

And according to what the Lord required of me herein,
I was wrought into a willingness to go forth into several counties in this nation,
to bear my testimony against this spirit, and such as were actuated by it.
I went with fear and trembling, yet the Lord furnished me with power sufficient,
to perform what he required of me, though my exercises were great,
both in body and spirit.
Whilst at the Yearly Meeting at London I wrote the following letter to my wife:

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

Thou art truly so unto me, as near as bone of my bone, and flesh of my flesh;
this is the Lord`'s own doing;
we are forever engaged to return the praise and glory unto him,
who hath blessed us and our offspring, who grow up as tender plants before him,
which makes my heart and soul tender,
to consider the great love and favour of God to us herein.
My love is with thee and thine, and my life in the truth reacheth unto you,
though I be thus separated from you;
and the supplication of my soul is to the Lord for you,
that your faith and patience may increase more and more,
that in hope you may be confirmed against all the reasonings of the enemy,
and may for ever trust in the Lord and the sufficiency of his power, which thou knowest,
my dear, hath never failed us, nor ever will, as we continue unto the end,
in the faith of our Lord and Saviour Jesus Christ.

And as the Lord hath been pleased to work thee into a
true willingness to give me up into his service,
expect me not again before I have performed it; for the will of the Lord cannot be done,
but in the cross to ours.
I have great cause to magnify the name of the Lord for ever,
who hath not only called me into his work and service,
but is pleased to furnish me with wisdom and
ability every way to perform what he requires,
according to my measure.
Let us then praise the Lord, because his work prospers both in city and country.
The Lord be with thee and thine,
and comfort and refresh thy soul in the assemblies of his people;
with whom meet as often as thou canst, first-day and week-day,
with the rest of the family, for thou knowest it was always my care when present;
wherefore I did rise early, and sit up late, and worked and laboured with all diligence,
that the same might be effected according to the desire of my heart;
and that through diligence in lawful business, with the blessing of the Lord,
I might also provide for and maintain thee with the children, in decent and comely order,
according to truth and my ability.

And as this was my care and concern when present,
I can do no less than put thee in mind of those things though absent;
not being unmindful of thy affairs and concerns as to the outward,
in which I still sympathize with thee.
This I hope the Lord as he has done, through faith and patience, and using diligence,
will make easy unto thee; for we have no cause to look back and say,
The Lord has been wanting.
But on the other hand, he hath withheld nothing from us,
that he has seen we stood in need of, as therewith we have been content;
endless glory unto him who lives for ever!

As to our Yearly Meeting; Oh! how did the Lord`'s power overshadow us,
and his pure love and life run as a stream amongst us,
with the pouring forth of his Spirit upon us in a plentiful manner;
in subjection to whose holy Spirit, we were made willing to speak and declare,
one by one, of the great work of God; confirming and establishing one another therein,
in all faithfulness.
And this was in such subjection, and holy order, very many brethren being present,
that my heart breaks into tenderness when I think of it; yea,
such was the glorious appearance of God amongst us in our meetings,
both of men and women, that the contrary spirit was never once able to lift up its head,
for the power of God was over all; so that we were made to joy and rejoice before him,
in returning praise, honour and glory unto him, who is worthy for ever;
who is carrying on his own work in order to perfect it, and none can let nor hinder,
though they may oppose.

Notwithstanding the great noise of wars, all the meetings I have been in here were full,
peaceable, and quiet; even so full that not many houses could contain them,
though it is supposed some will hold between two and three thousand.
Here is encouragement for all the Lord`'s people to go on their way rejoicing,
for the Lord our God is with us; and in faith and patience to say, Come what may come,
thy will O God,
be done! for all things work together for good to them that love Thee unto the end;
unto which the Lord preserve us all: Amen!

I intend, if the Lord will, to go from hence tomorrow, and travel towards Bristol,
and it may be one month ere I come there.
I travelled hard to come here one week before the Yearly Meeting,
which tended to clear me the sooner of this city.

[.salutation]
And now, my dear Children,

Mind the fear of the Lord, every one of you,
who can see a difference between good and evil; and be careful to do that which is good;
so shall you be preserved out of that which is evil.
Be sober and quiet, and take heed to every word your mother saith,
as though I were there and spoke it, for she tells you for your good,
what she would have you to do.

Be mindful to read as often in your books as you have opportunities,
together with the Holy Scriptures, which is the book of books.

And you my servants, James and Mary, my love is to you,
with a great desire and care in my heart,
that you may dwell together in love and unity in the fear of God;
and walk as becomes the truth, which the Lord in his love hath given you a knowledge of,
in which I truly desire your growth and increase, as if you were my children;
then all things will be well.

[.signed-section-closing]
Farewell my dear wife, children, and servants.

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
London, the 16th of the Fourth month, 1679

--

From thence I proceeded in my journey westward;
but my greatest exercise was in Westmoreland, and at Hartford, as`' I came up to London,
and afterward at Reading, Wycombe, Charlcote, Bristol, and through Wiltshire,
where I had fifteen meetings in three weeks,
at all which meetings there were many of these unruly separate-spirited people,
though none of them had power to oppose me;
yet after most meetings would be greatly enraged against me behind my back,
and threaten what they would do at the next meeting,
but never had power to open a mouth in meeting to oppose;
for it pleased the Lord to be with me in a wonderful manner;
to his praise and glory I speak it with reverence and humility before him;
for my testimony was as a flame of fire among briars and thorns,
as many of God`'s people could witness.

My companion, Christopher Story, was a help and comfort to me,
though little concerned in that exercise; yet he greatly sympathized with me in spirit,
and had a good service to Friends,
and continues a solid weighty man in the work of the ministry, both at home and abroad.

Oh! great was the exercise I travailed under many times, both in body and spirit;
for the weight and wickedness of the separate spirit bore hard upon me,
but the Lord`'s power chained and limited it.
I had little benefit either of meat or sleep, especially in Wiltshire;
for they who were of it followed me from meeting to meeting.

The following letter I wrote to my daughter, after she was placed at service in London,
in the year 1682.

[.embedded-content-document.letter]
--

[.salutation]
Sarah Banks, my eldest daughter,

Thou hast been near and dear to me ever since the day thou wast born,
with a godly care as a tender father,
that thou mightest be nourished up in thy young and tender years for thy preservation;
with many desires in my heart to Almighty God, that as thou grewest in years,
he would be pleased to make thee sensible and give thee an
understanding of those things which make for thy everlasting peace,
and the salvation of thy soul in the kingdom of glory, when time here shall be no more.

And now, dear child, the Lord having thus far answered my desires,
and enabled me to perform my care towards thee;
I have a further concern upon my mind for the good of thy soul;
which as thou art truly mindful of will tend to thy good,
and will never hinder thee of anything that is really needful for thee.

First of all I would put thee in mind, that God,
according to his Divine Wisdom and Providence, gave thee life and breath,
which thou oughtest to prize and value as mercies,
amongst many more thou hast received from him;
and thou art also come to an understanding in some degree,
how to behave thyself as a child of God, by the light and grace of our Lord Jesus Christ,
which he hath placed in the secret of thy heart, for a teacher to thee in all things.
My concern now is to stir thee up unto this by way of remembrance;
to be faithful and obedient to its requirings, whether more or less.

This light and grace of our Lord Jesus Christ, teacheth thee thy duty towards God,
to thy parents, and to all men and women.
It first teaches thee, to fear and love God, and to wait upon, worship,
and serve him with all thy mind and strength, that he alone by his Spirit,
manifested in and through Jesus Christ, may be thy chiefest love and delight.
It will teach thee as thou art watchful, to deny all ungodliness and worldly lusts,
to take pleasure and delight in meeting with God`'s people,
to worship him in spirit and truth;
so that thou mayest come more and more to have
unity and fellowship with his faithful children,
according to thy measure.

This pure light of the Son of God, teaches thee to be lowly minded,
sober and watchful over thy words, carriage, and behaviour, in thy life and conversation,
and to choose such for thy companions; and not those, who though they profess the truth,
are light, wanton, and high-minded, and follow the fashions of the world; and tattling,
and tale-bearing,
and meddling with other men`'s and women`'s matters which do not concern them.
Be sure thou be found only in what concerns thee, and well becomes thy place,
being a servant.

This is the way to grow in grace and saving knowledge, and to have the comely adorning,
which is the ornament of a meek and quiet spirit,
which in the sight of God is of great price; and is better than costly attire.
This is the way to be beloved of God, and his people, to grow up a good woman,
and to make a blessed and happy end.
This blessed way and course of life, my soul desires for thee, my dear child,
that thou mayest carefully live and keep in it, to the end of thy days.
Amen.

The light of Jesus Christ, which thus teaches thee thy duty towards God,
will also leach thee thy duty towards all men, women, servants, and children;
especially now in thy place where thou art a servant.
It will teach thee to be faithful, willing, and obedient to thy master and mistress,
in all things which are meet and convenient;
to be careful that nothing waste under thy hand, which is committed to thy trust,
nor otherwise; and to watch with an eye for good over all in the family.
If anything else appear, tell it not abroad to any whereby it may cause dissension;
but first tell the party in love, for so wouldest thou be dealt with.
This is according to the righteous law of God, which is light,
that teaches to do unto all as we would be done unto;
and when anything happens amiss with thyself, and thou art spoken to and reproved for it,
as Paul`'s counsel to Timothy concerning servants was, I exhort thee in tenderness,
murmur not, nor answer again, except it be to say it shall be amended.

My dear child, the desire of my heart is unto Almighty God,
that this my counsel and advice may be made effectual unto thee;
and that in the serious consideration thereof,
with honest desires raised in thee to perform and answer the same,
thy heart may be truly broken and tendered before the Lord,
and so kept in all lowliness and humility before him, unto the end of thy days.
Amen.

[.signed-section-closing]
So prayeth thy tender and affectionate father,

[.signed-section-signature]
John Banks.

--

This year I went to Ireland again, from whence I wrote the following letter to my wife:

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

In that which openeth my heart to the Lord, and maketh me truly tender before him,
am I at this time enlarged in tenderness towards thee,
with our dear children and servants, desiring to the Lord,
that by the same power thy heart may be kept open in tenderness before him,
that thou mayest increase more and more; that so we may have a sense one of the other,
of our growing up together by the living virtue
that springs out of the root which bears us;
for as our habitation and dwelling is here, though our work and service be not one,
because of the diversity of the gifts given us,
yet we grow up together as do all the faithful in Christ Jesus.

The Lord preserve thee in his fear, and guide thee in his wisdom,
that thou mayest be a good example before thy children and servants,
being careful to train them up in the same fear, to walk as becomes truth in all things;
always having a tender regard over them, chiefly for the good of their souls,
as well as their bodies; for many opportunities in mercy thou hast,
wherein thou mayest do good unto them, which I have not.
So, my dear, be concerned for their good as they grow up in understanding,
for they are quick and apprehensive enough (as many children in this age are),
who can quickly see if they be indulged in anything which they ought not to have;
and if we thus indulge them, we lose our dominion and authority over them.
Let our care be to reach to and have the answer of the witness of God in them,
even the witness of his gracious Spirit, which most of them have a sense of,
by which they know what they should do,
and what they should not and as this comes up in them and is minded,
it will make good children of them: and much lies in what examples we are before them.

Wherefore I am still more and more concerned in
my mind how to behave myself towards them,
to the end I may be found clear of my charge and duty concerning them,
especially for the good of their souls.
The Lord hath richly blessed us with them as manifold mercies;
but still there remains a great care and concern on our parts to be performed;
for want of which, I clearly see that many children who might bring honour to God,
his truth, and their parents are, on the contrary, a dishonour to all,
though they may have great possessions in the earth, and fulness,
ease and great preferment as it is called: but being lost from the Truth,
what serves it all for, though many look too much at that,
and neglect the weightier matters, which ought to be the greatest part of their concern.

And now, dear children, you may understand our care and concern for you;
therefore you that are come to this understanding, I admonish you as a tender father,
in the love of God, that you would put on this good resolution, and say,
How ought I to behave myself in all things, both in word and deed,
carriage and behaviour, as an obedient child, both to my dear father and mother,
who have such a care for my good and preservation every way;
and now especially to my mother, my father being absent?
And in order that you may all be such, now to her, and to me when I am present,
be ye all subject and condescending one unto another; live in love, quietness,
and good-will one towards another; and be sober-minded in the fear of God,
and keep out of all company but such as is sober.

And by no means be idle at any time, but give yourselves to some good employment,
such as your body and understanding is able to perform,
with a willing and ready mind to be assistant to your mother in her concerns,
and be careful to mind your books when you have time for it.
Read the holy Scriptures, and Friends`' books,
and be diligent in your course and order to keep to meetings,
weekday as well as first-day, that so the work of your hands may be made more easy,
sweet and comfortable unto you; that God over all, for all his blessings and mercies,
may have the praise, honour and glory; who is eternally worthy.

Peter Fearon, who was my servant seven years,
is now my acceptable companion in the work of the Gospel.

[.signed-section-signature]
J+++.+++ B.

[.signed-section-context-close]
Mount Melick in Ireland, the 23rd of the Fourth month, 1682.

--

[.asterism]
'''

[.blurb]
=== A relation of my imprisonment in the city of Carlisle in Cumberland, for six years and nine months, because for conscience sake I could not pay tithes demanded by George Fletcher, of Hutton hall, in the aforesaid county; a justice of peace, so called, but a great persecutor of God`'s people, by imprisonment and spoiling of their goods; and at the time of my commitment, all that he pretended was his due was but eight shillings and six-pence, which showeth his hard-heartedness and oppression.

In the beginning of the second month of the year 1684,
I was committed to prison at the suit of the said George Fletcher, impropriator,
because for conscience sake I could not but bear my
testimony against that great oppression of tithes;
being first subpoenaed, and afterwards arrested,
because in obedience to Christ`'s command I could
not put in my answer upon oath to his bill.
On the same day that I was taken to prison,
there came twelve men with a warrant from George Fletcher,
and distrained and took away seven pounds ten shillings worth of my goods,
for part of a fine of twenty pounds for a Friend in the ministry,
who spoke in our meetinghouse at Pardsay-Crag,
it being in the time of the penal act against conventicles.
The goods were sold by him, or his order;
and so much more taken from other Friends for the said fine,
as amounted to thirty-five pounds.

My imprisonment continued seven years, wanting three months,
when I was freed by King William`'s Act of Grace.

Here follows a true relation of the abuses and hard
usage that I with some of my fellow-prisoners,
have suffered from the jailer, George Lancake, and the turnkey, Alexander Richardson,
for no other cause than worshipping God in our prison-house;
and in obedience unto the Lord, speaking in his name, in exhortation and prayer;
and sometimes by way of warning,
that I was constrained to give to people as they passed by our
prison-window from their worship and at other times,
to turn to the Lord by a speedy repentance, and amendment of their ways.

On the 20th day of the fifth month, 1684, a little before the time of our meeting,
there being five more Friends prisoners with me, the jailer said to me,
that except I would promise him not to preach that day, he would take me away.
I answered, that I could not make him any such promise,
neither did I know before the time came that I should preach.
"`Then,`" said he, "`I have prepared another place for thee.`"
He took me by my arm, and led me along, and put me in a noisome, smokey room,
under which they brewed, and locked me in; where I remained three days and two nights,
without any bed.
So the first-day in the evening after I was put there,
the turnkey came and opened the door, and said,
his master sent him to bid me come forth and go to my friends; but I answered,
"`Go tell thy master I shall not come forth of this place to another,
until he fetch me himself who put me here.`"
He went and told him; and the jailer bid his man tell me again,
that I should stay there until I rotted before he would fetch me;
but I took no notice of that, knowing well what I did.
There were several prisoners in his house for debt,
who had wastefully spent most of their estates, who said,
"`the Quaker saith he will not come forth till you fetch him,`" meaning the jailer,
"`and you say he shall stay there till he rot before you will do it;
we will see who will get the victory.`"

That night and the next day and night passed over,
and the next day towards the evening came the turnkey again,
and told me his master had sent him to pull me out by force,
if I would not come willingly, that being the fourth time he sent him.
The turnkey was a lusty, strong, rugged-spirited fellow.
I being sitting, stood up before him, and said, "`If thou canst take me by force, do,
here I am,`" stretching forth my arms; so that he took me by one,
and pulled with all his strength, but he could not move me at all; and he wickedly said,
"`God bless me, I think the devil is in the man, I cannot move him.`"
"`Nay,`" said I, "`the devil is in thee,
and I am stronger through the power of God than both thee and the devil, go,
tell thy master that.`"

All this while I felt his master was in torment;
so he went and told him what he had done, and what I said; and said,
he thought I was as strong as twenty men,
for he could move me no more than if I had been a tree.
But in a little time after came the jailer himself to me, and said, "`What now, John,
what is the matter you will not come forth,
I having sent my man so oft to let thee go to thy friends?`"
I answered, "`because it was thy will and pleasure to lead me hither,
thou shalt also lead me back again, or here I intend to stay;
I shall be a true prisoner to thee, I shall not make an escape.`"
After some more words had passed between us, he took me by the arm, saying, "`Well,
come then, if nothing else will do, I will lead thee back again;`" which he did,
down the stairs through the court, to the door from whence he brought me,
and thrust me in, and said, "`Go thy ways, pray God I had never seen thy face.`"
And the prisoners for debt standing at his door, looking on while he led me,
laughed and said, "`The Quaker hath got the victory.`"

After this, for seven meetings together,
the turnkey haled me out into the jailer`'s house, being urged on by him,
with many threatening speeches,
charging his man not to let one of us go out at the gate of his court.

About this time I wrote to my wife as follows:

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

My love in our Lord Jesus Christ salutes thee, and all thine,
and Friends as though named;
the breathing of my soul is still continued unto the Lord for your preservation;
for we have cause to say,
the Lord hath never been wanting to us in the time of our greatest need,
to bear up our spirits with courage and boldness for his own name`'s sake;
and as we retain our integrity unto the end, he will be the same,
though greater may be our trials and exercises than heretofore.

Wherefore, let us go on our way rejoicing together; because the Lord is our strength,
through the greatness of his power,
who has not only counted us worthy to believe in his name, but also to suffer for it;
and though many hands and tongues be lifted up and bended against the Lord,
and his chosen and redeemed ones, in vain do they strive;
for the Lord hath determined to carry on his own work, in his own way,
and to finish it in his time, in despite of all Sion`'s enemies and opposers;
and to crown his faithful ones with dominion and victory.
So the Lord preserve thee, my dear, near to himself, in openness and tenderness of heart;
that thou mayest feel and receive of his divine comfort and spiritual sweetness,
in waiting upon him in the assemblies of his people;
and through the fresh virtue thereof, be kept living and tender before him; that so,
by his power thou mayest be preserved in and through all thy various exercises,
knowing that many are the trials of the righteous, but the Lord delivereth out of all;
and this is the comfort and encouragement of the righteous,
which makes them bold and valiant for the truth upon earth.
I am well, with all my suffering brethren,
notwithstanding the rage of the wicked still continues against us;
and no greater joy and comfort I have in this world,
than to know that thou and all thine are well, both in body and mind.
In the Lord`'s time all things will be well.
Though I could be glad to see thee here, do not straiten thyself in any wise,
for I am truly content to bear it, if it were much more,
considering thy concerns in this season of the year, being harvest time,
and the journey so long.

[.signed-section-closing]
So farewell in the Lord.

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
From the prison in Carlisle, the 12th of the Sixth month, 1684.

--

Upon the 17th day of the sixth month, being the first-day of the week,
we were met together to wait upon the Lord our God with all our hearts,
whose power and presence, to his praise and glory be it spoken,
was daily manifested amongst us; the turnkey, who now always watched when I spoke, came,
according to his wonted manner, and took me away to his master`'s house.

The jailer`'s rage and cruelty began to rise to a greater height than before;
and the bad tree to bring forth corrupt and bad fruit more abundantly,
as his corrupt words, wicked speeches and actions hereafter testify.
After I had been in his house some time, he began to break forth in a rage, and say,
that we were all rogues, and rascals, and cheating knaves,
and the common jail was too good for us; nay,
if he could get us into the house of office, he would put us all there,
being then in number sixteen.
However, he said he would put six of us who were in one room into the smokey loft,
and the rest into his barn, and we should lie there like sheep in their pens.
He charged the turnkey not to let one of us go out at his gate,
no not to buy our own victuals or what we had need of,
which his man pretty strictly observed;
so that we were put to it to get one to bring such things to us as we had occasion for.

About this time William Johnson, a Friend, a prisoner, said to the jailer,
"`Seeing thou so straitenest us of our liberty,
that we may not go forth to buy our own victuals,
thou shouldest get us somebody to do it for us:`" he said he would get us none,
and if one of us durst go out at the gate, he would drive us in again,
as the thieves were driven to the gallows.

Upon the next sixth-day, being the 22nd day of the month,
we were met together in the fear of the Lord in the prison-house,
and our friend John Carlisle amongst us, he being an inhabitant of the city.
In our waiting upon the Lord he did powerfully appear amongst us as at other times,
and our friend John Carlisle had his mouth opened,
with some words of comfort to Friends in suffering.
But on a sudden the turnkey came and haled him away, and turned him out at the gate;
but he came in again, and spake some words to the jailer,
to warn him to beware what he did; but the jailer pushed him on the breast with his fist,
insomuch that the jailer`'s wife asked him if he was mad.

In a little time after the turnkey had haled our Friend John Carlisle away,
the spirit of supplication came upon me, and in obedience thereto,
I besought the Lord for my own preservation, with the rest of his suffering people.
Then came the turnkey and pulled me off of my knees, being set on by the jailer,
who bid him pull me out by the ears;
and stood at the stairs`' head with a staff in his hand, we being in an upper room,
and when the turnkey brought me to the stairs`' head, the jailer said,
throw him down head foremost and he will be sooner at the ground,
and thrust me with his staff, setting it on my ribs, while the other haled me.
They put me in the old smokey room,
and there kept me until some time after the meeting was over, as their manner was;
and in the meeting some time after they haled me out,
our friend William Johnson spoke a few words of exhortation to Friends,
and the turnkey came and haled him away into another room in the jailer`'s house.

Two meetings after, the turnkey haled me out and abused me much,
sometimes putting my hat over my face when I was declaring the truth,
and setting up a hooting noise to drown my voice,
that people in the street might not understand; at other times coming behind me,
and clapping his hands upon my mouth to stop me from speaking, but could not.

Upon the 26th day of the same month,
we being met together to perform our duty unto the Lord,
a necessity came upon me to pray to him; and so with his people then present,
we fell down upon our knees together.
In a little time after came both the jailer and the turnkey, and the jailer said,
"`Pull him down;`" so he pulled me down from off my knees,
along the floor by one of my arms, but said he could not get me along,
and the jailer said, "`Trail him,`" but he could not get me trailed to the other`'s mind;
and so the jailer took hold of me in great fury, by the same arm the other had hold of,
and both dragged me along the floor, out of the door, down the stairs,
into the old smoky room again; and when I was at the stairs`' foot,
these words rose in my heart, which I spoke to the jailer:
"`It had been better for thee thou hadst never taken this weapon into thine hand,
to fight against God, his truth and people;
for the time will come upon thee which thou canst not resist,
that it will turn with trouble and pain into thy own bowels.`"
To the truth of which, several times he hath since confessed.

About this time, upon the first-day of the week, the then mayor, John How, and aldermen,
with the chief priests, there being a great many of them belonging to the city,
with several of a persecuting spirit, being greatly enraged against me,
because I was often constrained to sound truth`'s
testimony in their ears as they came from their worship,
I being in their view, the casement of our window opening to the street,
came into our meeting in our prison-house, when I was engaged in testimony for the truth;
and the mayor in great rage bid me be silent, often shaking his staff at me,
threatening what he would do to me for preaching there, and disturbing all the city,
in contempt of authority.
I seemed to take no notice of him for some time,
that so he might manifest himself the more.
He being a very passionate man, said, if I would not be silent, he would stop my mouth;
then I answered and said, "`The Lord hath opened my mouth, and he,
and all the assistance he could get in the city, could not stop it.`"
He said he would put a gag in it, and put me in the common jail,
and I should preach there to the walls.
I said, "`I fear neither thee, thy gag, nor the common jail;
for though thou art the mayor, thou hast nothing to do to meddle with us,
we are the king`'s prisoners and in safe custody, and here is our keeper,
pointing at the jailer, he being present,
so thou mayest go about thy own business;`" with which he was silent.

Then one of the aldermen said to me, he could prove I had nothing to do to preach.
I asked him, "`how he could prove it?`"
He said, "`by the Bible;`" I bid one reach him a Bible quickly.
Another alderman said to him, "`Let him alone, sir, you will do no good with him,
you may as well speak to the wall.`"
So he failed of his proof,
and with some threatening words they all went away and troubled us no more.

At times the jailer would seem to flatter me, to see what he could do that way,
and would say, "`Thou seest the mayor and aldermen of the city,
with the priests and many others are set against me, because I suffer thee to preach,
and say they will fine me, and that your meeting is a conventicle;--if thou wilt preach,
canst thou not preach in another house off from the street,
or go to the other end of this house, it being a long one;
will no place serve thee but just before the casement?
I said several times to him upon this account, "`I take no notice of thy flattery,
no more than of thy threatenings, neither can I go to another place at thy request,
nor theirs; put me where thou wilt, as a prisoner I shall be true and subject to thee,
but in what is required of me in obedience to the Lord,
in that I am resolved in his name and fear to stand faithful in my testimony for him,
in doing or suffering;
not regarding or fearing what either thou or any of
these persecutors shall say or do to hinder me,
notwithstanding thine and their cruelty and threatenings; for the Lord my God,
in whom I trust, and for whose cause I suffer, is my preserver.
I can well remember, and have good cause so to do, that above twenty years ago,
I was put prisoner into the common jail in this city, for praying to Almighty God,
and being met with his people, and also fined and goods distrained for it;
and the Lord endued me with strength to suffer all with joy and gladness.
And thinkest thou I will play the coward now, after so many years?
Nay, nay, blessed be the name of the Lord for evermore!
I am grown so many degrees stronger in faith and patience,
through the might of his power, that I hope and believe upon good ground,
I shall be enabled to endure whatsoever thou, and all who are like minded with thee,
shall be suffered to impose upon me; so never let it enter thee,
to think thou shalt prevail over me, either with flattery, threatening, cruelty,
or the common jail.`"

After which he said to some of the aldermen, in discourse with them about me,
"`I have used all the endeavours I could hitherto, to put yonder man to silence,
but I cannot.
I know no way that it can be done, but one, and I dare not do it.
Except his mouth be sewed up, I dare say he will never give over preaching.`"

And for four meetings after this,
came either the jailer or turnkey and haled and abused me,
and put me in some other place, until after the meeting was over;
and through the jailer`'s cruelty and abuse, my body was bruised and my health impaired.

On the 13th day of the seventh month,
our friend Peter Fearon being come to visit the prisoners,
we sat down together to wait upon the Lord,
and after some time Peter Fearon went to prayer.
But in a little time came the turnkey in a great rage, and asked our friend,
"`Where earnest thou from?
Come away!`"
And so fell to pulling him in a most cruel manner; taking him by the cravat,
and threw him back into a bed, and said, he would either hang him,
or pull out his throat; still shaking and pulling him by his cravat, or neckcloth,
dragging him out of the door into the jailer`'s house,
with curses and oaths what he would do to him.
For which I reproved both the jailer and turnkey sharply;
so that in a little time they let him go.
This day I wrote to my wife and children, the following letter.

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

Thou art truly so to me, even so near that we are truly one,
to help to bear each other`'s burdens,
sympathize and be truly concerned one for the other`'s preservation,
both at home and abroad, in prison or at liberty, in sickness or health;
not only for the body, but for the eternal happiness and wellbeing of the soul.
This is the right concern of husband and wife who are truly joined together,
and who are come to know the true marriage, which is God`'s joining.
Oh, how this helpeth and strengtheneth, encourageth and beareth up,
in the time of the greatest exercise.

The Lord, who knoweth my heart,
knows how often in my confinement I have been under a serious
consideration of thy condition with thy weak family,
as to outward things, with a cry unto the Lord,
in the supplication of my soul on thine and their behalf;
that thou mightest be preserved with them in health and strength,
for the managing of thy affairs.
And surely thy soul may say with mine.
The Lord hath heard and answered--He hath been good and gracious unto us herein;
that we can say, things on that hand are well.
And so with humbled hearts for the same,
let us bless and praise his holy and worthy name, and have his mercies, blessings,
and favours, in continual remembrance;
for surely the Lord hath a secret ordering hand in those things; and if,
in his fear and true faith, it be minded, he gives us to see,
and makes us witnesses also, that he can and doth bring things to pass,
far beyond what can aforehand be seen, or expected.

And now, my dear, as to my present state under suffering, it is well,
though I am not altogether so in body, yet in the Lord`'s time I hope I shall be so.
I say it is well, though my condition be what it is;
for I am well assured that it is according to his will,
in performing which I have great peace and satisfaction,
although the wrath and cruelty of ungodly men are still much bended against me;
but I believe it will not be long, until the Lord by his power will bring them down;
for I see, in the light of the Lord,
their strength grows weak and their expectation concerning me begins to fail.
Howbeit, whatsoever the Lord may yet suffer them to inflict upon my body,
I count all that may be endured or passed through here, but light affliction,
because of the evidence and assurance of that far more exceeding weight of eternal glory,
which I have in view, through faith in Jesus Christ,
and am travelling in the way that will bring to the everlasting possession thereof.

And so, my dear,
let us freely and faithfully follow those things which will
make for our everlasting peace and joy with the Lord;
whereby we may have the full assurance of the salvation of our souls,
in the kingdom of happiness and glory, when time here shall be no more,
whatever we enjoy besides in this world; for be it more or less,
as we are truly content therewith, it will be sufficient.
The Lord giveth and taketh away, or suffers it so to be,
according to his good will and pleasure, blessed be his holy name,
and reverenced be his glorious power, now, henceforth, and for evermore.
Amen!

And now, my dear children, concerning whom my heart is often tendered,
my bowels yearn for your preservation from evil,
and that you may grow and increase in all that is good;
give ear every one of you and take good notice what I have to say unto you.

John, my son, and dear child, "`God in his love, according to his Divine wisdom,
hath given thee a measure or manifestation of his good spirit, grace, or light,
which he hath placed in thy heart and conscience,
as a witness against every appearance of evil:
this in some degree thou art come to the knowledge of;
whereby thou knowest thou shouldest do that which is good, and eschew the evil.
This light of the Lord Jesus Christ, teaches thee not to be wild or wanton,
or given to any idle talking, or unsavoury words;
and if thou shouldest do or act contrary,
this pure light will reprove and judge thee for it.
This is that, my child, which thou must own and love;
and then it will not only discover all sin, and every evil to thee,
but as thou takest heed to its checks, reproofs, and manifestations,
thou wilt receive power over those things, one after another,
which the light makes manifest unto thee, to avoid all light and airy company,
and to have thy mind kept in the fear of God, to serve him.
Above all love the truth, and those who are in it; and love to go to Friends`' meetings,
and delight in their company;
so wilt thou come to be weaned from every appearance of evil, and to be sober and solid,
as becomes the truth.
This is thy duty towards God, be careful to be found in it;
and as thou art found in the performance of this,
the pure light and grace of our Lord Jesus Christ,
which teacheth thee thy duty towards God, and how to obey him,
will also teach thee thy duty to thy parents, and in particular to thy dear mother,
and also to thy sisters and brother.
Thou being the eldest at home, I expect thy care and diligence herein,
in love and tenderness to thy dear mother,
that so thou mayest be a strength and help to her, now in my absence.
I charge thee look to it, as thou expectest a blessing from the Lord,
and my favour and countenance.
Also be careful that there be no strife between thee
and thy sisters and brother upon any occasion,
neither in words nor actions; but be tender and loving one to another,
and be sure you all keep to truth`'s language, Thee and Thou, to every single person.

And now to you Ann and Mary, my daughters and dear children, whom I dearly love,
with all the rest; be sure you speak no ill one of the other, nor do ill to any body,
carry no tales from one house to another; and when you are sent on an errand,
go and come quickly; and be loving, kind, and respectful one to the other,
and to your brethren, sister and servants; and help one another willingly in all things,
but especially your dear mother;
be dutiful and obedient unto her in all things what she bids you do, I charge you,
do it readily and willingly, without murmuring.
My dear children, keep these my words in mind daily,
that you may all serve one another in love.

And to you, little William and Emme, the youngest.
My dear children, be sure you love one another;
do not fall out by the way when you go to school, or in coming home; do no hurt to any,
and mind your books well that you may be good scholars.
Be sure you remember what I say to you,
and above all things be careful to do what your mother bids you,
and to love your brother and sisters.
Dear children, all of you mind your books; read the holy Scriptures;
and the Lord bless and preserve you all, in love, unity, peace, and quietness; fearing,
serving, and loving God with all your hearts; and then all will be well.

I find a great alteration in my body,
because of the cruelty and hard usage of the jailer, and his turnkey;
together with the want of the fresh air;
for I have had no liberty to walk abroad these several months,
and the jailer doth not suffer me to speak or pray in any meeting, after he hears me;
for which, the Lord will assuredly meet with him by his judgments.

[.signed-section-closing]
I am thy loving husband, dear wife, and your tender father, dear children,

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
From my prison-house, in Carlisle, the 13th of the Seventh month, 1684.

--

On the 15th of the same month, in the evening, came the jailer,
and ordered Thomas Hall and myself to the common jail,
because we could not answer his unreasonable demands;
howbeit there was not room in the common jail,
for it was wholly taken up with poor debtors and thieves.
I having been sick for some time, and not well recovered, a Friend said to the jailer,
"`If this our friend die through thy cruelty and hard usage,
his blood will be required at thy hands.`"
He answered, he did not care if I never stood upon my feet again,
he would put me in the common jail.
I asked him, if the place was fit for us to be put in; especially I, not being well.
He said, it was such as he had for us, and we might either sit or lie as we could;
and if there was not room for us to lie one by the other,
we might lie one above the other; and if there was not room elsewhere,
we might go into the sink, a nasty, stinking hole, filled up with filth and straw;
which fulfils that saying, "`The mercy of the wicked is cruelty.`"

Accordingly, he put us two among the debtors, in the common jail,
where there was no convenient room either to sit or lie;
and we were forced to sit in our clothes all night by the sink;
but next day the jailer caused a poor debtor to be removed to his house,
where he lodged him.
Then we got some straw and bedding to lay on the ground, which was very raw and wet,
in the debtor`'s place, and got stones for our bedstock, head and feet;
where we were for the most part locked in day and night,
for thirteen days and nights together.
And notwithstanding the weakness that attended me when I was put there,
and the nastiness of the place,
the Lord was pleased to make it as a place of healing
and restoration of health and strength to me;
so that when the jailer took me from that place again,
as I was going down the street to the place from whence he took me,
many people coming forth to look upon me, several said,
"`He looks better than he did when they put him into
the common jail,`" which was cause of rejoicing to me;
praises, honour, and glory, be given to the most high God, who by his own healing,
restoring, preserving power, can bring to pass whatsoever seems good in his eyes!

One passage more is fit to be taken notice of,
to set forth the cruelty and hard-heartedness of the jailer.
My dear wife, with other Friends, coming to visit me in the common jail,
which was above twenty miles from my own house,
she desired the jailer that he would do so much as suffer me to come out of the jail,
to some other place; but there being no compassion in him,
he would not suffer me to come forth to her; but sent word by his turnkey,
that if she would be with me, she might in the common jail but no other place;
where she did contentedly abide with me until the next day,
rather than leave me and go to a better place.

One time when I was doing some work in the common jail,
the jailer came to me and said mockingly, "`John, thou hast scarce light to thy work,
(there being very little light in the prison,) but what matter,`" said he,
"`thou hast light enough within.`"
I answered, "`Yes, blessed be the Lord my God for ever, so I have,
but thou hast little of it; for if thou hadst more,
thou wouldst see thy way better what to do, than thou now doest.`"
So he turned from me and said no more, but took my fellow prisoner, Thomas Hall,
away from me at the end of thirteen days, and kept me there three days and nights more,
and then removed me as aforesaid.

When the jailer saw that all his contrivances would not effect his purpose,
to make me bow, and to get chamber rent of us;
and being troubled in his conscience both day and night, as afterwards he confessed,
slavish fear mixed with cruelty still attended him.
So he betook himself to a new-invented shift,
to hinder the sound of truth`'s testimony borne by me, from reaching the people`'s ears.
About this time I wrote the following paper:

[.embedded-content-document.paper]
--

[.blurb]
=== To the inhabitants of the city of Carlisle; but more especially to such as cannot endure to hear the sound of a man`'s voice, though in prayer to the God of heaven, or in exhortation to his fellow-prisoners or others to love and fear God, and walk before him as becomes Christians; and yet can endure to hear men and women curse and swear, without reproof or punishment; and suffer drunkards to stagger and reel in the streets, with curses and oaths; which I have often seen and heard to the grief of my soul, since I came a prisoner into your city.

Under the consideration whereof,
a necessity attends me to put you in mind what you have been and are doing,
if happily you may come to see the evil you have done, and repent and amend;
because we must all give an account unto the Lord, of the deeds done in the body,
whether good or evil.

What evil have I done, or what law have I transgressed, either against God or man?
Show me, if you can, and let it be known to people abroad,
what great crime I have committed; or why I have been and am so abused;
even such abuses as never were done, I presume, to any prisoner in this city before,
either by jailer or others.

I say, what is the cause, why I have been and am now, so threatened and abused,
being kept close prisoner in the common jail?
Is it for praying to God, or exhorting one another, or warning people to repent,
that the jailer hath been so threatened, and charged to take a course with me?
who accordingly often hath abused me, also his turnkey, sometimes one,
and sometimes both; pulling and haling me off my knees when in prayer to God,
both of them at one time taking me by the arm, throwing me down,
and dragging me along the floor; threatening sometimes to throw me down the stairs.
And yet thieves and robbers, and other evil-doers,
have had liberty to worship in their way, without disturbance.

Why are your ears so shut, and you so troubled at the sound of truth,
while your ears are so open to the contrary?
Read the Scriptures, and judge yourselves,
wherein you are short of a true Christian`'s practice under the Gospel dispensation;
which never was to persecute and imprison for worshipping God.
Read Psalm 58.
1 to 5; and whether you are not such, who are said to be '`like the deaf adder,
that stoppeth her ear and will not hearken to the voice of the charmer,
charming never so wisely.`'
'`Do your ears hear reproof, or do you hate reproof, and refuse instruction?
Consider your states and conditions what they are?`'
'`Be not deceived, God is not mocked, such as every one of you sow, such shall you reap.
They that sow to the flesh, shall of the flesh reap corruption;
but they that sow to the spirit, shall of the spirit reap life everlasting.`'
What must you reap, think you?
When will it enter into your hearts to consider, you who daily sow lying,
swearing and drunkenness, whoredom and pride,
which are grown to that height in your city, as though they should win it the crown.
'`But woe to the crown of pride, for it must be plagued.`'
'`And though hand join in hand, the wicked shall not be unpunished.`'
'`Though your brows be like brass, and your necks as iron sinews,
and though you walk with stout and lofty looks, and tinkle with your feet as you go,
the Lord can break and bow you, and turn all your songs into mourning,
and your pride and vain glory, sport, pleasure and pastime,
into howling and bitter lamentation, which he assuredly will do, except you repent,
and amend your doings with speed, before it be too late.`'

Oh! why should people`'s ears be so shut against that which is good,
and so set and bent to hear and do that which is evil; to believe lies rather than truth.
Search the Scriptures, and read in fear and with understanding: Prov. 17:45.
'`A wicked doer giveth heed to false lips,
and a liar giveth heed to a naughty tongue.`' Jer. 5:21-22.
'`Hear this, O foolish people, and without understanding,
which have eyes, and see not, ears, and hear not.`'
See Matt. 28:11 to 14; who was it there,
whose ears were more desirous to have lies told them than the truth,
though by those who were ear and eye-witnesses?
Was it not the chief-priests and elders, who did what in them lay,
by holding a counsel together,
to keep the truth of Christ`'s resurrection from the governor`'s ears;
or if it did come to his ear, to endeavour to persuade him with lies?
Let search be made amongst you, and examine yourselves,
and see whether there be not such chief-priests and elders,
who do what in them lies to hinder the truth from coming to people`'s ears,
or to persuade them not to believe it.

And see Acts 7:51-52, who were the stiff-necked, Stephen testified against;
whom he calls uncircumcised in heart and ears?
For it is said, they stopped their ears, and ran upon him with one accord,
because he spoke the truth to them; and for the true testimony he bore,
they stoned him to death.
Read to the end of the chapter, and there you may find your examples, you stoners,
who have thrown stones at us, and at our prison windows, for no other cause,
than speaking the word of truth unto you, in love to your souls.
And in Acts 17:18 to 20, see who it was in the city of Athens,
that called Paul a babbler, or base fellow, a setter forth of strange gods;
for no other reason, but because he preached Jesus and the resurrection,
calling it a new doctrine, and said,
he brought strange things to their ears (and yet true,) but they liked not to hear it;
and so some of them mocked, and others said, '`We will hear thee again of this matter.`'

Now all people search the Scriptures and see with the light of Jesus Christ,
'`The true light,
which lighteth every man that cometh into the world;`' of what kind your deeds are:
for Christ saith, '`This is the condemnation, that light is come into the world,
and men love darkness rather than light, because their deeds are evil;
for every one that doth evil hateth the light, neither cometh to the light,
lest his deeds should be reproved; but he that doth truth cometh to the light,
that his deeds may be made manifest, that they are wrought in God.`'

I say unto all you in whom there are any living desires and
breathings to come out of the broad way that leads to destruction,
where many go and walk, come into the narrow way, which few find.

Consider in the fear of the Lord, what manner of lives you live,
and what fruits you bring forth, and see if the light of Christ, the spirit of Truth,
the faithful and true witness of God, his grace or word nigh unto you,
placed in your hearts and consciences, does not condemn you;
and if your hearts condemn you, God is greater; but if your hearts condemn you not,
then have you confidence towards God.

If any say, If I should believe in this light, grace, word nigh, witness of God,
or spirit of Truth, which are all one, what will it do for me;
for some say it is but a natural light?
I answer; It is a teacher in the heart and conscience,
'`teaching to deny ungodliness and worldly lusts, and to live soberly, righteously,
and godly in this present world.`'
Mark, not ungodly or rudely, as many do.
This the light of Christ, the grace of God, the spirit of Truth, will do for thee,
if thou lovest it, and believest in it: when thou art tempted to sin,
power from God will be given unto thee, through it, which thou hast not of thyself,
to overcome the wicked one in his temptations; for it is no sin to be tempted,
but the sin is, to enter into the temptation.
Thus power is given over the temptation, and so over sin;
one temptation and sin after another is gradually overcome;
for as many as believe in him,
who said '`I am the light,`' to them he gives power to become the sons of God.
He redeems them out of the state of the sons and daughters of the first Adam,
who is of the earth earthly,
into the condition of the sons and daughters of the second Adam, the Lord from heaven,
the quickening Spirit who never fell, (1 Cor. 15:45-47) who says, '`Behold,
I stand at the door, and knock; if any man hear my voice, and open unto me,
I will come in and sup with him, and he with me.`' Rev. 3:20.


Is not He at the door of your hearts, to call you to repentance, by his light, grace,
and holy Spirit?
And if there be not a believing in him by obeying the same,
what availeth his death and suffering to you,
and the shedding of his precious blood for you, if sin be not finished here,
and transgression put to an end?
Eph. 5:5, and read to the 21st verse.
'`No unclean thing can enter into the kingdom of Christ and of God.`'
Did not he suffer for the sins of all, that all through him might believe?
'`and they that believe not, are condemned already.`'

Was not sin the cause wherefore he suffered; and if the cause, through faith in him,
be not taken away, how shall the effect cease?
but if the cause through faith in him be taken away, then the effect ceaseth,
and everlasting felicity, world without end, ensueth.

So all people, in tender love to your souls, I exhort you, while you have time,
to prize it and make good use of it;
seriously consider what effects your faith and belief in Christ have wrought,
in order for your salvation and freedom from sin, that always separates from God;
for as saith John, '`This is that which gives victory over the world,
even your faith;`' and if your faith be not such,
ye cannot come to know the victory over the world, and the evil that is in it.
Let none think that the name of a Christian will save him;
for to have a Christian`'s name, and yet to be found in the practice of the heathen,
does not make a Christian.
It is the life and practice of Christianity, lived in, through faith in Christ,
that makes Christians, and not barely saying you believe;
which life and practice is a '`life of holiness, without which none shall see the Lord.`'

Now to the faithful and true witness of God in your hearts and consciences,
that will either accuse or excuse, I commend these things,
to be weighed and truly considered by you in moderation and the fear of the Lord,
as becomes Christians, and what manner of life, conversation, and practice,
is found amongst you.
'`Know ye not,`' saith the apostle, '`that to whom ye yield yourselves to obey,
his servants ye are, whether of sin unto death, or of obedience unto righteousness.`'
For when the book of your conscience comes to be opened,
with that other book which is the book of life;
according as your deeds and actions shall be found therein, so shall your reward be:
in which day of general resurrection,
we must all appear before the tribunal of God`'s glory and judgment seat,
to receive the sentence, either '`Come, ye blessed;`' or '`Go, ye cursed.`'

From one who truly wisheth and desireth the welfare and
preservation both of the bodies and souls of all people;
and hates nothing but the evil in any;
and yet am a sufferer in outward bonds for the
testimony of Jesus and of a good conscience,

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
Given forth in the common jail in the city of Carlisle, Cumberland,
the 30th day of the Seventh month, 1684.

--

The sixth day of the week, and also the first-day following,
being the 3rd and 5th days of the eighth month,
so soon as the jailer perceived we were met together, being thirty-eight prisoners,
he sent his turnkey to take us all away, one by one,
and put us in a back room to have our meeting, and then let us go to our places.
But growing weary of this work, the sound of my voice still reaching to the street,
he sought out a place in the city to his mind; and removed both himself and us,
and placed us in rooms back from the street, in a court enclosed with gates,
which he ordered to be shut when our meeting began, especially on the first-days.
Since we were so removed and placed, we have enjoyed our meetings pretty peaceably,
both as to the jailer and the rest of the city; and gained our freedom and liberty,
not only in prison and in and about the city, but at times to go home,
far beyond what could have been expected; praises, honour,
and glory for evermore be unto the Lord our God,
who never leaves nor forsakes his people, that stand faithful in their testimony for him.
He by his great power is with them, to uphold and preserve them;
and also in his own time to work their deliverance,
and to give them dominion and victory over all their enemies;
endless praises over all unto him who rules and reigns for ever and evermore.
Amen!

After I was liberated by the act of grace,
I travelled in the work of the ministry into the West of England,
where I wrote the following letters to my wife and children.

[.embedded-content-document.letter]
--

[.salutation]
Dear wife, together with my dear children,

My heart being open in the love of God, in a living remembrance of you all,
as at many other times, when my supplications are put up unto the Lord for his people;
I could do no less than write a few lines to express how I am
concerned for your growth and prosperity in the truth,
every one in your several measures.

The Lord beget and increase love in your hearts to him, and one towards another;
that therein you may feel life and true tenderness to spring afresh in your souls,
as a testimony that you are kept near unto the Lord,
in an inward waiting and dependance in fear before him.
It is these who are kept near unto the Lord in their hearts, who are living, fresh,
and tender;
for he causes his heavenly rain and gracious showers to be poured forth upon them,
and the springs of life to bubble up in them, that they are made to say,
What manner of love is this,
wherewithal the Lord our God hath loved us! and what manner of persons ought we to be,
in all holy life and conversation?
to the end that we may live and die the death of the righteous;
that so it may be well with us, when time here shall be no more.

[.salutation]
Dear children,

Carefully mind the performance of your duty towards God daily, fearing and obeying him,
in what you know of him by his light and grace in your hearts, be it never so little;
for as you are faithful in the little, the Lord will make you rulers over more.
And as you thus come to know a growth and increase,
you will also come to understand what it is to have heavenly treasure in earthen vessels;
which is far better than earthly riches and worldly glory, with strife and contention.

Truth prospers very much hereaway;
great desires are begotten in many people after the way thereof;
meetings are full and large almost everywhere in the counties, where I have of late been,
and in Somersetshire, Dorsetshire, Devonshire.
It was thought there were near a thousand people at the meeting at Spiceland,
where I was yesterday; yea, the work is great here,
but the labourers are very few among themselves.
Oh that the Lord would be pleased to fit, prepare, and send forth more!
I hope I may say, and exclude all boasting,
The Lord hath been pleased to make my service not only acceptable to many,
but effectual to answer the end wherefore he hath sent me;
so that my travel and exercises are made very sweet and comfortable unto me,
and Friends`' love, tenderness and respect are towards me,
being glad to see me after my long imprisonment;
and I have had blessed heavenly times among them.
All which considered greatly bows my spirit, and lays me low before the Lord.
I have had five or six meetings in a week.
My companion left me about three weeks ago, having something upon his mind for London,
and I being not yet clear of this county,
and feeling a concern upon me for some counties more,
I do not see that I am likely to reach the Yearly Meeting at London this year,
though I must go there before I return home; but when,
I cannot give any further account at present.

[.signed-section-closing]
Farewell, my dear.

[.signed-section-signature]
John Banks,

[.signed-section-context-close]
From Spiceland, in Devonshire, the 25th of the Third month, 1691.

--

[.embedded-content-document.letter]
--

[.salutation]
My dear heart,

It is with me to say unto thee and thine,
that the sacrifice of a broken heart and a contrite spirit the Lord accepteth,
and never did nor will despise,
though offered with sighs and groans that cannot be uttered.
In this the Lord keep and preserve you all;
which is the way to grow in grace and saving knowledge,
and to receive a blessing from his hand, which enricheth the soul,
and is better than all earthly enjoyments, which are but for a moment.
Surely methinks I am always with you,
in travail and concern of mind for your preservation every way,
as I hope you are with me, in my travels and various exercises both of body and spirit,
which the Lord hath been pleased to make sweet and comfortable unto me;
and I believe hath also blessed my endeavours and labour of
love for the good of many where I have travelled.
It is the great rejoicing of my soul to see the work of the Lord prosper,
which he is hastening in the earth, for his own seed`'s sake:
blessed are all who answer him by obedience when he calls,
and in faithfulness continue unto the end; unto which, with my own soul,
the Lord preserve you all.
Amen!`"

--

[.embedded-content-document.letter]
--

[.salutation]
Dear Wife,

By these, thou with all thine, and Friends, may know that I am well every way;
high praises unto the worthy name of the Lord for ever!

I came to this city the last sixth-day, and have had five meetings since; in all which,
the Lord was pleased to appear effectually by his power and life-giving presence.
Meetings here are very full and peaceable,
and many people have great desires after the truth.
Oh! that those who have long made profession thereof,
may be found good examples in their places, so as to answer the testimony of truth,
and the witness of God in people`'s consciences,
which would greatly tend to further his work,
and cause truth to prevail more upon people; which the contrary hinders;
wherefore blessed are the faithful.

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
London, the 9th of the Fifth month, 1691.

--

The above is the last letter I wrote to my dear wife, Anne Banks.
She died the 2nd day of the tenth month, after the date of the aforesaid letter,
early in the morning; and was buried the fourth-day after,
in the burying-place of Friends at Eglesfield, in Cumberland.

We lived comfortably together many years, and she was a careful industrious woman,
bringing up her children in good order as became the truth, in speech, behaviour,
and habit; a help-meet and a good support to me in my travels,
always ready and willing in truth`'s service; and was never known to murmur,
though I often had to leave her with a weak family,
notwithstanding the exercises in many affairs she had to pass through.
She was well beloved amongst Friends and her neighbours,
several hundreds of whom were at her burial.

In the time of her sickness she was very patient and content unto the last,
being sensible of her inward condition and end; telling me she must leave me,
that it was well with her, and that it would be well with her for ever.

She also said she hoped I would be, as I had been,
a careful and tender father to her children, who were dear and near to her.
And in some time after, ended her days in peace with the Lord;
and I am well satisfied of her eternal well-being.

Though our separation by death was the greatest trial I ever met with,
yet the Lord in whom I trust, was and is my preserver,
in that and many other deep trials and exercises;
to whom I am deeply engaged in all humility, to give the praise,
and return him honour and glory, who is God over all; blessed for ever.
Amen!

I have used much brevity in respect to many of my journeys and exercises,
not being willing to make a great volume; it remains to be noticed,
that often I have visited Friends`' meetings from Cumberland to London, and in London,
and into the West of England, in my way thither and home,
both before and after the Yearly Meetings; and in many other journeys beside,
from the year 1688, to the year 1702.

This year, going to London to the Yearly Meeting,
I sent the following letter to my children.

[.embedded-content-document.letter]
--

My dear love in the truth, is hereby remembered unto you and Friends;
by these you and they may know that I am well, with your brethren and sisters.
I am in haste, being the tenth hour at night; and I with seven Friends from Ireland here,
take our journey towards Chester early tomorrow, if the Lord will, for that nation;
and therefore have not time to write to you what I desire.

We have had a long and tedious time with that contentious man, George Keith,
for several days together; he is of a very turbulent and troublesome spirit,
vexatious to the church of Christ; but the power of God, for all his quarrelling,
is over him, and the life of our meeting run in one channel,
to set the judgment of truth upon his head; for it was clearly made manifest unto us,
in the light of the Lord Jesus Christ,
that he was not only gone into and entertained the spirit of division and separation,
but of envy and deep deceit; by which he warred strongly,
to prove Friends in the ministry to preach false doctrine, and himself the true,
chiefly about the body of Christ, and the light within.
But by the unruliness of his spirit, and the darkness that he is gone into,
he hath so manifested himself, that all his enticing words could take no place with us.
The Lord preserve Friends in the innocency and simplicity of the truth,
where is true unity, peace and safety from the destroyer; for wit and wisdom,
in the strength of man`'s reason, darken and stop the springs of life.

[.signed-section-closing]
Your loving father,

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
London, the 8th of the Fourth month, 1694.

--

I travelled through the nation of Ireland five times;
and once from Carrickfergus to Dublin, being the first time, though I omit,
for brevity sake, to mention how I travelled from place to place,
and the length of time and number of miles.
I also travelled in Scotland and there visited the people of God, and in the Isle of Mann.

While I was in Ireland, I wrote the following letters to my children.

[.embedded-content-document.letter]
--

The love of God unto you hath been such, as to give you a knowledge of himself,
in and through Jesus Christ, the true and saving light;
and that which is required of you is obedience, and a diligent walking therein,
in all fear, humility and lowliness of mind;
for that greatly tends to make sure the steps, in the way of truth and righteousness;
and it is such the Lord teacheth, viz, the humble, by his pure light and grace.
Oh! that a daily care may attend you to follow him in all faithfulness,
in answer to his blessed requirings, whether in words or actions, at home or abroad;
for this is well-pleasing unto him, and a rejoicing unto my soul;
who am still under a weighty concern and tender care for your preservation every way,
in that which is good;
and more especially seeing the Lord hath been pleased to take your dear mother from us.
I have no greater joy than to know that you grow in the truth;
and that you are loving and tenderly affectionate one to the other,
in patience and quietness of mind bearing one with another,
in all affairs wherein you are concerned;
so will your undertakings be more easy and comfortable unto you.
Do what in you lies to keep to meetings, and be condescending one to the other therein;
and when you are met together with the Lord`'s people,
let the fear and dread of the Lord be upon you,
that you may be kept in all diligence in waiting upon him,
daily to feel the work of his spirit in your hearts,
to work you into true tenderness and brokenness; that you may grow up,
and bring forth fruit, to the praise and glory of the Lord, and your enduring comfort;
which is my hearty prayer unto the Lord on your behalf.

We had a very heavenly meeting here in their new meeting-house,
where never meeting was before; and are to have a meeting tomorrow at Youghall,
next day at Cork, where the province Six-week`'s meeting begins;
two meetings there the first-day, and men`'s and women`'s meeting the second-day;
and are to go ten miles to a meeting on third-day, at Bandon;
fourteen miles to a meeting further west on fourth-day;
forty-eight miles back again by Cork, to a meeting at Charleville, on sixth-day.

My acceptable companion, James Lancaster, desires his love remembered to you, and Friends.

[.signed-section-closing]
Farewell, dear children. Your loving father,

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
Waterford in Ireland, the 4th of the Fifth month, 1694.

--

[.embedded-content-document.letter]
--

[.salutation]
Dear children, John and Mary,

That true love and fatherly care which chiefly attends me concerning you is,
that you may grow in grace and saving knowledge, which edify the soul;
and in a sense and feeling of that, witness the divine touches of the love of God,
to tender your hearts before him, among his people, and at other times.
Carefully follow those things, in the course of your life, that make for peace with him,
according to the teachings of his holy Spirit;
by which the Lord hath measurably given you a knowledge
of himself and his will what he would have you to do,
and how to walk before him, and all people.
Oh! therefore, that you may fear, love, and obey him with all your hearts;
so will you be kept humble and low, which is safe and good for all,
but more especially for youth, because their natural inclinations are too often aspiring;
that is, climbing up and getting high.

But the truth, which is his love to the sons and daughters of men,
manifested in and through Jesus Christ, being kept to and lived in,
humbles the heart and brings and keeps down the wild nature;
where safety from many hurtful things is experienced.

By these, you and my friends may know, that I, with my companion J. L., are well,
praises be given to him who lives for ever!
We have travelled through the south and west of this nation to this place, a second time;
and intend, if the Lord will, to go towards the north the next second-day.
And, if I find myself clear, when I have gone through the north, I may turn homeward;
which if so, will be some time in the eighth month;
but this is more than I yet clearly see, and so must leave it at present.

The work is great in this nation, and the labourers are but few;
yet the Lord hath here a blessed zealous people for his name and truth,
filled with love to his servants.
This is largely manifested in accompanying us from one meeting and place to another,
from ten to twenty and more in company at one time, the length of twenty-five miles,
though in the time of harvest (mind that;) and three travelled
from this city above one hundred miles with us,
viz: Amos Strettell, Samuel Baker, and Joseph Hankes,
considerable dealers in outward affairs;
and two also intend to travel with us from this city into the north, viz:
Abel Strettell and Peter Fletcher.
This I write as an example for others to take notice of,
which in love I leave to their consideration, who may see these lines.

[.signed-section-closing]
Your loving father,

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
Dublin, the 18th of the Sixth month, 1694.

--

After I saw it my place and service to settle in Somersetshire,
which was in the year 1696, I often travelled in the counties and shires adjacent,
and also to the Land`'s End, in Cornwall, labouring together with Friends,
to keep up meetings for the worship of God, first-day and week-day; and not only so,
but to keep up and maintain the good order of truth,
and to have the same put in practice.

And the Lord hath been pleased to make use of me as an instrument,
of his own fitting and preparing, to convince several,
some of whom became faithful and able ministers in their day;
and some of them have finished their Lord and Master`'s work,
and are at rest with him in glory.
The Lord keep and preserve them, with my soul and all his everywhere,
diligent and faithful unto the end.
Amen!

[.signed-section-signature]
John Banks.
