== Epistles and Papers of John Banks.

[.blurb]
=== Unto You with Whom I Once Had My Conversation:

The truth in soundness held forth and declared unto
those with whom I formerly had my conversation,
who are yet remaining in the cloudy dark day, tossed from mountain to hill,
and cannot find a place of rest for your souls; but are crying "`there are so many ways,
worships and opinions held forth in the world, that we do not know which is the true way;
for if we did but know the way of God, we would walk in it.`"

For your sakes who are thus crying, I write,
in whom there are true breathings after the way of God: as I have learned of Christ,
who is the true light of the world,
and hath enlightened every man that cometh into the world; so shall I declare unto you,
who once had my conversation with you, according to the vain customs of the world.
While I remained with you in vain sports and pleasures, and in wantonness,
and could have gone to the same excess of riot which many of you are yet in,
you could have spoken well of me, though in an evil action,
because it was a pleasure to the vain mind,
which the light of Christ in my own conscience reproved me for.
I knew not then what it was which reproved me, and let me see that I should not do so;
and therefore was apt to believe those that called it a natural light,
or the check of a natural conscience, a thing not sufficient to bring salvation,
as the world calls it; for, say they, we know we have all such a thing as you tell us of,
but it is only a natural light, or the check of a natural conscience.
Is that natural which reproves in spiritual things?
Let the wise in heart judge by plain Scripture.
Is Satan divided against himself, how then shall his kingdom stand?
This is the windy doctrine of the priests, for which they have no Scripture,
and so add their meanings thereunto, or diminish therefrom, deceiving the simple.
But the Scriptures witness against them who tell you that the light of Christ is natural:
it is the Spirit of Truth, which he hath sent, which doth reprove the world of sin,
of righteousness and judgment, which whosoever believes in, shall not abide in darkness,
but shall have the light of Life.
They are deceivers, whom the prophet declares against,
every one seeking after his own way, for his gain from his quarter;
for put into their mouths, and they will cry peace, peace; but hold from them,
and they will even prepare war against you; and so they are the false prophets,
which the true prophets declared against,
and by which the people of God in all ages suffered the spoiling of their goods;
for they that will live godly in Christ Jesus, must suffer persecution.

When was the covenant changed,
or when do you look for those days declared of in the Scriptures?
"`Behold, the days come, saith the Lord,
that I will make a new covenant with the house of Israel, and with the house of Judah:
not according to the covenant that I made with their fathers
in the day that I took them by the hand to bring them out of
the land of Egypt (which my covenant they brake,
although I was an husband unto them, saith the Lord).
But this shall be the covenant that I will make with the house of Israel:
After those days, saith the Lord, I will put my law in their inward parts,
and write it in their hearts, and I will be their God, and they shall be my people.
And they shall teach no more every man his neighbour, and every man his brother, saying,
know the Lord: for they shall all know me, from the least of them,
unto the greatest of them, saith the Lord: for I will forgive their iniquity,
and I will remember their sin no more.`"

Cease then from man, whose breath is in his nostrils,
and come to the teachings of the Lord in spirit, where the New Covenant is known,
for God is a Spirit, and they that truly worship him,
must worship him in spirit and in truth;
and such he is seeking to worship him in this his everlasting day;
and the children of the Lord,
are taught of the Lord and in righteousness are they established,
and great is the peace of his children.

So all people, turn your minds to that which reproves you in secret,
of that which no man can accuse you for,
that by it you may be led and guided into all truth.
It is the light of Christ, the Spirit of Truth,
which he hath sent to reprove the world of sin, of righteousness and of judgment.
And take heed of the hasty will, that would say, away with this light;
if this be your way, we do not desire the knowledge of it.
Do not call it so, but try and prove its strength,
and depart from the evil which it makes manifest, and do not call it natural,
or a thing not sufficient, because it appears but little in you,
for this is because you are disobedient to it.
Whatever the light makes manifest to be evil, depart from; lying, swearing, drunkenness,
and all manner of profaneness; yea, if it be a secret thought,
or any intent harboured in thy bosom against thy
neighbour or any man or woman whatsoever,
never so secretly, yet being made manifest by the light in thy own conscience,
thou must depart from it,
or else the indignation of the Almighty thou must one day know to be heavy upon thee,
for disobedience;
when the Lord Jesus Christ shall be revealed from heaven with his mighty angels,
in flaming fire, taking vengeance on them that know not God,
and that obey not the Gospel of our Lord Jesus Christ.
For all things that are reproved, are made manifest by the light,
and they that believe in the light, shall not abide in darkness,
but shall have the light of Life; (mark the words) shall not abide in darkness,
but shall have the light of Life.
And though these things may seem but little in your eyes, yet be faithful in a little,
and you shall be made rulers over more;
you shall know power over all the works of darkness, and over the power of the devil.

The people of God witness a cleansing and sanctifying throughout, in body, soul,
and spirit; and the blood of Christ cleanses them from all sin,
for the Lord`'s hand is not shortened, that it cannot save to the utmost,
neither is his ear heavy that it cannot hear.
His power is the same, and as all-sufficient as ever it was;
but ye will not come unto me that ye might have life, saith Christ,
and so you remain in sin and in death; and he that sins is of the devil,
and hath not seen God, neither knows him; and as death leaveth such,
so will judgment find them.
Therefore cease from all those who make a prey of you for dishonest gain,
who lead captive silly women laden with sin, led away with divers lusts; ever learning,
but never able to come to the knowledge of the truth, as it is in Jesus Christ,
who is the true light, the way, the truth, and the life;
and no man can come unto the Father but by him.
I say, cease from all these scribes, pharisees, hypocrites, and deceivers,
who walk in long robes, and are called of men master,
who love the chiefest places in the synagogues, uppermost rooms at feasts,
and greetings in the market-places, whom the woe is to,
who shut up the kingdom of God against men, and will neither enter themselves,
nor suffer those to enter, that would.

Oh! all people cease from them, and come to the teachings of the Lord in spirit,
for the nations of them that are saved, must walk in the light of the Lamb.
But this is the condemnation, that light is come into the world,
and men love darkness rather than light, because their deeds are evil:
But he that doth truth, Cometh to the light,
that his deeds may be manifest that they are wrought in God.

Repent, repent, and turn unto the Lord Jesus Christ,
who is the stone refused and rejected by all the builders of the world;
the same stone is become the head of the corner;
praises everlastingly unto his holy name, who hath called us out of darkness,
into his marvellous light, where we walk and are not faint, run, and are not weary.
He hath not only called us, but also chosen us out of the world,
and therefore the world hateth us, for the world loveth its own; and though we be hated,
persecuted, scoffed, and scorned, and judged as a people not worthy to live,
by this wicked and adulterous generation, who speak evil of the thing they know not;
and though the beast push with his horns,
and the false prophet cast his envy and wrath against the Lamb and his followers,
yet they shall both be taken alive, and cast into the lake of fire,
and the saints shall rejoice forevermore.
I say again, repent, and turn from the evil of your ways, from your idle talking,
foolish jesting, and laughter, which is madness and folly; yea,
all your vain conversation whatsoever, lest sudden destruction come upon you;
which shall come upon all the wicked, who love and make a lie; without speedy repentance,
and amendment of your ways, not only in confessing your sins, but in forsaking them.
There is no other way to obtain mercy at the Lord`'s hand; for be not deceived,
God will not be mocked, such as every one sows, such shall he reap;
they that live after the flesh shall die;
but they who have a part in the first resurrection,
over such the second death shall have no power.

If ever you come to know the way of God, and to walk in it,
you must come to the spiritual worship, for God is a spirit,
and they that worship him must worship him in Spirit and in Truth;
and such he is seeking to worship him in this his everlasting day.
So you, in whom tender desires are, come ye out from among them, and be ye separated,
and touch no unclean thing, and I will receive you, saith the Lord.
Be careful now, while you have time, to cast off the deeds of darkness,
and be separated from all your idol worships, for the Lord is wearied with them.
Prize the everlasting love of God to you, who hath spared you so long; some twenty,
some thirty, some forty years, and upwards; and yet you are crying,
if we knew the way of God, we would walk in it; and then to satisfy yourselves, say,
we hope we are in the way; whereby it is evident you have no certainty of it.
By this you may plainly see, if you are not willfully blind,
that your teachers have not been sent of God, for they have not profited you;
and ye are always learning, led away with divers lusts,
but never able to come to the knowledge of the truth.
Some led into lying, swearing, and drunkenness, fighting, and quarrelling, gaming,
and sporting, and such like fruits as these.

And though both priests and people cry and say we are the false prophets,
and deceivers come in the latter days; I answer as the Scripture saith, "`by their,
fruits the false prophets are known; do men gather grapes of thorns,
or figs of thistles;`" nay, they are not so blind.
So whether the priests and teachers of the world, who have the words,
but are strangers to the life, or we, bear the fruits of the false prophets,
let that of God in all consciences, and plain Scripture judge.
Christ said, "`false prophets should come,`" and John said in his days,
"`that many false prophets and antichrists were already entered into the world;
whereby,`" said he, "`we know it is the last times.`"
I believe many of you will confess, that there were no Quakers,
(as in derision we are now called) in John`'s time, yet he said,
"`they knew it was the last time then,
because many false prophets and antichrists were already entered into the world.`"
You say the last time is but now come in our days; and so whether John,
or the professors and priests, and teachers of the world,
have holden forth the truth in this thing, let the wise in heart,
and plain Scripture judge.
Christ, who is the light and life of men,
is the door by which you must enter into the kingdom, if ever you enter;
"`for he that climbs up any other way, the same is a thief and a robber.`"

And if ever you come to own God, and the way that leads to his kingdom,
you must own the light of the Lord Jesus Christ, in his inward appearance,
to be your teacher, leader, and guide.
It is even he the true light, who is the way, the truth, and the life;
and if you speedily repent, and turn unto God by him, from whom you are fallen,
and put away the evil of your doings before repentance be too late,
it shall be well with you.
But if otherwise you go on in rebellion against the
light and strivings of his good spirit and grace,
which God hath placed in your hearts to witness against all sin and iniquity;
and harden your hearts, stop your ears, and close your eyes,
you shall seek repentance with tears, and shall not find it.
And this you shall know in the day of the Lord;
"`when you must give an account unto him of every idle word,`" and of
all the hard speeches which you have spoken against his servants,
his pure way of truth, and his people;
that you were warned to repentance in your life-time, by a lover of all your souls,
though but as a child, and one of the least among many of the Lord`'s children and people;
yet he hath obtained favour with the Lord and mercy at his hand,
through true judgment for sin, and transgression.

And therefore hath rather chosen to suffer affliction with the people of God,
than to enjoy the pleasure of sin for a season.`"

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
Given forth in the year, 1661.

[.blurb]
=== Unto You Who Once Knew the Truth, the Light, to Your Justification; But Being Turned From It Into the Unclean World, It Is Now Your Condemnation:

That all in whom there yet remains any tenderness,
or breathings towards the Lord and his truth,
and whom the enemy of their souls`' peace may be tempting to forsake the truth,
for the enjoyment of that which will perish in a moment,
may take warning lest they also be given up to hardness of heart.

Did you once know the truth, to convince you of the evil customs, fashions,
and vain traditions,
together with all the dead worships and forms which are in the world,
and are you now like the dog turned to the vomit, and the sow that was washed,
to the wallowing in the mire.

Oh! how doth my soul mourn and lament for you in secret,
at the consideration of your state;
who were once convinced by the light of the Lord Jesus,
of the evil that is in those things, and knew his power to redeem you therefrom,
in some measure.
And as you yielded obedience to that which manifested the evil and departed from it,
how did your peace increase?
so that you were brought near unto the Lord in spirit,
and worshipped him in truth and righteousness, by which you felt acceptance with him,
and he was well pleased.
And are you now departed from this, and gone back again into Egypt`'s darkness,
amongst the flesh-pots, which causeth you to have an ill savour?

Consider your ways, and look back from whence you are fallen;
and return unto that which justified you, but now condemns you,
or else you must perish eternally.
Wherein stands your joy, peace, and comfort?
or in what can you content yourselves?
Doth it stand in the enjoyment of the deceitfulness of riches,
or in that which will perish in a moment?
"`Thou fool,
this night thy soul shall be required of thee,`"
and then whose shall all these things be,
for which thou hast forsaken my precious truth, saith the Lord;
which of my everlasting love I made manifest unto thee, for the salvation of thy soul.
"`For as I live,`" saith the Lord,
"`I will not the death of a sinner--Oh foolish and unwise people, who hath bewitched you,
that you should forsake the truth,`" which forever will be your condemnation,
except you repent.
Repent then, consider your ways, and be wise,
who are not wholly given up to hardness of heart, and past feeling that which is good:
Repent, and return unto the Lord God with all your heart,
and be ye separated from all idol worships,
and come ye out from amongst all those people who resort thereto, whose course is evil,
and whose way is not right.
For if you do not, but go on in rebellion and hard-heartedness,
(mark what I say) seven other spirits more
wicked than that which bare rule in you before,
will enter you; so that you will become two-fold more the children of hell,
than you were before.

Oh! your state is sad, and your condition lamentable, who turned from the light,
Christ Jesus, the way, the truth, and the life, into darkness,
to be tempted and led away of the devil.
Your state is miserable, who turn from worshipping the true and living God,
in Spirit and Truth, which worship he accepts and none else,
to the worship set up by man`'s invention and tradition; and forsake the truth, the light,
under what pretence, colour or covering soever.
If upon pretence of staying at home; and say, Why may you not serve God as well there,
as in coming to our meetings; and that you will stay a while at home,
and not join yourselves to any people as yet.
Oh!
Believe not, neither hearken ye unto the enemy of your soul`'s peace,
in this kind of reasoning by his lying spirit, by which he would counsel you;
or under what other pretence soever,
for this is the craft and subtlety of the old serpent.
He will proffer you all the glory and preferment of the world if you will worship him,
or that likeness which is now set up, under what name, or in what manner soever;
whether by staying at home, or with whatever other trap he may take you;
for he cares not whither the body goes or is,
so that he in his subtlety can but get the rule of the heart,
and the affections set on earthly things.
If you lend an ear unto him, you will grow worse and worse, as the wicked do;
and then though you may enjoy all the pleasures the world can afford,
you shall always beg, and still want; he that hath an ear to hear,
let him hear what the spirit saith.
This covering, or any other besides the Spirit of Truth,
cannot hide you from the wrath of the Lord.
For where is your example?
They that feared the Lord, and worshipped him in Spirit and Truth, met often together,
though sometimes upon mountains and high-ways;
and did salute the church at one another`'s houses.
And they that forsake the assembling themselves with the people of God,
under what colour or covering soever,
I must declare it for the clearing of my conscience, whatever they pretend,
they neither worship nor serve God, nor hath he pleasure in them, because they draw back;
"`for if any man draw back, my soul hath no pleasure in him,`" saith the Lord.
All these coverings are but like those of fig-leaves;
for "`woe unto them that are covered with a covering,
but not of my spirit,`" saith the Lord;
all other coverings shall be ripped off in the day of the Lord,
and they that are under such coverings, shall be made naked and bare,
and by his jealousy consumed.

Oh! how is the truth dishonoured by you who turn from it.
Oh! how do vain people boast themselves against it, and plead to do wickedly.
"`Because of you offences come, but woe unto them by whom they come;
it were better that a mill-stone were hanged about their necks,
and they cast into the depth of the sea.`"

Therefore I say unto all you in whom there are any true
breathings towards the Lord and his truth yet remaining,
and do yet feel the spirit of the Lord striving with you;
in whom the enemy of your soul`'s peace may be twisting and twining,
to drive you therefrom, and to persuade you to forsake the truth,
(but under another pretence,) for that which will perish in a moment,
and will bring everlasting torment; I say unto you in true and tender love,
take warning betimes, upon the consideration of what I have before said,
concerning the state of them who are turned from the truth;
lest you also be given up to hardness of heart.

Friends, do you know the truth in any measure to abound in your hearts, yea,
though never so little?
and do you feel the spirit of the Lord yet to strive with you,
which will not always strive?
and are you sensible for what it striveth?
and do you know the truth, and that there is not another way, nor truth,
that can bring people unto God?
and do ye know that ye are in that, and if you turn from that,
it must be to your own condemnation?

And doth the truth let you see that all worship and forms,
and many ways and opinions in the world, are dead, dry and empty;
and that all the vain customs and changeable fashions in the world, are corrupting,
and will defile.
And are you not sensible that the Lord out of his everlasting love,
did reveal and make manifest these things unto you, that you should come out of them,
and be separated from them, and wait upon him, and worship him in Spirit and in Truth,
according to his own ordination.
And if you turn back again from this his precious truth,
which hath separated you from all these things,
or at least made them manifest to be evil, into the world where all these things are,
you shall be polluted by them.

I say, Friends, do you know, and hath the truth made you sensible of these things?
Oh! then forever stand fast, faithful and obedient, and continue to the end,
and you shall be saved.
Let none faint in their minds, nor sit down by the way, but in the measure of light,
which hath life in it, breathe unto the Lord, and continue unto the end,
that in the end you may receive the crown of life, even the salvation of your souls.
But they who are not willing to bear the cross, cannot obtain the crown;
and they that will live godly in Christ Jesus, must suffer persecution.
They that are not willing to suffer with him, must not reign with him;
(mark that) and "`he that loves father or mother, wife or children,
house or lands more than me,`" saith Christ, "`is not worthy of me.`"
Dear Friends, as you value the salvation of your souls, which is of great weight,
"`choose rather to suffer affliction with the people of God,
than to enjoy the pleasure of sin for a season;`"
and do not hearken unto that spirit in you,
which would say you may go to the world`'s worship, and yet live honestly,
and serve God well enough.
Oh! dear Friends, let none hearken to that, for that is the seed of the evil one,
the devil, who was a liar from the beginning.
"`You cannot serve God and mammon;`" you cannot forsake the truth, and serve God;
though the enemy of your soul`'s peace may tell you that
departing from or not coming to meetings,
in the way and manner that the people of God meet to worship him in Spirit and Truth,
and going into the world, or to their worship, is not departing from the truth,
and that you may serve God in another way, and live honestly in this world.
Dear Friends, be not deceived through the subtlety of the enemy,
for God will not be mocked: such as every one of you sows, such shall he reap;
"`they that sow to the flesh, shall of the flesh reap corruption;
but they that sow to the spirit, shall of the spirit reap life eternal.`"

But rejoice ye, my suffering Friends, who sow unto the spirit,
of which you shall reap life everlasting; rejoice, I say, and be exceeding glad,
even in the God of your salvation.
Let your rejoicing be in the cross of our Lord Jesus Christ,
by which ye are crucified unto the world, and the world unto you;
ye lambs of my Father`'s fold, with whom I lie down and am safe, even in the endless rest.
Oh rejoice, ye who are freely given up to follow the Lamb whithersoever he goeth,
in this the day of trial; "`wherein he will thoroughly purge his floor,
and gather the wheat into his garner, and burn the chaff with unquenchable fire.`"
In which day the wolf is seeking to worry you,
and the ravenous beasts to make a prey of you;
and wherein the spoiler may be suffered to take
away that which you enjoy as to the outward;
yet again I say unto you, rejoice; as one whom the Lord hath made sensible of your state,
as being a member of the same body, for the stirring up of the pure mind in you,
that you may be more sensible of his love in your trial,
and that you may answer the same by pure obedience:
Praise and magnify the God of your salvation,
by walking in obedience to what he requires of you, or suffers to come upon you,
for the trial of your faith,
who are as those having nothing yet enjoying all things to the praise of the Lord.
Yea, truly, my Friends, this can I say to your comfort,
that in whatever ye suffer freely and willingly,
for holding the testimony of Jesus in righteousness,
you shall receive an hundred fold in this world,
though it cannot be beheld with an outward eye, and in that which is to come,
everlasting life.

Blessed are your eyes that see, and your ears that hear,
and your hearts that understand the things of God aright,
for you shall hear and receive the things that belong to your peace.
Yea, as you diligently hearken to that still small voice in you,
which is the voice of the true Shepherd,
who calleth the sheep of his pasture into his fold, who know his voice,
and the voice of a stranger they will not follow.
As you keep close unto this, which leadeth into the low valleys, where fat pasture is,
you shall receive strength,
whereby you will be enabled to stand in and go through the greatest trials,
and leap over the highest mountain that shall arise in your way.
So shall you finish your testimony for the Lord,
and his pure way of truth and righteousness, in the faith of Jesus Christ,
in which you did begin; which is to make a blessed and happy end and finishing;
for such as continue and persevere unto the end, in all faithfulness, shall be saved.
Unto which the Lord preserve you all, bold and valiant, and faithful for the truth,
while yet upon the earth, is the breathing and travail of my soul,
in tender love to the Seed of God in all.

[.signed-section-signature]
John Banks.

[.blurb]
=== For Friends of Paedsay-Meeting, or Elsewhere in Cumberland; To Be Read Among Them, in the Fear of the Lord.

[.salutation]
Dear Friends,

The foundation of God standeth sure, and they whose building is thereupon,
dwell in safety, where the enemy cannot come.
Dear Friends, keep the watch, that nothing may have any entrance into your hearts,
but the beloved of your souls, whose love hath been so prevalent with you,
that by it a willingness hath been wrought in you to part with all for his sake.
Oh! therefore, press on towards the recompense of reward, always following him,
so that you may feel sweet peace with him in your bosoms;
for behold he cometh quickly and his reward is with him; who can deliver,
both out of the fire, and out of the water.

Let none think it strange concerning the fiery trial,
in which the Lord hath seen it good to try you, among the rest of his people,
as though some strange thing had happened; but all be faithful to the Lord unto death,
and you shall receive a crown of life.
It is not they that have begun well, and sit down by the way,
who receive this recompense of reward;
but they who in faithfulness continue unto the end, who know the saving health of Israel,
and are cured of all their infirmities.

Let none suffer that to have place in your hearts, which would say, Why is it thus?
or why hath the Lord suffered it thus to come to pass?
But all keep the faith and hold fast your integrity, and be steadfast in your minds,
for ere the day be over, the trial must be greater,
before the dross be separated from the pure gold;
for the Lord our God is about to work a thorough work in the earth,
to make you clean vessels for his use,
by which he will get himself honour and make you shine who are faithful.

Blessed and happy are all you, my dear Friends, who honour God in your generation;
and woe to them who dishonour him in their lives and conversations,
who would seem to honour God with their mouths and lips,
and yet their hearts are far from him, in the earth.
And all that are given to tattling, and talebearing, and of a whispering spirit,
and busy mind, are for judgment; and in what bottle soever these things are retained,
it will burst, and must be broken to pieces.

Therefore, watch against every appearance of evil, both within and without,
with an eye for good, over one another; that where there is an evil eye,
it may be plucked out; and so the eye being single,
the whole body will be filled with light, by which the darkness comes to be expelled.
And they whose abiding and dwelling place is here,
know that it is a pleasant thing to dwell together in unity.
"`It is like the ointment that was poured upon Aaron`'s head, which ran down his beard,
to the skirts of his garment; yea, as the dew of Hermon,
and as the dew that descended upon the mountains of Zion;
for there the Lord commanded the blessing, even life forevermore.`"

Dear brethren, dwell together in unity, that this blessing may be witnessed among you,
even life forevermore.
And that this everlasting dew may be felt to be distilled among you,
that so you may all be members of that body that
is fitly framed together by joints and bands,
which the Lord God hath prepared to do his will.

And all my dear Friends, in the Lord Jesus Christ,
who have kept your garments unspotted of the world,
and who have borne a faithful testimony for him in this trying day and perilous time,
peace be unto you: the love of God fill your hearts,
and his living unity tie you together forevermore; with whom I am truly bound up,
in that bundle of love and life that can never be broken.
Surely my soul loves you, and I am truly one with you, in that love and unity,
of which length of time, distance of place,
and wide seas can make no breach or separation.
Oh! be you all encouraged to follow the Captain of your salvation,
who hitherto hath gone before you and pleaded your cause with your enemies,
both within and without.
Surely you have good experience how he hath spread his banner over you, which is love;
which unto you hath been as a covering from the heat,
and a hidingplace from the tempest and the storm.
Yea, it is even so,
for there never hath been any weapon yet formed against you which hath prospered,
as you have stood in his pure counsel.

Therefore,
whatsoever the Lord may yet suffer to come to pass for the further trial of your faith,
fear not, ye little flock, for it is his good pleasure to give you the kingdom.
And though the waves toss themselves, yet need you not be troubled,
for he that delivered Daniel out of the lion`'s den, and Shadrach, Meshach and Abednego,
out of the fiery furnace, is the same as ever he was.
"`I am the Lord, I change not,
therefore ye sons of Jacob are not consumed,`" but preserved,
and that to his praise and glory, even all who are of that seed and offspring.
And blessed are all you that suffer for truth and righteousness sake,
who count nothing too hard, too near, or too dear to be parted with,
for this righteous cause of your God; great is your reward in heaven,
even life everlasting, world without end.
And as the Lord your God,
hath not only counted you worthy to believe in his name and truth, but to suffer for him;
Oh suffer joyfully the spoiling of your goods: wife, or husband, whoever it be,
part with and freely give up each other, whether to a prison, or the spoiling of goods,
or to be spoken all manner of evil against.
The servant is not greater than his Lord; as they have done unto me, saith Christ,
so will they do unto you; who suffered even unto the death upon the cross,
through the counsel of the chief priests, scribes, pharisees, and hard-hearted Jews.

Dear Friends, consider the everlasting love of God unto you,
who spared not his only Son for your sake, that by him, to wit,
by his death and suffering, you might be redeemed out of your miserable state,
and lost and undone condition.
By this love, the Lord your God hath wrought a willingness in your hearts;
and oh! that he may work more and more; that so in a true sense of the same,
you may be preserved,
to the tendering of your spirits in true unity
and fellowship with him and one with another.
In a blessed inward feeling of that love, life,
and heavenly unity which are at this time in my heart, I take my leave of you;
and breathe unto the Lord, that we may all be preserved unto the end.

[.signed-section-closing]
Your brother in the living truth, that changeth not.

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
From Malloe in the county of Cork, in Ireland, the 19th day of the Sixth month, 1671.

[.blurb]
=== The Testimony of Truth, Against All the Customs, Fashions, Ways, Words, Worships, Carriages and Behaviours That Be In the World, Which Are Out of the Truth.

[.centered]
__With an exhortation and warning to all that profess the truth,
and come amongst God`'s people, and yet are found in the said customs, fashions, ways,
words, etc., and plead for them.
The people of God,
in scorn called Quakers do deny and have no fellowship
with such unfruitful works of darkness,
but rather reprove them, because the testimony of truth is against them.__

Fashion not yourselves like unto the world, for the world passeth away,
and the glory of it as the flower of the field; and the world by wisdom knows not God,
nor the things of his kingdom, for its wisdom is from below,
which leads and draws down into the beggarly elements and rudiments.
The carnal-minded man knows not the things of God nor his kingdom,
even those things that belong to the soul`'s peace; for they are foolishness to him,
because they are spiritually discerned.
The carnal mind and wisdom lead out into carnal, visible things,
to feed on the husks among the swine; for without are dogs, sorcerers, etc;
and that spirit which rules in the hearts of the children of disobedience,
leads into divers lusts, pleasures, customs, fashions, idle talking, foolish jesting,
lying, swearing, pride, and drunkenness.
Such discern not the Lord`'s body, but crucify him, and say, as some did of old,
they will not have this man, even Christ, to rule over them; because by his light,
he reproves them for their evil deeds . So they crucify
the Son of God afresh and put him to open shame,
by sinning against him.
And in such, who bring forth these fruits, the just suffers by the unjust.

For these are the fruits of the flesh,
and of those who preach and teach for doctrines the precepts of men,
and are found in the many inventions; in outward washings, eating and drinking,
under a pretence that God requires these things at their hands; when as he saith,
"`Who hath required these things at your hands?`"
These things do not so much as make clean the outside;
and so are far from making or keeping the heart or conscience clean,
or void of offence towards God.
All such ways, worships, customs and fashions, truth`'s testimony is against;
for these things are practised amongst them who say
they are erred and strayed from the way of God,
like lost sheep; and so upon good ground God`'s people dissent from them.

The practice of the world, is to change from fashion to fashion, in pride of apparel,
meats and drinks, to see who can exceed each other in pride and high-mindedness;
to the end, their eyes and minds may look out, one after another.

The practice of those who truly fear the Lord,
is to be plain and decent in their apparel, not given to change,
as they of the world are, nor to wear anything but what becomes the truth,
and may tend to adorn the Gospel of our Lord Jesus Christ.
Where God hath endowed with much, they are not to be extreme because of that;
nor they who are endowed but with little,
to strive to set out the fleshly part beyond their ability; for both in rich and poor,
this is to cause the eye to look out, and the mind to wander.
But the people of God strive who can exceed each other in good example; both in meat,
drink, and apparel, only using what is decent and comely;
to the end every eye may be turned inward, and all learn to be lowly-minded.

The ways of the world are many, crooked and unclean; and they run to and fro in lying,
swearing, and drunkenness; idle, vain, needless, unsavoury words; vain customs,
and proud antic fashions; which is the cause why their ways are crooked and unclean.

The way of the people of God, whom he hath redeemed out of the world,
is but one straight and pure way, in which they follow the Lamb in the regeneration,
who leads them out of all uncleanness, into purity and holiness.

The words of the people of the world, are many, needless, and unsavoury.

But the words of God`'s people are few and savoury.

The worship of the people of the world, who deny the true light, is in darkness,
and their prayer therein is not heard, nor answered; for in praying, they cry,
Lord forgive us our sins; and yet they do not believe they can be freed from them;
and the people they preach to, live in their sins and so are never the better.

The worship of the people of God is in Spirit and truth;
they pray with the Spirit and with the understanding, and their prayers he hears,
and answers; they preach, being sent of God, and so profit the people;
and such receive the end of their hope, the salvation of their souls,
by Jesus Christ the righteous.

And now unto you who profess the truth, and assemble amongst God`'s people,
and yet are not in reality what you should be, either in your words or practice,
in many things; but are loose and unfaithful; in love to your souls,
this is written as a faithful warning, being the testimony of truth.

Take heed both old and young,
who are fashioning yourselves according to the world in extremes,
beyond the bounds of truth, either in your apparel, words, carriage, or behaviour.

What! cannot you set the people of the world an example according to truth,
and if they will not come to that, never go you to join with,
embrace or follow their vain and antic fashions.

And you that are old men and women, both as to convincement and years,
set a watch in the fear of God against hastiness, rashness, peevishness,
and crossness of spirit, for this is an ill example to your children,
and to such who are young and weak in the truth.
But be ye grave and temperate, as nursing fathers and mothers;
and set a watch before your lips, that you may not offend with your tongue.

And both old and young, who make a profession of the truth,
take heed that you do not utter unsavoury words in your communications,
and using the name of Lord and God in your common talk,
as is the manner and custom of the people of the world.
This is taking the name of God in vain, and such he will not hold guiltless.
It is evil communication that corrupts good manners.
"`Ye are the salt of the earth,`" said Christ Jesus to his disciples,
"`but if the salt hath lost its savour, it is good for nothing,
but to be cast out and trodden under foot of men.`"
Wherefore have salt in yourselves.
Friends, you know that from the time you were first convinced,
the truth would not allow nor admit of any of those things above;
and it is the same now as ever;
therefore consider from what root it is these things arise,
for they are all out of the truth and disowned by the children of light;
and the testimony of truth is against them.

You who are parents of children, train them up in the fear of the Lord,
as becomes the truth, and give no liberty to them, nor indulge them in word or action,
that is contrary to the truth of God.
Teach them the plain language of thee and thou, to every single person;
and to name the days of the week, and months in the year,
according to the testimony of the holy Scripture; for this is according to truth;
and not, as the people of the world do, after the names of the heathen`'s gods.
And beware, both old and young, of taking liberty,
and presuming to do such things as you call little faults, until greater evils break out;
for then will shame come openly to such, and God`'s truth and people suffer.

And let none join with the people of the world, in their customs of marriages, feastings,
or set drinkings, sports, pleasures, or vain shows whatsoever;
but take heed unto the light of the Lord Jesus Christ,
which makes manifest all things that are reprovable and for condemnation.

Beware all you who profess the blessed truth, of being overcome with strong drink,
or other liquors, for by such the truth will suffer great reproach.
Take heed of idle talking, foolish jesting, or fair speeches,
for pleasing your relations in the flesh, for an earthly end,
more than the truth will allow of, that is a deceitful thing;
neither be ye found back-biters, tattlers, nor tale-bearers, to stir up strife,
or busy bodies in other men and women`'s matters.

Be watchful in the fear of God, and carefully mind and obey his teaching grace,
and holy Spirit; the Spirit of Truth that leadeth into all truth.
And as this is kept to,
we cannot in conscience join with the people and spirit of the world,
for that spirit leadeth out of the truth, into the broad way which leads to destruction.
So all who in any measure have known your garments washed and made clean,
from the pollutions of the world, have a care that they be not spotted and defiled again,
by being familiar with the people of the world, in their vain, loose discourse,
in their communications.
This is the inlet of many evils; for we cannot join with the spirit of the world,
that leads into vanity and excess,
without there is first a going from the Spirit of Truth in ourselves,
for light hath no fellowship with darkness.
Hence when the mind is gone from the pure light and all-sufficient grace,
the eye is abroad after many things, which should be inward to the Lord;
and so that eye and mind being too much one with the world,
such begin to spy out which is the newest and finest cut and fashion,
and the minds of such are restless until they have it;
being gone from the truth in themselves, in which is the true rest and peace.

And yet you would be owned and called Friends: "`You are my friends,`" said Christ,
"`if ye do whatsoever I command you.`"
And he says, "`Learn of me, for I am meek and lowly in heart.`"
His grace teaches not to be proud, or high-minded, for that is the enemy`'s work,
and the spirit of the world joins with it, but not the Spirit of Truth.

But some are friends to the world, and enemies to God;
so consider whether you are friends of Christ, or of the world;
for according to the blessed apostle Paul, "`Be not deceived, God is not mocked,
such as you sow, such must you reap; they that sow to the flesh,
shall of the flesh reap corruption, but they that sow to the Spirit,
shall of the Spirit reap life everlasting.`"

Now it is plain and clear to every one who knows
what it is to have their eye in their Head,
(which is Christ) that they who follow and join with the world,
in their needless and extravagant fashions, sow to the flesh, and the wrong spirit;
for some of which the prophet Isaiah, in chap.
3rd, from ver. 16th to the end of it,
reproves the haughty carriage and behaviour of the daughters of Zion.

Wherefore I say unto you, away with your round tire, like the moon,
(as said the prophet) and setting your dresses
high above your brows with your powdered hair;
but adorn yourselves in modest apparel, with shamefacedness and sobriety,
not with broidered hair, or with gold or pearls, or costly array, but,
which becometh women professing godliness, with good works, as said the apostle Paul,
1 Tim. 2 ver. 9, 10. And for further proofs,
read Jer. 10:2-3. 1 Cor. 7:31. 1 Pet. 1:14. and Ch. 3
ver. 3, 4, 5. and there you may see how many fashions the apostles name.

The fashions too many of you are found in the practice of,
had you not your example from the people of the world,
and were taught by the spirit of it to uphold and plead for them,
and not from those who truly fear and serve God; nor yet from his pure holy Spirit,
for the testimony thereof is against your fashions, that the truth never led into;
and they who live the life thereof, must stand in their testimony against them.
These things cannot be hid from the world,
being daily and publicly practised and seen with their eyes.

That as Thomas Ellwood said, in his Epistle to Friends: "`It hath come to pass,
that there is scarce a new fashion comes up, or a fantastic cut invented,
but some one or other who professes truth, is ready with the foremost to run into it.
Ah!
Friends, the world sees this, and smiles,
and points the finger at it and this is both a hurt to the particular,
and a reproach to the Society in general.`"

If you would not have these things spoken nor written against, take away the cause,
and the effect will cease.
See to it, that the inside be clean, and then the outside will be clean also.
Cast off the deeds of darkness, and put on the armour of light,
and willingly take up the cross of the Lord Jesus Christ, and contentedly bear it,
and it will crucify you to the world and the world to you, with all the vain fashions,
words, and actions of the world, with all the sinful lusts of the flesh.

And as our dear and elder brother, George Fox, who was a good example to us in his time,
said; "`All Friends everywhere, admonish one another, young and old,
that you do not run after every fashion which is
invented and set up by the light and vain mind;
for if you do, how can you judge the world for such things?--And set not up,
nor put on that which you once did with the light condemn; but in all things be plain,
that you may adorn the truth of the Gospel of Christ, and judge the world,
and keep in that which is comely and decent.`"

So hear and fear, betimes, and lay to heart and consider these things,
for the spirit of the Lord is grieved because of them,
and the hearts of the righteous are made sad; therefore see that these things be amended;
for all these are for judgment.

And you who profess the truth, and meet amongst God`'s people,
and yet go out into the world to seek wives,
or to join yourselves with the world for wives or husbands; the testimony of truth,
and of the holy Scriptures, and all God`'s people is against you,
because you have fellowship, and join with them who are in darkness.
In so doing, you go from the truth in yourselves,
and so lose unity with the children of light,
and wax cold in your love and affection towards God, his truth and people; and grow hard,
proud, and highminded, and count this but a light matter,
but it will prove heavy unto such in the end, except they unfeignedly repent.
Oh! be not deceived, you cannot serve God and mammon; you cannot live in the truth,
though you make profession of it, and join with the world.
Why are you so vain in your imaginations, and why are your foolish hearts so darkened?

Surely it is because you have not been watchful in the fear of God,
against the out-goings of your minds; and not keeping to that which is good,
the evil hath overcome you.
For if you had dwelt in the pure light, it would have expelled your dark thoughts,
and then the world`'s spirit would have had no place in you.

It never was the practice of God`'s people, in any age of the world,
to be joined together in marriage, by a hireling priest.
But marriage being an ordinance of God,
and the true joining together being in and by his Spirit,
God`'s people who kept the law of marriages,
took one another in the assemblies of the righteous, or before witnesses,
and they were and are witnesses thereunto.

And so, dear Friends,
whom God hath redeemed out of the world and the evil that is therein,
keep out of the same, keep your garments unspotted of it;
take heed of that which would spot and mar your garments, and heavenly image.
Evil words in your communication spot and mar; corrupt ways, peevish, hasty,
and passionate humours, lead and drive the heart far from God,
and out of the way of truth.
Evil customs and changeable fashions, spot and defile your garments.
Condescending to the worldly spirit, for pleasing relations, or others,
for an earthly end, loses your dominion in the truth.
Mixed marriages by a priest, and yet the truth professed,
tend to bring into worldly-mindedness; and where the earth and love to the world,
come over the pure mind, the just is oppressed by it.

Live and dwell in the redeeming power of God, that sets free, and preserves so,
all those who abide in it.
It preserves out of the world`'s ways, customs, and fashions; out of unsavoury words,
out of hastiness, bitterness, and crossness of spirit; out of pride, and high-mindedness,
bad marriages, and the like, and preserves the mind unto God;
to seek first his kingdom and the righteousness thereof, and then all other things,
in the Lord`'s time, will be added.
Thus you may be true witnesses that greater is he that is in you,
than he that is in the world.
Christ Jesus, God`'s everlasting power, you are all to follow, hear, and obey;
he leads into purity, and holiness; he leads into the green pastures, which make fat;
but the spirit and power of the prince of the air and darkness, that rules in the world,
if you give way to it, leads into blindness, and darkness, and hardness of heart,
and leanness of soul.
And when the soul is in death, what better will any be to have a name to hve, and be dead?
What comfort can a wife, a husband, houses, lands, gold or silver,
then minister unto any, especially when their dying hour comes,
and they not fitted for it; for tribulation,
anguish and woe will then be to every soul that doth evil.

So know Christ Jesus the power of God, to be your head, and husband,
and never forsake or deny him, for any pleasure or delight in the world,
for the world passeth away, and the glory of it; but he, the way, the truth,
and the life, will last and endure forever; whose name is called the Word of God.
He hath said, I am Alpha, and Omega, the beginning, and the end, the first and last;
he was before, and will out-last all the world`'s ways, worships, customs, fashions,
tithes, types, figures, shadows and inventions of men.
He the substance is come, and fed upon; blessed be his name forevermore.

And, dear Friends, keep all your meetings in his name and power.
Come orderly together at the time and hour appointed, not scatteringly,
a long time one after another, for this is no good example to the world,
nor so profitable for your growth in the truth, in your own particulars.
Keep your meetings in constancy and faithfulness, as well on the weekday,
as on the first-day; as our manner was in the beginning.
Prize truth and God`'s glory, for truth is the same that ever it was;
and the Lord is not wanting to his people now, any more than formerly,
to them who in faithfulness wait upon worship and serve him.

And, when you are met together, be faithful and diligent in keeping your watch,
and take heed that you be not overcome with the spirit of slumber,
especially you that are ancient, and public in the affairs and concerns of truth;
nor any professing to wait upon, worship and serve God, neither old, nor young;
it is of bad report, and ill savour, and very uncomely to behold;
a stumbling-block in the way of the weak, a hurt of their own souls,
and a grief unto the heart of the upright.

Dear brethren and sisters, be faithful and diligent in your meetings, and waitings,
lives and conversations, that you may adorn the Gospel of our Lord Jesus Christ;
that the life you live, may be the life of the just, which is by faith in the Son of God;
for this only gives the victory over the world, and all the evil that is in it.
Hold fast the same unto the end, that you may receive the crown of life,
and of immortal glory.
That to God alone, who hath called you by an holy calling,
and gathered you together by his own hand and arm of power, to wait upon,
worship and serve him, who never said to the house of Jacob, seek ye my face in vain,
you may give the praise, and evermore have cause to return him the honour and glory;
who is worthy thereof, forevermore, Amen.

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
Mooregate, in Cumberland, the 22nd of the Twelfth month.

[.blurb]
=== Dear Friends and Brethren, Unto Whom the Salutation of My Love Reacheth.

In all your meetings together to do service for the Lord, his truth, and people,
and to see that good order be kept in the churches of Christ,
wait diligently to be endowed with power and wisdom from above, which is pure,
and peaceable;
that by the same you may be guided to judge of and determine
all that you have committed to your trust and charge,
whether in things spiritual or temporal.
Thus good order, the blessed unity and fellowship that stands in the one spirit,
may be preserved amongst you, and every one may have right done them,
and true judgment in the power and wisdom of God
may be set upon the head of that which is unruly,
stubborn and rebellious.
For take notice, that every one who professeth to be a member of the body,
or of the meeting, where things are to be done in unity, according to order,
and settled and agreed to by the ancient and elder brethren of the church of Christ;
every such an one ought to be subject and condescending one unto another,
in things which are already settled and established as to church-order;
and not any one to say in this or the other, I would be left to my freedom and liberty.

Let all seriously consider, that if every one of you when met together,
should be of this mind, would not this tend to lay aside and break all order,
rule and fellowship, as it is already settled according to truth,
in our men and women`'s meetings, as seen meet in the wisdom of God?
Yes, surely it would.
Wherefore I cannot but say unto you, for the clearing of my spirit,
that care be taken to keep up the good order settled in the church;
notwithstanding some in their particular judgment be against it.
I speak in tenderness,
for the good and preservation of all who love
good order and unity with the people of God,
beware every one of reasoning above the simplicity of the truth;
for the apostle warned to take heed that you be not
betrayed from the simplicity that is in Christ,
as the serpent beguiled Eve.

Dear brethren and sisters, be ye all careful to keep low and near the Lord,
and then you will be kept near and dear one unto another; and the Fountain of life,
and Divine wisdom will be opened unto you,
and the streams thereof will run plentifully among you;
which will make all your meetings and undertakings sweet and comfortable,
in the wisdom and power of God; and in the heavenly fellowship of his spirit,
all the disorderly, unsubjected, and unruly will be judged and cast out from among you.

Wherefore, dear Friends, keep close together, as a body fitly framed together in unity,
so shall nothing be lacking; for we need not to want anything amongst ourselves,
that may tend to strengthen us against the enemy within, or his instruments without;
for he is strong and subtle, and they are many,
all seeking to devour and break us asunder,
which all the powers of hell and death shall never be able to do,
as our care is to keep close together.
Let your continued care and mine be, that nothing upon any account may be given way to,
that may tend to do any hurt, or make any breach amongst ourselves;
but as the Lord hath honoured us with his truth, above many, to his praise and glory,
and our comfort be it spoken, he hath preserved us in unity,
and sweet communion together for many years.
Oh! that we may still be concerned as one man, of one heart and mind,
to continue and persevere unto the end,
in that in which we have begun and thus far are preserved, living to God,
zealous for his name, truth, and glory; that through our careful settling,
and steadfast abiding upon the rock and living root that bears us,
we may bring forth fruit more abundantly, through the fresh springs of life,
which will spring afresh into us, in and through Him,
who is the fountain of all our mercies, blessings, favours, and preservations;
that living praises in our hearts and mouths in our assemblies, may arise to the Lord,
in a sense of life, being broken and tendered before him, to bless, praise,
and magnify his holy and honourable name, for our preservation in his truth,
near to himself, and in love and unity one with another;
which is the travail and living concern and prayer of your brother,
that you may be so kept and preserved forever, unto the end.
Amen.

[.signed-section-closing]
Known to you by the name of

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
From my prison-house, in Carlisle, in Cumberland, the 29th of the Third month, 1684.

[.blurb]
=== The Blessed Effects of True and Saving Faith: With Encouragement To All Friends Everywhere, That Suffer For Truth and Righteousness Sake.

[.salutation]
Dear Friends,

The great work of God in the sons and daughters of men,
is to purify the heart and make clean the inward parts,
which is through faith in his Son.
Faith is the gift of God, and the work of it is to purify the heart,
and cleanse from dead works, to serve the true and living God in newness of life,
to work out the old leaven, and mould into a new lump, to make the heart a-new,
the mind heavenly, and the soul living.

Oh the blessed effects of true and saving faith,
even that faith which stands in the power of God! which as man comes to the knowledge of,
such come truly to believe in God, and confession with the mouth is made to salvation,
and so gradually a casting off and forsaking everything that is evil,
whereby a learning to do well, by the teachings of the grace through faith,
comes more and more to be known.
These are the blessed effects of true and saving faith;
which works tenderness in the heart, instead of hardness,
and brings to true openness those that have been shut up,
and into a nearness with the Lord, and one with another,
even such who have been far separated from him, by wicked works.
This is true faith, that works in the heart, to the overcoming of it,
saves them that were lost, quickens them that were dead,
and brings them through the strength and power thereof, to serve the true and living God,
in the newness of life.

The blessed effects of this true and saving faith, are to make clean, pure, and holy,
and to sanctify throughout, in body, soul, and spirit; to make a new creature,
and bring to a true knowledge.
What it is to be in Christ Jesus; and so the heart, with the whole affections,
come to be set on things which are heavenly, everlasting, and eternal.
Oh! the pure change and blessed alteration that comes to be known hereby.
Man that hath been unclean, is made clean,
and man and woman that have been unholy and impure, are made holy and pure;
and so in the holy life, holy men and holy women,
come to worship and serve the pure holy God, in the newness, livingness,
and tenderness thereof.
According to their measure, they come with the blessed apostle, to say,
by living experience; "`The life that I now live is by faith in the Son of God.
Old things are past away, and behold all things are become new.`"
The old words past away, the bad actions and vain conversation put off,
which are for judgment and condemnation;
and the armour of light put on through the blessed effects thereof.

Through this true and saving faith, which stands in the power of God,
His people come to have on their armour, by which, they are made more than conquerors;
made able to withstand all the fiery darts of the devil,
and all his instruments both within and without,
and with the prophet to leap over a wall, run through a troop,
and to break that which is as a bow of steel spiritually,
that otherwise cannot be got over, run through, nor broken.
Oh! what is too hard, for those who are in this true and saving faith?

The author to the Hebrews, in the eleventh chapter, verse thirty-second,
having spoken largely of the fruits and effects of faith, saith, "`What shall I say more?
for the time would fail me to tell of Gideon, and of Barak, and of Sampson,
and of Jephtha, of David, and also of Samuel, and of the prophets;
who through faith subdued kingdoms; wrought righteousness; obtained promises;
stopped the mouths of lions; quenched the violence of fire;
escaped the edge of the sword; out of weakness, were made strong:
women received their dead raised to life again; and others were tortured,
not accepting deliverance, that they might obtain a better resurrection;
and others had trials of cruel mockings, and scourgings; yea, moreover,
of bonds and imprisonment; they were stoned, they were sawn asunder, were tempted,
were slain with the sword, they wandered about in sheep-skins, and goat-skins,
being destitute, afflicted, tormented, of whom the world was not worthy;
they wandered in deserts and in mountains, and in dens and caves of the earth,
and these all have obtained a good report through faith.`"

So dear Friends, wherever this may come, unto whom the salutation of my life reacheth,
try yourselves, prove yourselves, that you may know whether you be in this faith or not,
whereby all these blessed effects are wrought and brought to pass, and many more,
to the making perfect throughout.
Let none content or satisfy yourselves with the
word faith or with the bare profession of faith;
but carefully mind what Christ Jesus our Lord saith,
"`If thou hast faith as a grain of mustard seed, thou shalt say unto this mountain,
be thou removed, and it shall be so.`"
If faith in this small measure or degree, through the blessed effects of it,
be thus powerful, or those whose faith is no more, thus gain the victory,
how much more victory shall those obtain that keep it unto the end;
for it is those who finish in that same faith in which they begun, who shall be saved,
and for whom the crown of life and immortal glory is laid up.

But some who are young in the truth,
and whom the enemy may bear hard upon by temptations, may say,
I thought I had faith in some measure,
and yet those things stand in my way like mountains, that I cannot get over as yet,
and great oppositions and temptations I meet with, both within and without,
that prevail with me.

Dear Friend, in much tenderness my soul breathes unto the Lord for thy deliverance;
and in order that thou mayest be delivered from that which so oppresses thee in spirit,
or stands in thy way, mark well what I say unto thee, thou willest too much,
and through thy willing thou wouldest run too fast, and make too much haste,
striving to get over things,
which is the great cause why thou comest short of obtaining victory through faith;
and that thou dost not come to know the blessed effects or work of it in thy heart.
Remember the counsel given to Israel of old, "`Thy strength, O Israel,
is to stand still.`"
True strength, and victory through faith,
over and against the enemies both within and without, is in standing still,
and being quiet and cool in thy mind; for as the Scriptures of Truth testify,
it is certainly true, It is not in him that wills nor runs;
the battle is not unto the strong, nor the race to the swift.
And Christ saith.
Which of you by taking thought can add one cubit to your stature?
Stand still and patiently wait to receive the power
which the Lord will give to all in his own time,
not in theirs, who patiently wait for it,
that so patience in thee may have its perfect work,
and thou mayest have the victory given to thee, over all the temptations of the enemy,
through faith in the power of God,
and so will all those things come to be removed out of thy way,
that thou standest questioning and reasoning about.
True faith gives victory, and is known by the blessed effects of it;
and as the apostle said, This is the victory that overcometh the world, even our faith;
and this is the way to know an anchoring and establishing upon the sure rock,
through faith and hope, which never make ashamed.

And now, dear Friends, unto all you whom God in and through Christ Jesus his Son,
hath not only called to believe in his name,
but also to suffer for truth and righteousness sake;
blessed and happy of the Lord shall you be, if you continue unto the end.
You have a true knowledge and right understanding,
that your suffering is for truth and righteousness sake, for Christ`'s sake,
as those that are his, whom he hath redeemed, and saved, and sanctified by his blood,
death and suffering.
You are not your own, nor anything you have or enjoy,
that your suffering may be for Christ your Redeemer, your Saviour, your Shepherd,
Counsellor, King, Priest, and Law-giver, and so for righteousness sake, as those,
who because of the tenderness of their consciences cannot do, nor consent to have done,
that which is unrighteous, unjust, or unlawful, according to the righteous law of God.

Blessed and happy are all you whose suffering is on this wise;
for it is not only what any suffers, whether in body or goods,
that will tend to bring the recompense of reward home to the comfort and joy of the soul,
as a confirming encouragement in suffering;
but also that you all know for what you suffer, to wit, the name, the power, the truth,
in the Seed Christ.
Here is true ease, true peace, and quietness in spirit under suffering;
this makes the yoke easy, and the burden light,
and the blessed recompense of reward from the hand of
God cometh unto all such an hundred fold in this life,
and such also shall inherit life everlasting, as Christ Jesus our Lord said unto Peter,
Where there is a willingness to forsake father, or mother, wife or children,
houses or lands for his name sake, this shall be their reward.

So dear Friends,
my counsel and advice unto you all is that you all be truly careful what you suffer for,
that none may have only a name to live, and be dead;
but as those who have faith in Christ, and are in a spiritual travail;
for if any one suffer in body or goods, and not in the truth,
that will be a sad comfortless suffering.

While as a great mercy from God,
you have yet health and liberty to meet together to worship and serve him,
be faithful in meeting often together, first-day and week-day,
in men and women`'s meetings; and when met, be diligent in waiting upon him,
to receive of his living power from time to time.
This is that which truly fits, furnishes and prepares in every good word,
work and service.
Make good use of time, in being truly careful how you spend it,
for it is the ill use made of time, or the careless squandering away of it,
that makes many unfit for a time of trial, when called thereunto.
Remember, the ten virgins all had lamps, but five wanted oil,
and it is said their lamps were gone out.
It seems they once did shine; and they were all called to prepare,
but the five foolish wanted oil, and so were left behind,
and the door was shut against their entering into rest, and partaking of joy,
because of their unwatchfulness, in the time they had given them;
and although they came calling and crying afterward, it was to no purpose,
the door was shut.
It is plain there was a time when the door was open, when the wise,
who had both the lamps and oil, entered in; therefore all be upon your watch continually,
with a care to have oil in your lamps, that you may enter into the place of rest,
where you shall partake of joy unspeakable and full of glory,
as in a habitation of safety, where none can make afraid.
If the storm or tempestuous trial last long, you shall never want for bread,
but it will be sure, and your water will never fail; for He,
for whose name sake ye suffer, will spread your table, fill your cup,
and maintain your cause.
There your communion will be sweet with the Lord,
and your unity and fellowship will be very comfortable,
that you will have with all his faithful suffering people.

This is the counsel and advice of your brother, in tender love,
that all who suffer by oppression for truth and righteousness sake,
it may be in this manner,
that so you all may have cause of great encouragement under suffering,
whether in body or goods, which I can give in truth by good experience,
who have had my own goods spoiled, and my body imprisoned time after time,
and now am a prisoner,
because for conscience sake I cannot uphold that great oppression of tithes.
In the same day and hour I was to go to prison, were the spoilers carrying away my goods,
for no greater crime than worshipping and serving the Lord my God; and oh! the joy,
gladness, and rejoicing that was in my heart,
because I was truly sensible of the cause wherefore I suffered.
My joy was unutterable under this consideration,
that the Lord my God should not only count me worthy to believe in his name,
but also to suffer for the same.
Christ Jesus the Son of the Father`'s love suffered to save and redeem my soul;
and therefore should not I willingly offer up all I had and did enjoy,
in answer to what God, through Christ his Son, had done for me?
Yea surely, I said in my heart, I will offer up all freely.
I speak to his praise and glory, and the encouragement of all faithful willing sufferers,
whose suffering will never be wearisome nor tedious unto you;
no murmuring nor complaining will have room in any such heart, as to say or think,
How shall I live?
Or how shall my wife and children be maintained?
Or my business be carried on?
For though we are not to be void of an honest care in those things,
yet not to murmur because of the suffering.

What! is not God Almighty all-sufficient for the soul?
And must not he be relied upon, through Christ his Son, our Lord,
for the salvation thereof?
And is not he that is all-sufficient for the soul, sufficient for the body also?
Yea, assuredly, by living experience can my soul say, And is not the earth the Lord`'s,
and the fulness thereof?
And cannot he take and give according to his good will and pleasure?

Let all remember the patience of Job in retaining his integrity,
in his deep affliction and suffering, both in goods and body,
whose wife gave him bad counsel, saying, Wilt thou always retain thine integrity?
Curse God, and die: But he refused it, and reproved her;
and suffered the loss of his thousands of sheep and camels, and hundreds of oxen;
and all his children and servants; yet the Lord restored him double, so that it is said,
The latter end of Job, was far more happy and blessed than the beginning.

Oh! that all who are called to suffer may be careful to refuse evil counsel,
given either by wife or husband, kinsfolk or relations,
who would persuade them to requite the Lord evil for good,
and desert their testimony in suffering; such who would give counsel on this wise,
This is but a small matter, and the other is but a little thing;
thou mayest do it well enough, or suffer another to do it for thee: Nay,
saith the honest-hearted and true to God,
I must first be faithful in the little and then
my Lord and Master will make me ruler over more;
and that which I cannot for conscience sake do myself,
I cannot suffer any connivingly to do for me, for this is hypocrisy and dissimulation.

Oh! what encouragement have all the faithful in suffering,
to trust the Lord with all they have and enjoy, and to consider the patience of Job;
the faithfulness of Daniel; and the faith, courage, and nobility of Shadrach,
Meshach and Abednego.
Daniel could not but open his window, and pray to his God,
though a decree was made to cast him into the den of lions,
but the angel of the Lord`'s presence shut their mouths, and preserved Daniel,
the servant of the living God; as the king called him, when he saw his faithfulness.

The kings and rulers of the earth, with many people, are made to confess,
We are the people of God indeed; when they see us stand faithful in our testimony,
as Nebuchadnezzar was made to call the three servants of the Lord,
Come forth ye servants of the Most High God; although he threatened then,
as some in our times, that, If they would not fall down,
and worship the image he had set up, they should be cast into the fiery furnace,
seven times hotter than ever;
and who is that God that shall be able to deliver out of my hand?
Yet as the Lord had then, so he hath a way now,
to deliver all whose trust and confidence is in him,
beyond the expectation of wicked and cruel men, notwithstanding their fury.
Shadrach, Meshach and Abednego said, "`Be it known unto thee, O king,
we will not serve thy gods,
for our God whom we serve is able to deliver us from the burning fiery furnace;
and if not, we are not careful to answer thee in this matter.`"
And because they could not bow to the king`'s image,
at the sounding of several sorts of instruments of music,
they were bound and cast into the burning fire, with their coats, hosen, and hats;
and the flame of the furnace was so great, that those men that cast them in,
were slain thereby;
but not so much as one hair of the three faithful servants of the Lord was singed,
nor the smell of fire found on their clothes.

What great encouragement is here, for all who in any measure know God,
to believe and trust in him in suffering, whether in body or goods, though ever so deep;
for hereby it is evident that the Lord always had, and hath a true regard to his people,
and the more need they stand in of him, so accordingly he appears,
and works their deliverance, according to that saying,
"`The rod of the wicked shall not always rest upon the lot of the righteous.`"
Not only so,
but he brings plagues and judgments upon the heads of
the persecutors and afflictors of his faithful ones;
"`One hair of whose head,`" saith Christ,
"`shall not fall to the ground without your Father`'s notice.`"

When Herod the king, the troubler of the church, killed James,
and because it pleased the Jews, took Peter also, and put him in prison,
intending to bring him forth to the people; that same night,
although Peter lay bound in prison with two chains between two soldiers,
an angel from God came upon him, and loosed his chains,
and caused the iron gate to open of its own accord.
And Paul and Silas, who were put in the inward prison,
after they had been beaten and sorely abused, and their feet fastened in the stocks,
prayed and sang praises unto God at midnight;
and such was the wonderful appearance of the great power of the mighty God,
which caused the prison doors to open, that it is said,
The foundations of the prison were shaken; and when the jailer waked,
he thought to have killed himself, seeing the doors open,
supposing the prisoners had been fled; but Paul said, "`Do thyself no harm,
we are all here;`" and he came trembling, when he perceived what was done, and said,
"`What shall I do to be saved?`"
and Paul and Silas spoke unto him the word of the Lord,
and bid him believe in the Lord Jesus Christ, and he should be saved;
and he and all his house believed.

There is great encouragement for all faithful honest-hearted Friends, under suffering,
to go on in all faithfulness, freely giving up life and liberty,
and all into the Lord`'s hand, willing to cast their care,
and put their confidence in Him, who hath all power in his own hand,
to bring to pass whatsoever seems good in his eyes.
The wicked many times in the height of their wickedness are frustrated, and God`'s people,
beyond all expectation, preserved and delivered;
of which you yourselves have many times been made living witnesses; hold it fast,
dear Friends, in your remembrance.

And you may also see when there is a giving up freely to what the Lord requires,
through the might of his power people`'s hearts and consciences are reached,
causing them to tremble, whereby good desires are begotten and the query raised,
What shall we do to be saved;
though before they have been persecutors and afflictors of God`'s people.
They whose care it is thus to walk and show forth a
godly conversation and example in doing or suffering,
so as to reach to the witness of God in people`'s consciences, though in the inner prison,
as Paul and Silas were, have not only cause to bless and praise the holy name of God,
for accompanying them by the angel of his presence,
but also to sing and make melody unto him in their hearts.

Dear Friends and suffering brethren,
though the Lord our God see it good to try your faith and patience,
to see how you will trust in him, in the hour of temptation and time of trial,
and men are permitted to take your goods,
and also separate you from your nearest relations, your dear wives and tender children,
and put you in prison; yet this is your joy and comfort,
being sensible of the cause wherefore you suffer,
and that man with all his power and rage,
cannot separate you from the pure enjoyment of the presence of the Lord;
but it reaches unto his dear suffering lambs, though in a dungeon.
If it were not so, we were most miserable;
but now above all people we are blessed and happy; blessed and praised,
and magnified forevermore be the holy name, and great power of our God,
by which he doth carry through all his faithful children and people;
for he is forever worthy of all praise, honour and glory: unto him alone be it given,
both now and forevermore.
Amen.

Dear Friends, put on courage and boldness, in the name, fear and power of the Most High,
as an armour, faithfully to follow your Captain, the Lord Jesus Christ,
who will never leave you nor forsake you, except you first leave him,
who will lead through good and bad report, fire and water,
and in every trouble and exercise, will be your preserver,
who upholds all by his word and power.
In faithfulness follow your Leader whithersoever he goes;
for as you with diligence follow him, he will bring you forth in his own time;
and happy are they that patiently wait till then though
in as great trial as ever any of his people suffered.
Yet, if you be steadfast in the faith, he will bring you forth,
and make you more bright and pure, holy and clean; for the fiery trial makes so;
concerning which, as the apostle Peter said, "`Think it not strange,
concerning the fiery trial which is to try you,
as though some strange thing happened unto you: but rejoice,
inasmuch as ye are partakers of Christ`'s sufferings; that,
when his glory shall be revealed,
ye may be glad also with exceeding joy:`" So a true and faithful testimony,
whether in doing or suffering, in body or goods, may be borne unto the truth,
and for God, and his pure holy worship, and against all oppression and unrighteousness,
that the same may be left upon record to after ages as a confirmation to their faith,
and may tend to their encouragement;
as the example of those faithful witnesses who have already
finished their course in the faith of our Lord Jesus Christ,
and are gone to their rest, doth greatly tend to strengthen the faith,
and encourage those who are now travelling in the same way.

In that same love, pure life, and true tenderness, into which at first you were begotten,
and raised to bear a faithful testimony for the Lord, his truth and glory,
though but in little things, when nothing was too near or dear for you to part with,
may you all persevere; that He who was known to be the first, may carefully be kept unto,
and be known to be the last; the Alpha, and the Omega; the beginning and the ending;
the same today, yesterday, and forever; who is from everlasting, to everlasting;
that so the crown of life and immortal glory may be set upon your heads,
which is laid up in store for all who in faithfulness continue unto the end: Unto which,
the Lord God of life, by and through the greatness of his own power,
preserve you all faithful in life, and unto death.
Amen.

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
From my prison-house, in Carlisle, in Cumberland, the 17th of the Fifth month, 1684.

[.blurb]
=== An Exhortation to Friends, etc.

[.salutation]
Dear Friends,

Many have been the mercies, privileges and deliverances,
of which the Lord your God hath made you rich partakers, as you have stood faithful,
ever since he gathered you out of the world, by an arm of mighty power stretched forth.

And first of all, let me put you in mind of his love and good-will towards you,
in so calling and gathering you; and it hath been through his fatherly care over you,
that you have been preserved until now.
Forever prize the same, in all humility before Him, for he is worthy.

And now, dear Friends,
you know the good end of the Lord in calling and gathering you to be a people to himself,
was not only, that you should believe in his name,
but that you should also suffer for truth and righteousness.
And a great work the Lord hath wrought in you, and also for you,
by his power and holy Spirit of Life, in order to prepare and furnish you,
and give you strength, that you might run the race set before you,
without wearisomeness or fainting;
where you meet with many conflicts by the enemy within, and deep exercises,
and hard trials without, so that the saying is fulfilled in you;
Through many tribulations you must enter the kingdom: And yet,
notwithstanding the danger on every hand, that caused fear and trembling sometimes;
and notwithstanding the rod of the wicked was laid heavy,
and with sharp strokes upon you; yet through all, the Lord your God,
by the same power with which he gathered you, and brought you through all these things,
hath wrought your deliverance, and brought you to your desired haven.

And these the mercies, favours, and deliverances which you received from His hand,
are never to be forgotten.
Many times they were little expected, either inwardly, or outwardly;
and in both respects, when your travel and exercise was great;
when a little peace was given, and ease from burdens felt,
how sweet and precious was this unto you;
and how did it tend to humble you before the Lord, and lay you low before him,
to the renewing of your fellowship and communion with him, and one with another.

Dear Friends, always keep these things in your remembrance,
that like so many good householders,
you may be found bringing forth out of the good treasure of your heart,
things both new and old, and yet all sweet and savoury.

O the inexpressible love and kindness of the Most High! in calling and gathering you,
in quickening and giving life unto you, by his eternal spirit and power,
and in causing his heavenly light to shine out of the darkness,
to give you to see your way out of the same; in which waiting,
you might witness life more and more.
And great was his love and Fatherly care, in feeding, refreshing, and nourishing you;
causing his gracious showers to fall upon you, his plantation,
that the seed of life and righteousness might grow in you, in freshness and tenderness.

Oh, the love, mercy, and good-will of your God unto you,
who have stood faithful in your testimony-bearing, for him and his pure truth:
In the day of your trial, he hath borne up your heads, over all his and your enemies,
that you might not sink in the midst of troubles; and hath filled your cups,
and maintained your cause,
and returned an hundred fold of joy and peace into your bosoms,
even when the body was in prison, and the goods spoiled, and husband separated from wife,
and wife from husband, sometimes unto death: hath not the Lord, in all these things,
been as a husband unto the widow; and more to the wife,
than she could either ask or think; and as a father unto the fatherless children;
and in the time, when as to outward appearance, you might have wept and mourned,
because of your deep exercises,
have not you even then been made to rejoice and give praises unto God,
who did not only count you worthy to believe in his name,
but to suffer for truth and righteousness, and say with patient Job also, The Lord gives,
and takes away, etc., or suffers it to come so to pass:
blessed and praised be his holy name, and great power forevermore.

Oh Friends! let these things be had in remembrance by you, while you have a being.
For how hath the Lord gone before you as a King and Captain, to lead you on,
who have counted nothing too near nor dear to part with,
that in faithfulness you might freely and fully follow him, as Caleb and Joshua did,
notwithstanding the winds and tempests.
And how hath he also followed you with his mercies, blessings and favours,
when great spoil and havoc hath been made of your goods,
and of what the earth brought forth and afforded you; yea,
how hath the Lord caused these things to grow and increase again abundantly,
so that you have had good cause to say, You have been blessed in basket and in store;
and though some have had but little, yet having meat, drink, and clothing,
let such therewith be content, for so we learn by the teachings of the grace of God,
which is sufficient in all states and conditions.

Dear Friends, let these things come often under your consideration,
when you lie down and rise up, go forth and come in;
so shall you feel your spirits wrought more and more into true tenderness and brokenness,
to lay to heart what the Lord hath done since his heavenly day dawned.
May not I say to such as can read and understand.
One hath chased a thousand, and two put ten thousand to flight: the work is the Lord`'s,
the praise and glory thereof belongs unto him, to whom it is due,
both now and forevermore.
Amen.

And now, dear Friends, the Lord in his kindness and good-will to you,
after a long time of cruel sufferings, tribulations and deep exercises,
hath suffered a day of ease and liberty to come unto you,
according to the desire of your hearts;
which was not to be expected as to outward appearance,
which hath freed you from your suffering condition, both in body and goods,
in many places.
And although it doth not reach to free me from my bonds, yet the Lord knows,
I am truly content with my condition,
and no more weary than I was the first day I entered the same: and my heart is glad,
and my soul rejoiceth, upon the account of what is extended unto many Friends.

One hour of such a day and time, once, by many, would have been greatly valued,
when prisons were full, houses and shops broken up, goods spoiled,
and meetings greatly disquieted by wicked informers, and others;
surely such a day as now is, or one hour of it,
would have been greatly prized as a mercy from the Lord,
and no doubt was much desired by many,
and laboured for with much care and diligence by others.

And is the day and time now come and yet continued, how long, I shall leave to the Lord,
of so large liberty and freedom as I need not to mention;
and is it not prized by all as a great mercy, favour, and deliverance,
seeing that many prison doors are set open, and the wife enjoys her husband again,
and children their parents,
and our meetings are continued unto us in a most peaceable manner:
praises to God on high forever.
I say, is not this prized by all?
I hope it is by many; and my desire is, it might be by all; for what a pity were it,
that such a rich mercy should be undervalued by any,
or not considered and prized according to the worth of it, or what it may produce,
if made right use of.

But I fear, and have a godly jealousy,
that there are some who are so inconsiderate and unmindful of the mercies of the Lord,
that they rather requite him evil than good herein.

Oh! let all take heed and beware, that because of the present time of liberty and ease,
none may take more ease and liberty unto yourselves, in meeting, or out of meeting,
than becomes those professing truth: No--no more ought you to take,
than if it were a day of trial and deep exercise;
for still you have an unwearied enemy to war with,
that neglects no opportunity which may make for his purpose,
by many temptations within and evil counsellors without.

And though it be not now a time for him and his,
to rage and roar as though they would devour all at once,
yet he will be creeping now in his cunning and subtlety
more mysteriously and hiddenly to darken within,
to hurt and hinder your growth in the truth,
by presenting some delightful object without; and there is no way to have him discovered,
nor to receive power against him, but by waiting and watching with diligence,
and true fear, in the pure light of the Son of God.
Therein power is received, whereby the power of darkness is trod down, and kept under;
so that he will be known to rule and reign, whose right it is,
who is God over all heaven and the whole earth, blessed forevermore.

It is the work of the prince and power of the air, that evil spirit,
where it gets place and rules, to do what hurt it can amongst the tender plants of God,
to hinder the work of God;
as that rending spirit of separation in those that entertained it,
hath used all its cunning craftiness, by creeping in the dark, to hurt and spoil within,
and so make breaches and separations without.
For it is plain and evident, which may greatly tend to confirm all Friends against it,
and to convince those that are of it, that this spirit and power,
which pretends to be the Spirit of Truth and power of God,
is not the Spirit of Truth nor the power of God; for though such be preachers,
they never have been instrumental since they were joined with it, I am fully persuaded,
to convince any of sin, or gather any out of the world.
Their work has been, and still is, to deceive the simple, and the wise and rich,
who love ease and pleasure more than God, his truth and people,
and are got into a false liberty and looseness, because they love not to bear the cross,
and live in self-denial; and because they who are of that spirit,
like ease and liberty to the flesh and carnal mind.
This present juncture of time might have served them to work in,
but that they have already so far manifested what spirit they are of,
to all whose eyes are open, by flying and hiding themselves in the time of persecution,
and keeping Friends out of their meeting-houses.
So that now they can do little more harm, though they creep here and there;
for that serpentine-spirit hath shot its sting, and spent the greatest of its strength,
so that any child of God now may tread upon it, without hurt or danger.

Dear Friends, how can it otherwise be, but all those things, rightly considered,
shall greatly tend to confirm your faith against it, never any more to touch with it,
nor them that are of it, and also open the eyes of others, taken as in a snare,
to break the snare and come forth from them who are of that spirit,
that such may be restored and healed: As many as have escaped,
let them prize God`'s love therein forever.

I say, they have never, since they received that spirit I have described,
been instrumental to convince any of sin, or gather any out of the world to God;
so it is plain such are none of his sending, nor preparing: no ministers of Christ,
but of him that is opposite to Christ,
speaking from a dark power and spirit which gathers into the darkness,
out from the true light, where people cannot see the true way.

For the work of the true ministers of the everlasting
Gospel is still to gather from darkness,
into the true light and life, and so into the heavenly Man,
who was before the power of darkness was, Christ Jesus the power of God, there to live,
move, and have a being; where this earthly, separating, rending spirit cannot come,
for it hath its power from below, out of the pit of darkness,
where its habitation and dwelling-place is; out of which the Lord God of life,
keep and preserve you all, my dear Friends, in your habitations of light,
there forevermore to live and dwell.

Let all take heed and beware of the deceitfulness of the enemy`'s workings in the dark,
who from the beginning still wrought man`'s misery by getting an entrance by his lies,
contrary to the knowledge God gives by his light and grace.
He undoubtedly will now persuade to fleshly ease, careless security, worldly-mindedness,
to seek self and its interest, if the watch be not carefully kept.
For want of this, darkness enters, deadness comes over them,
and a spirit of slumber takes place, which is both a thief and a robber;
and the Spirit of Truth not being minded, to lead and guide,
the spirit of the world gets in, and draws, and leads into the earth and earthly things;
and instead of labouring to be rich in faith and good works towards God,
such labour chiefly how to grow rich in the world,
that they may have great substance to leave, they know not to whom.

And all this darkness and insensibleness comes for want of waiting
and watching with diligence in the light of Jesus Christ,
the ancient and standing principle of truth,
and because the daily cross to the will and mind that leads out,
is not borne and lived in.

And some, for want of a rightly prizing and valuing the present mercy,
so largely enjoyed, suffer a high mind to rule them, which leads above the fear of God,
and out of a sense and feeling of the pure truth in themselves, and so walk not orderly.

Dear Friends everywhere, as wise men and women, have a care in the fear of God,
and in love to his truth, as those who are ordered and guided in his wisdom,
that all people may see you are no more heightened, because of peace and liberty,
than cast down in a day of trial: but that all may behold your good conversation,
coupled with fear, that you are as those bowed before the Lord,
under a deep sense of his present mercy, not forgetting those heretofore received.
For although the Lord may be pleased to make man instrumental in this or any other thing,
it is unto him alone, who is the Author and Original of all good,
that you are to return the praise, honour, and glory forever;
though we would not withhold that from man which is his due who is found doing well,
which is acceptable with God, and worthy of commendation and praise by all his people,
who desire their continuance therein.

And dear Friends, as you are preserved before the Lord and all people,
you will be of the blessed apostle`'s persuasion; who says,
I am persuaded that neither life nor death, principalities nor powers; things present,
nor yet that which is to come,
shall be able to separate me from the love of God that is in Christ Jesus.
So let all take heed, and keep low in the even way, the middle path, where no extreme is,
where you will be kept humble and meek.
It is such the Lord teacheth to prize and value
every mercy and favour they receive from him.

It is very rarely those prize liberty and ease to the worth thereof,
who never knew bonds, trouble, and suffering: Yea, it is as rare in such,
as for a man and woman to prize health and strength,
who scarcely ever knew sickness or weakness; or for those to prize the worth of bread,
who never knew the want of it.

It is those chiefly,
who have borne the heavy burden of imprisonment and spoiling of goods,
and have been straitly confined to the impairing of their health,
who are ready to cry out and say,
How deeply are we engaged unto the Lord for the
enjoyment of this mercy of so large liberty and freedom.

Oh that you may never forget of the same,
though I know the honest-hearted who have their eye to God, and love him,
his truth and people above all, though never called to suffer,
are ready often to say in their hearts;
Though I have never been exercised as other of my friends,
yet I cannot but be mindful of their suffering condition; and when they suffer,
I suffer with them, and when they are freed, eased, or at liberty, I am made truly glad;
so that I am engaged with them, to praise the Lord for such a favour.

And the blessed effects produced by duly prizing the
mercies and favours received from the Lord are,
walking worthy of his love manifested to us, and valuing the same,
which engageth the Lord to give us more abundantly thereof,
and constrains us to love him again, and to double our diligence.
These are so far from taking more liberty to themselves,
because of the liberty that is given,
that they find themselves the more engaged to meet
often amongst God`'s people in all their meetings,
not only for worship, but men and women`'s meetings to do service there for him,
his truth and people.
But ease and liberty, not made right use of,
bring forth little but idleness and unprofitableness,
which render men unfit to do service for God.

Dear Friends, in the name of the Lord go on, and let none sit down by the way,
but in faithfulness follow your Captain, the Lord Jesus Christ,
who never leaves nor forsakes those who follow him, that you may have good cause to say,
as those who have made right use of the day of God`'s love and mercy,
in giving ease and liberty, as well as when exercised in and under suffering,
"`come what will come, the will of the Lord be done.`"

And all who make not use of this day`'s mercy for that end and
purpose wherefore the Lord hath suffered it to come to pass,
which is to engage and establish his faithful people,
it will rise up in judgment against them.

Brethren and sisters everywhere,
all be awakened unto righteousness to serve the living God,
as you ought to worship and serve him, which is with all your hearts,
your might and your strength, and with all you have and do enjoy,
which is the Lord`'s. The Lord God of Israel keep and preserve
you faithful in serving Him and one another in love,
for the increase of life and unity amongst you;
is the supplication and travail of my soul unto the Lord on your behalf,
into whose blessed and Fatherly protection I commit you all;
to be kept where safety and preservation is forevermore.

Who am your friend and brother, in the living and precious truth,
though a sufferer in outward bonds, for the testimony of Jesus, and of a good conscience.

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
From my prison-house, in Carlisle, in Cumberland, the 8th day of the Seventh month, 1687.

[.blurb]
=== A General Epistle to the Flock of God, but More Particularly, in Cumberland.

[.salutation]
Dear Friends and Brethren,

Look to the rock from whence ye were hewn,
and to the hole of the pit from whence ye were digged; that is to say,
never forget from whence you came, no more than to what degree you are attained;
what you were when the Lord first visited you; and what you still are of yourselves,
without the assistance of his power; hold this fast in your remembrance,
and it will greatly tend to humble you, and keep you little and low in your own eyes,
in true self-denial: so shall the Lord alone be exalted,
and his glorious power extolled over all.

It was the Lord who visited us with the dayspring of his love from on high,
by the shining forth of his glorious light, in a land of darkness,
a country where there was a famine, not of bread nor water,
but of the preaching of the Gospel; and brought us to a country,
where light and life are, and that flows with milk and honey.
Forget not the way of your soul`'s travel; and you that have not known it yet,
must tread the same path, before you can come to be sharers with those who have so done;
who have known what it was when they entered on their journey,
or the beginning of the work, to drink a bitter cup, even the cup of judgment,
to bring down and burn up all that was contrary; and as a sword to slay the enmity,
and of twain to make one new man.

Then was the day of weeping, and mourning, and trembling;
then did the earth tremble at the presence of the Lord.
The way of Zion`'s redemption being through judgment, love it still,
and dwell in a sense of it to the end, and the enemy shall never prevail against you;
dwelling in Him to whom all judgment is committed, both in heaven and in earth,
in Christ, the light, the life, and the quickening spirit.

Dear Friends, in a sense of the tendering love of God, let me ask you,
who delivered and saved you, who hath kept and preserved you until now?
Surely you can say with my soul, the Lord alone by his own power and strength;
which he hath never failed to show for those that trust in Him.
Therefore trust therein, and keep thereto, unto the end, and you shall be eternally happy.

And as you have known the travail of your souls, in passing from death to life,
and out of darkness into light,
which is the path that the younger generation who are coming up must tread in,
you can tell them by experience, for their encouragement,
that the Lord will never leave them nor forsake them,
if they follow him in the way of his judgments, which he mixeth with mercy,
and which must be owned and loved, to bring down self,
and whatever would exalt itself above the pure witness.
You can tell them, that when your hands did hang down,
and your knees smote one against another;
so that sometimes your hearts were fearful whether they
should ever be lifted up or strengthened again;
yet having faith,
and being taught by the grace of God to have patience also to wait the Lord`'s time,
he has appeared to lift up the weak hands, and strengthen the feeble knees,
and make the fearful heart strong by the might of his power.

Yea, the Lord hath often wrought your deliverance, and done wonderful things for you,
beyond what you then could see, so that you have been ready to say,
I hope I shall never meet with such exercises, trials and temptations as heretofore.
Yet if anything of self was set up, to glory above what was meet,
because of what the Lord had done for you; hath not the only wise God seen it good,
after all this, to try and prove you again, both without and within,
that you might be kept truly humble and low before him, always depending upon his power,
and on nothing of your own.
Hath he not seen meet to try your faith and patience,
and for a time hath hid his face from you;
and given you but little either of spiritual bread or water; insomuch,
that because of your weakness and faintness,
the enemy hath been very busy to tempt you to despair
of the sufficiency of the power and mercy of the Lord,
or to turn you aside from the way of truth,
using all his subtlety to keep you from calling to mind how
the Lord heretofore brought you over mountains and high hills,
and levelled them all before you.
And your hopes sometimes have been so faint, that some of you have been ready to say,
with one in the days of old, "`Lord, hast thou forgotten to be gracious!`"

And yet has not the Lord, after all this and much more,
renewed your hope and strength again, and by the glorious appearance of his heavenly Sun,
hath broken forth and shined in your hearts,
clearly discovering to you the enemy`'s wiles and working,
with all the mists and darkness he brings in with him, and driving away the same,
through the power that is received in the light, even the light of life.
Thereby you see what hath been the cause of your being so exercised,
so long after your convincement; and after you have known many deliverances,
and watering-showers, and fruitful seasons;
yet now are brought to judgment and the sentence of condemnation;
that all which is of self, in which the enemy works to the hurt of the soul,
may be slain with the sword of the spirit, which is the Word of God,
and consumed with the fire of the Lord.

Thus hath the only wise God taught you by his holy Spirit,
and thereby you have learned experience and spiritual skill,
how to come to his judgment seat, that you might come to his mercy seat also;
that so you might know the way of your soul`'s travel, from death to life,
through weeping and mourning, to joy and gladness, through poverty and weakness,
to feed at the table of the Lord; and come to have your strength daily renewed,
to sit in heavenly places in Christ Jesus, in that rest prepared of God in Him,
where his glory shines in your dwellings,
which will make you to shine as the stars of heaven,
as you keep your station in inward watchfulness and waiting in the light.

When the mind is stayed there, it is immoveable,
for its stay and strength is the sure rock and foundation of God,
his great and glorious power, out of which, both the water and honey proceed.
O the divine sweetness that is in it!
Who can set forth the greatness, the goodness, and excellency thereof?

You know, dear brethren and sisters, that our souls many times when together,
have been made rich partakers of the same,
in the enjoyment of the life-giving presence of our God,
and made near and dear one to another;
when we have been so filled with the wine of his kingdom,
that tears of joy have often run, which have far exceeded the tears of our sorrow.

Dear Friends, whom my soul loveth in all true tenderness,
and unto whom I am inseparably joined; in the unity of the spirit,
my heart is full of love and life, which flows from the living Fountain;
with desires for your eternal good.
That you ancient ones, whose time cannot be long here,
may finish in that in which you began, in freshness, and true tenderness,
and receive the crown, that so it may be well with you forevermore.

And that you who are younger in the truth, and also in years,
may not please yourselves with long life, nor yet with worldly preferment;
but wait with all diligence and true fear, to feel the work of the converting,
heart-tendering power of the great and mighty God, to work a true change in you, in body,
soul, and spirit; that so it may be well with you, when death looks you in the face.

And my dear ancient Friends, be careful that you never forget,
nor depart from your first love and tenderness;
and all you younger who have not so fully known it, wait diligently for it,
that you may know the blessed effects of it, as the ancients have done,
that through the fear of God placed in the heart,
and an awe and dread of offending the Lord, you may come to say with them;
Oh! that I may never speak a word, nor do any action that may grieve his good spirit,
nor break my peace with him.
May I neither eat nor drink to excess,
nor wear anything in apparel contrary to the pure truth,
neither be found in any carriage or behaviour, in conversation or communication,
that may give any occasion, or whereby truth may suffer.
This was and is the desire, and cry of all the faithful,
and of those that truly fear the Lord, and have known what the first love is,
and the blessed effects of it.

This was a time when nothing was valued like the truth; and it is so still,
with all who love truth and righteousness.
No hardship, no scoffing, no scorn, no reproach for the name of Jesus, no suffering,
no spoiling of goods, nor imprisonment of body, neither principalities nor powers,
things present, nor things to come, shall be able to separate such from the love of God,
which is in Christ Jesus our Lord.

All these, and much more than I am able to express,
were the effects of your first love and true tenderness that was begotten in you thereby.
Keep to it, live in it, and never depart from it, nor forget it;
that so you may continue unto the end, in that in which you have begun;
as those whom the Lord in his love and by his power, hath thus far preserved,
so shall you be everlastingly happy, when time here shall be no more.

Dear Friends, were we the wisest, the greatest, the mightiest,
or richest among the sons and daughters of men?
Most of us were such as were accounted foolish, weak, mean and contemptible,
like the Jews in the days of the prophet Nehemiah,
who were called feeble by the enemies of God, and of his people,
who mocked and laughed them to scorn, and said, What do these feeble Jews?
not knowing what work the Lord hath determined to do by
them in answer to the prayer of the prophet.

He hath done great and wonderful things in this
his days through the might of his own power,
by those whom he hath called and chosen out of the world, though counted weak and feeble,
yet made strong, through his renewing of their strength.
Here is encouragement given by our Lord and Master Jesus Christ,
for all true believers and faithful followers of him, through many tribulations:
"`Behold,`" saith Christ, "`I give unto you power to tread on serpents and scorpions,
and over all the power of the enemy, and nothing by any means shall hurt you:
notwithstanding, in this rejoice not, that the spirits are subject unto you;
but rather rejoice that your names are written in heaven.
In that hour Jesus rejoiced in spirit, and said, I thank thee, O Father,
Lord of heaven and earth, that thou hast hid these things from the wise and prudent,
and hast revealed them unto babes, even so Father, for so it seemed good in thy sight.`"

What remains for you then to say; Oh saith the truly humbled,
what manner of love is this wherewith the Lord my God hath loved me, and visited my soul?
And most especially, in a day when I was an enemy in my mind to him by wicked works.
I am constrained to love him again, and to fear him always,
that I may in no wise offend Him, so good and gracious a God,
so dear and tender a Father, who hath dealt so kindly with me,
not according to my desert, for I was unworthy that his love should reach unto me.

And such were we.
Yet, notwithstanding all this, and much more, hath the Lord,
with whom there is no respect of persons, loved us freely,
in a time never to be forgotten.
Oh! be humbled, and laid low before him, under the sense of his love,
that our hearts may be often broken, and tendered thereby;
for if the love of God doth not work this effect, nothing can.
But all who, in true fear, dwell in a sense of what the Lord hath done for them;
the secret cry of their soul is.
Oh!
I can never do enough for the Lord, to answer his love,
and the knowledge of his blessed truth he hath given me,
and the divine sweetness and abounding thereof,
that I have many times felt to spring afresh in my soul, in waiting upon him.

Wherefore such a one is made often to say, there is nothing that I have,
that is so near and dear to me,
but I can freely part with it for the Lord and his worthy name`'s sake,
for all I have and do enjoy is the Lord`'s;
so can his redeemed say with a good understanding, not only their souls and bodies,
but all they have and do enjoy, are his.

Blessed and happy are all they, whose godly resolution this is,
who are thus redeemed by his power;
hold fast and continue your godly resolution unto the end, in true faith;
and look not out, nor give way to the reasoning part;
but keep near the Lord and rely upon the sufficiency of his power;
that by waiting and watching therein, you may receive strength.
Then you will be strong and courageous, bold and valiant for the truth upon earth;
for he, for whose name`'s sake you suffer,
has sufficient in store to reward all your losses, crosses, trials and sufferings,
both here, and eternally hereafter; and assuredly will not withhold it from you,
as you stand faithful unto him in your testimony unto the end; unto which,
the Lord by his own power, preserve you all, Amen.

Dear Friends, I being well stricken in years,
cannot promise long time to myself in this world, and I was willing,
in answer to the motion of God`'s blessed spirit, to send this epistle abroad amongst you,
as a token of my entire love and tender care over the flock of Christ;
wishing that grace, mercy and peace, in and through Him,
may be multiplied and increased amongst you, and that brotherly love and unity,
in the one spirit of life may continue, and abound more and more,
and that in all your meetings and families,
you may be blessed with heavenly blessings in Christ Jesus.

[.signed-section-closing]
From your friend and brother, in the covenant of light and life.

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
Given forth at Meare, in Somersetshire, the 23rd day of the Fifth month, 1698.

[.blurb]
=== A True Testimony Concerning My Faith in Christ.

I believe in that same Lord Jesus Christ, the Son of God, for remission of sins,
and the salvation of my soul, who "`was conceived of the Holy Ghost,
born of the virgin Mary, made a good confession before Pontius Pilate,
and was crucified without the gates of Jerusalem; was dead and buried,
and rose again the third-day, and ascended into glory,
far above all heavens,`" that he might fill all things,
according to the testimony of the holy Scriptures;
for which I have a godly and reverent esteem.

I also believe in Him, as to his appearing the second time, without sin, unto salvation,
to all that look for Him, by his living and eternal spirit, the Spirit of Truth,
which the world cannot receive, as when he prayed unto the Father,
that he would send the Comforter, that leads into all truth,
all that believe in him thereby.

When it pleased the Lord to visit me with the day-spring of his love from on high,
in the days of my youth, by this Spirit of Life and Truth, sin and Satan were manifested;
and if at any time I was prevailed upon, by entering into any of his temptations,
I was reproved and judged thereby.
But when faith was begotten in my heart,
to believe in the Spirit of Truth that reproved me, I received power from Him,
in whom I did and do believe, to overcome one sin after another,
in order to a perfect freedom from it, which must be in this life,
or else there is no entering into the kingdom of heaven.
For all who live and die in sin are unclean and therefore cannot enter the kingdom.

This is the blessed effect of the faith of every true believer in the Lord Jesus Christ;
as to his birth, suffering, resurrection, ascension, and second coming without sin,
unto salvation; in whom all must believe for life and salvation to their souls,
whoever come to know the full assurance thereof, in the kingdom of happiness,
and endless glory.

I believe in Him, and own Him in all his offices,
and under every name and denomination which is given to Him in the holy Scriptures.
I own Him as King, even King of saints, and Lord of life and glory;
High Priest of the profession of all that were and are of the true faith;
God`'s covenant of light and life; Emmanuel, God with us,
who is come to save his people from their sins, not in their sins,
for there is no being saved therein; which is in the fallen and lost condition.

I own and believe in Him, as he is the "`true light,
that enlighteneth every man that Cometh into the world.`"

I own and believe Him to be "`the way, the truth, and the life;
and that no man comes to the Father but by Him.`"

I believe in Him, as he is the Minister of the sanctuary,
and true tabernacle which God hath pitched, and not man; who by his power and spirit,
hath fitted and made many able and faithful ministers,
in this the day of his everlasting Gospel,
among whom he hath been pleased to account me worthy to be one,
though one of the least of many.
He is the Minister of ministers, and none are or can be true ministers,
but who are made so and ordained by Him.--He fits, opens and prepares by his power,
and quickening spirit.--So the ministers of Christ preach Him, the way, the truth,
and the life; the true light, the door, the true Shepherd,
who laid down his life for his sheep, and saves by his grace all true believers,
who obey the teachings thereof.

He is also believed in and known by his second coming, to be the ingrafted Word,
that is able to save the soul.
He took flesh and suffered in it, the one Offering once for all, to put an end to sin,
and finish transgression, and bring in everlasting righteousness.--The fulfiller,
the finisher and end of the law, with all the types, figures and shadows of it;
the end of tithes, swearing, temple-worship, outward circumcision,
offerings and oblations.
The end, finisher and fulfiller of water-baptism,
and outward communion by eating of bread, and drinking of wine; He the great Baptizer,
having baptized many by his spirit into one body, of which he is the Head,
which is the one saving baptism,
with the Holy Ghost and fire;--and John with his water baptism is decreased, and ended.

And He is the one bread of life, come down from God out of heaven,
which is eaten of by faith, whose flesh is meat indeed, and his blood is drink indeed.
He the living substance is come and fed upon; that was and is the communion of saints.

This being the substance of the testimony, in brevity, of my faith in Christ,
I am willing to leave it behind me, when I have finished the work of my day,
and am gathered to my everlasting rest, which I have long travailed for,
through many deep exercises.
And this not only for myself, but I was willing to leave this upon record,
on the behalf of my Friends and brethren also, the people of God in scorn called Quakers,
who are of the same faith in Christ with me.

That all may know,
who have a desire to have a right understanding of our faith and principles;
that we are no such people as to our faith in Christ, as some ignorantly,
and others hatefully have rendered us;
as though we only or wholly depended upon the light within, for salvation to our souls;
and did not own or believe in Christ, as to his coming, death, resurrection, ascension,
etc.; and the benefit we, and all true believers have thereby.

But, blessed, praised and magnified be the worthy name of the Lord our God forever,
who hath opened our understandings by his power, whereby we know Him,
in whom we do believe; which is not to believe in the light within,
distinct from Christ;--or as if people could believe in the light, and not in Christ.
But we believe in both, as one; knowing and being clear in our understanding,
that no separation can be made between Christ, and the light that comes from him,
which shines in the hearts of all true believers;
and shines in the darkness of unbelievers,
and therefore the darkness cannot comprehend it.
So we as truly believe in that same Christ, who laid down his body, and took it up again,
as in his light within, and we have benefit to salvation,
by the one as well as the other, and of both, they being one,
and are willing to lay hold of every help and means, God in and through Jesus Christ,
has ordained for our salvation.

[.signed-section-signature]
John Banks.

[.signed-section-context-close]
Meare, in Somersetshire, the 5th day of the Seventh month, 1704
