== Testimonies Concerning John Banks.

[.blurb]
=== John Whiting`'s Testimony Concerning John Banks.

Since it pleased the Lord, in his infinite love,
to cause his day to dawn and his truth to break forth in this nation of England,
even in an acceptable time, when many were seeking the Lord,
and wandering like sheep without a shepherd upon
the barren mountains of lifeless profession,
seeking rest but finding none; many messengers have been raised up,
and sent forth to publish the glad tidings of the Gospel,
and to turn people from darkness to light, that they might find rest to their souls;
many of whom, especially of the first rank, are fallen asleep.
Among these our dear friend John Banks, the author of the following papers,
was early raised and sent forth with the word of life,
and was a faithful labourer in his day, who gave up himself for the spreading of truth,
spending and being spent in the service of the Gospel,
for gathering people to the knowledge of the truth,
in which he was made an effectual instrument to many, in this and other nations,
particularly Scotland and Ireland.

Since the Lord was pleased to give me the knowledge of his truth,
to which my education by religious parents was a good help,
I always loved its messengers for its sake,
as I did the author of the ensuing papers for his sound and savoury testimony,
which ministered grace to the hearers.
He divided the word aright, according to their several states and conditions,
of which he had a good discerning, and could speak a word in season accordingly;
like a good scribe instructed unto the kingdom of heaven,
who bringeth forth of his treasure things new and old.
He was also one that ruled well, not only his own family, but in the church of God.

I knew him above thirty years, from his coming into the county of Somerset,
in the year 1677; and could then, though but a young man,
set my seal to the truth of his ministry, and witnessed the efficacy of it.
It was with demonstration of the spirit and power; he being endued from on high,
to preach the everlasting Gospel of life and salvation.
I have often been comforted in meetings with him since,
especially about the time of his coming to settle in the county of Somerset.

One of the last duties we owe to the memory of such who
have laboured among us in word and doctrine,
and for their works`' sake have been worthy of double honour, is to publish their memoirs,
as occasion offers, after their decease; in which, I confess,
I have often been comforted,
as commemorating the worthy and noble acts of the Lord done by them, and his goodness,
mercies, and providences in preserving them,
and carrying them over all opposition of men of perverse minds,
and the persecutions and sufferings which have attended them for their testimony,
and which have not been few in these latter days.
This has always been the lot of truth and its witnesses,
and was the lot of the author of this book.

The following journal and collection of his
writings were sent to me by him in his life-time,
with a desire that I, and J. Field,
should take the care of publishing them after his decease, which we have carefully done.
I have been comforted in reading them, by the sound, solid,
serious matter contained in them,
which I doubt not will have a witness in the
consciences of all who read them in the fear of God.
In them he being dead yet speaketh,
whose memorial still lives and will live among
the faithful in a lively remembrance of him.

I truly loved him for his sincerity and uprightness,
being a faithful man to the testimony of Truth,
and concerned for good order in the church of Christ, against disorderly walkers,
and to keep things clean in Monthly and Quarterly Meetings,
from all that would defile or break the love and unity.
When he grew weak in body, that he could not travel as in time past,
though he got to several meetings beyond expectation but a little while before his death,
yet his care for the church was not lessened, that all things might be kept well;
and at last having served his generation according to the will of God,
he fell asleep and died in the faith and full assurance
of a blessed immortality and eternal life.
He laid down his head in peace with the Lord, in a good old age, and full of days,
aged about seventy-four, and is entered into the fruition and reward of his labours,
and his works follow him.

[.signed-section-signature]
John Whiting.

[.signed-section-context-close]
London, the 12th of the Twelfth month, 1711.

[.blurb]
=== A Testimony from Friends of Pardshaw Monthly Meeting in Cumberland, concerning John Banks.

He was one upon whom the Lord poured forth of his holy Spirit,
and gave a large gift thereof to serve him.
The Lord`'s love is universal to all; he would have none to perish,
but that all should come to the knowledge of the truth, and be saved;
and for that end he gives gifts to men, to make them instrumental in his hand,
to bring the sons of men to have faith in his only Son the Lord Jesus Christ,
"`who is the true light which lighteth every man that cometh into the world.`"
Our dear friend was early called into the work of the ministry,
and was faithful to improve his gift; and the Lord made him useful in his hand,
and many are the seals of his ministry who yet remain in this county,
who are witnesses of the power that was effectually with him, to the convincing of many.
He was a faithful minister of the everlasting Gospel, and given up to preach it freely,
and labour faithfully in the work thereof; and went through great hardships,
and travelled much both by sea and land, in Ireland, Scotland, and in this nation,
and most of all in this county,
where he laboured night and day for the gathering of people to God,
and for the settling of those who were gathered.
He was one of good discernment, and was often opened by the Spirit of Truth,
to speak to peoples`' states, and had an answer from God`'s witness in their hearts,
so that many were convinced by him.
He was instrumental to gather several meetings in this county;
being an incessant labourer in the Lord`'s work, both in body and mind; rising up early,
and lying down late, and freely given up to spend and be spent;
and we sincerely desire that we who had the benefit of his labour,
may be kept in true fear and walk worthy of all the Lord`'s mercies, to his glory,
and our salvation.

His ministry was powerful and piercing, ministering judgment upon the transgressor,
yet filled with consolation to the sincere-hearted,
so that he was both beloved and feared by many.
His memory lives amongst the righteous; and we doubt not but he is entered into rest.
It was not only given him to believe, but to suffer for the testimony of God;
in which he was preserved firm and true,
to the stripping of his goods by the Conventicle Act,
public sale being made of what he had; yet the Lord bore him up over all,
that he was as one of the stakes of Zion, that could not be moved.
He was afterwards in prison at Carlisle for his testimony; yet retained his integrity,
and stood faithful, and the Lord was with him,
and gave him courage still to stand firm in his
testimony against tithes and the hireling priests,
not only in word, but in deed and in truth.
In the time of the Conventicle Act, he kept close to meetings,
so that the informers concluded, whoever were not, he would be there;
insomuch that they ventured to inform against him, whether they saw him, or not;
and thereby laid a snare for themselves; and swore he was preaching on Pardshaw Crag,
when he was gone in the service of the Gospel into Ireland,
and was taken prisoner in Wicklow; which was proved against them,
and they were forced to fly the country, and both came to miserable ends.

He had great service at that time,
for many were convinced of the truth at the meeting in which he was taken prisoner.
We might say more on this subject;
yet the bent of our minds is not to attribute anything to him, or to any man,
but to the Lord`'s power, which raised him up and made him what he was,
to his honour and the peace and benefit of the church;
desiring that we who yet remain may keep in true fear and humility,
following the Lord Jesus in the way of self-denial,
that we may so run as to obtain the crown of immortal glory.
"`Be thou faithful unto death, and I will give thee a crown of life.`"

[.signed-section-signature]
James Dickinson, Peter Fearon, John Burnyeat, William Harris, John Wilson,
Jonathan Bowman, John Ribton, Peter Wilson, Thomas Tiffin, Christopher Fearon,
Jonathan Bell, John Nicholson, Matthew Lowman, George Wilson.

[.signed-section-context-close]
From Friends of Pardshaw Monthly Meeting, the 23rd of the Eighth month, 1711.

[.blurb]
=== John Bousted`'s Testimony Concerning His Deceased Friend, John Banks.

He was a faithful minister of Christ in this his glorious Gospel day,
after that long and dark night of apostacy, which had spread itself over the nations,
in which many were made drunk with the cup of fornication.
After it had pleased the eternal, wise God to open his understanding,
and to let him see his own state and condition, and reveal his Son in him,
he was made willing to give up freely to the
heavenly and inward appearance of Christ Jesus,
the hope of glory.
And as he was obedient thereunto, he was entrusted with a large gift of the ministry,
in which he grew, and was made powerful in it,
to the turning of many unto the right way of the Lord;
who were convinced of the evil of their ways, and turned unto Jesus Christ,
their free teacher; and were made to bless the Lord on his behalf,
that it should please the Lord to send him amongst them who had sat in darkness,
and under the region of the shadow of death.
He was skillful in dividing of the word aright, having milk for babes,
and stronger meat for those of riper age.
I knew him well, and truly loved and honoured him, for he was worthy of double honour,
as one that ruled well in the church of Christ.
As he was bold in asserting the truth, so he was valiant in suffering for it,
both by imprisonment, and in spoiling of his goods.
When at liberty, he travelled much in divers parts of this nation,
also in Ireland and Scotland; and in many places where it was my lot to follow him,
I found of the fruits of his labours; both by the convincement of some,
and the settlement of others; for great was his labour in the love of Christ our Lord.
And although he was sharp in his rebukes to the unfaithful and to backsliders,
yet in admonition he was gentle and courteous;
God having given him the spirit of discerning, and of a sound judgment.
I speak these things to the honour of the hand that raised him up;
with fervent and true desires to the Lord,
that he may raise up and send forth many more faithful labourers into his harvest;
for the harvest is great, and the true labourers are but few.

[.signed-section-signature]
John Bousted.

[.signed-section-context-close]
Aglionbye, the 25th of the Ninth month, 1711.

[.blurb]
=== Christopher Story`'s Testimony Concerning John Banks.

As the labours, travels, and exercises of our dear friend John Banks were great,
both in doing and in suffering for the name of the Lord,
I shall here give a relation of some part of them, where I was present with him.

The first time I saw him was at a meeting at John Iveston`'s, of Jerishtown in Cumberland,
in the latter end of the year 1672, or about the beginning of the year 1673,
where there were many Friends and other people.
It was a good meeting,
to the confirming of those who had lately received the truth in the love of it;
and convincing others of the right way of the Lord.

The next meeting he had in our parts was at Edward Atkinson`'s of Masthorne.
A great meeting it was, and many received the truth in the love of it,
and lived and died in it.
Others were so reached,
that though they never took the profession of the truth upon them,
yet they often manifested their love to truth and Friends, to their dying day.

So effectually was the love of God manifested in that meeting,
that many tears were shed by some for joy that the Gospel of glad tiding was so preached,
and by others, in a sense of godly sorrow for their mis-spent time.
He had several meetings afterward, nearer to the borders of Scotland;
and one at Parkrigg, in which several were convinced by him, and others being added,
it is now become a settled meeting.
He was serviceable amongst us in word and doctrine,
and very exemplary in life and conversation, so that I greatly loved him.
He had also a share in government, and the care of the churches was upon him,
that they who professed the truth might walk answerably in their lives and conversations.

In the year 1679, our dear friend going to the Yearly Meeting at London, for the county,
and it being my lot to be his companion at that time,
we met at Strickland in Westmoreland; and visited some meetings in Yorkshire,
Nottinghamshire, Leicestershire, Northamptonshire, and so to London.
He had good service in most places,
and much comfort and satisfaction I had in his company, he,
whom I esteemed above many others, being a loving and a nursing father to me.

After we had stayed the time of the Yearly Meeting,
and he was clear of the meetings of the city, we went to a meeting at Windsor,
and so to High Wycombe, Reading, Newbury, Marlborough, Calne, Chippenham,
and most of the meetings in those parts.
It was a time of deep exercise to many faithful
brethren who kept their habitations in the truth;
for in most meetings of this part of the nation, there was a rending,
dividing spirit crept into the church, and many were made to say, "`Alas,
we know not which way to turn, or what will be the end,`" etc.
I am a witness, with many more, some of whom are yet alive,
of the deep exercise of spirit he went under, from meeting to meeting,
for the Seed`'s sake, that the innocent might be preserved from hurt,
and the spirit of separation which would divide in Jacob and scatter in Israel,
might be fully manifested.
Though his exercises were such night and day that his
meat and sleep were almost taken from him,
yet the Lord so strengthened him in his inward man, that he was borne up in his spirit,
to confirm and build up the righteous in that most holy faith which works by love,
and to proclaim woe and judgment upon the spirit that had led into separation.

And though in several places, they who were most in the separation,
followed him from meeting to meeting, and bent their bows against him,
waiting for an advantage, yet the Lord was pleased, for the honour of his own name,
to preserve him by his power, that he came away to the churches`' comfort and edification,
and to his own peace.

After this, we came to Bristol,
and found faithful Friends under great exercise of spirit,
by reason of a contentious spirit that some there were gone into.
We visited meetings thereabouts, and when our friend was clear, and his service over,
we came pretty direct for Cumberland.

As the labours and travels of this our dear friend were great for the truth`'s sake,
which he was called to bear witness to, so he was also valiant in suffering for it,
as appeared in his imprisonment in Carlisle.
It was my lot, with others of our meeting, to be committed to prison at that time,
for our peaceable meeting together to wait upon the Lord,
and to worship him in spirit and in truth.
We found our dear friends, John Banks and Thomas Hall,
separated from the rest of Friends, who were prisoners, and put into a dark place,
called the citadel, among the felons, something like a dungeon,
where they could not see to work in a dark day, without candle-light;
and for no other cause,
but for preaching and praying in the time of Friends`' meeting to wait upon the Lord,
in the place where they were confined.
His persecutors hoped by their being absent, the meetings of Friends would be silent,
and give less occasion of disturbance to priests and others,
who took occasion against his preaching.
The first meeting we had amongst the Friends in prison, Andrew Graham and I,
appearing in public, the jailer was much disturbed,
and took us away from the rest of Friends; and being afraid of the priests and others,
was at a stand what to do; for there was no room for any more beds among the felons.
The bed whereon our dear friend lay, was next to the sink,
where the filth was discharged, which made it the more noisome;
but the Lord`'s power carried them over all,
and in a few days I obtained liberty of the jailer, to go with the turnkey,
and found the Friends, through the Lord`'s goodness, easy and well.
The turnkey returning, I stayed to bear them company till evening.
When the turnkey came again,
he told John Banks he and his companion might go to the rest of Friends, if they pleased,
for it would avail nothing to keep them there, as there were now other preachers.
John Banks replied, the jailer brought them thither without any just cause,
and he should fetch them back again,
and cause what they had to be carried along with them; which he did before he slept.
Being now together in one place, we kept our meetings, first-day, and week days;
and the place of our confinement being near the upper end of Castle street,
and not far from the great cathedral, so called,
it often happened that at the time when people came from their worship,
on the first-days, John was preaching,
and his voice would reach to the door of the great house;
and people frequently would either go softly, or stand a little;
for at that time no meeting of Friends was kept in the city.
And at this the priests were much disturbed, and threatened the jailer so much,
that he left this place at the year`'s end, and hired another house.

Our friend John Banks, being a good example in all things,
laboured diligently with his hands, being a glover and fell-monger by trade;
and with much sitting during that cold winter,
in which the great frost continued so long, he thereby grew infirm.
We were sixteen in one room, and had the privilege of but one little fire;
and mostly four or five ancient people had the benefit of it;
but at last we all obtained our liberty; mostly by King James`'s proclamation,
and came forth free and clear men, for which the Lord shall have the praise.

I could say more; but knowing there are many faithful brethren and sisters,
who had a perfect knowledge of him and of his integrity,
from the time of his convincement to the day of his death,
and of his many labours and exercises both at home and abroad,
I am the more easy to conclude, being an eye and ear witness of what I have here written.

[.signed-section-signature]
Christopher Story.

[.blurb]
=== A Testimony from the Quarterly Meeting in the County of Somerset, concerning John Banks, of Street, in the same County, deceased; who departed this life the 6th day of the Eighth month, 1710.

He was very zealous to the last to spread the Gospel;
and in all his exercises and afflictions he had the
honour of God and good of his people in his eye.
He devoutly laboured in his gift, and being an able minister of Christ,
was instrumental both to gather and confirm many souls in the truth.
We have many witnesses, who, with us, have partaken of the comfort of his labour.
He was a good example, and his conversation was pleasant and profitable;
sharp against the obstinate opposer, but meek and gentle towards them, who,
in a sense of their shortness, were ready and willing to acknowledge the same.

Such was his concern for the Gospel, that he did not spare himself to promote the truth:
he was zealous against a luke-warm spirit, warning Friends, both by doctrine and example,
to beware thereof;
often reminding the young people of that fervent love
which was amongst the brethren in the beginning.
He was not insensible that a libertine spirit too much prevailed in many places,
neither was he wanting to bear a testimony against it.

Friendly reader, whoever thou art, or whatever thy state in the church may be,
although the design of this is to demonstrate our love to the deceased,
yet we also intend hereby thy edification.
And in order thereunto, we would briefly say; first, if thou art a minister,
attend on thy ministry, and wait to know God`'s time,
that when thou speakest it may be in his time; and keep to thy opening,
that what thou speakest may be from the Spirit, and with understanding.
Thus wilt thou learn, both when to speak, what to speak, and when to be silent;
a principal thing for Gospel ministers to have the true knowledge of.
And also thou wilt be preserved from a lifeless unedifying ministry, which is a hurt,
but never helps true believers.
It is a living ministry which begets a living people; and by a living ministry, at first,
we were reached and turned to the truth.
It is a living ministry that will still be acceptable to the church,
and serviceable to its members.
It is an excellent virtue in ministers, a seal and confirmation of their ministry,
to be found in the practice of that which they preach to others;
such can in boldness say with the apostle, "`Be ye followers of us,
as we follow Christ.`"

Secondly, if thou art not gifted in the ministry,
but a living witness of the virtue of truth,
and partaker with us of the like precious faith,
we entreat thee mind thy place in the church,
that thou mayest be found in obedience to the Gospel:
thus mayest thou come under a spiritual qualification for the oversight of others;
which must be by taking heed to thyself, according to Acts 20:28:
"`Take heed therefore unto yourselves, and`" then "`to the flock,`" etc.,
but first take heed to thyself.
Why so much to myself?
I know the truth, and am sensible of my duty, some may say, But give us leave to add,
that many are sensible of the good they ought to do, but neglect it; therefore,
look well to thyself, that thy obedience keeps pace with thy knowledge,
that so thou mayest not only be a hearer, but a doer also.
This will give thee authority,
that with clearness and boldness thou mayest advise them that are unfaithful,
and neglect what they ought to do; for he that hears and doth not,
his building is not aright, and cannot stand in the time of trial.
Whatsoever thou mayest be, it matters not; for he that adviseth others,
being faulty himself, must expect to meet but with a cold reception.
Therefore, look well to thyself, neglect not the gift that is in thee,
neither measure thy duty by another`'s neglect.
It is too much a practice in this age,
to be influenced more by the worst than by the best of examples.
But, follow thou the footsteps of the flock of Christ`'s companions, who are gone before;
so wilt thou come up in the place of some of the
many worthy ancients who are gone to rest;
amongst the number of whom, this, our friend, may be accounted worthy to be reckoned;
as one who both bore the burden and heat of the day.
Let it be thy concern to follow his example in faithfulness; not for imitation`'s sake,
but for the Lord`'s honour;
so wilt thou be fitted to enter into that blessed
inheritance which God has in store for the faithful.
That this may be thy portion, so wish, and so pray thy fervent and Christian friends.

[.signed-section-closing]
Signed by order, and on the behalf of the Meeting aforesaid, from Glaston,
the 22nd and 23rd of the First month, 1710-11, by

[.signed-section-signature]
Elias Osborne, William Jenkins,
John Hipsley, Abraham Thomas, Joseph Pinker, William Horwood, John Thomas, Samuel Bownas,
William Alloway.

[.blurb]
=== A Testimony Concerning Our Dear and Worthy Friend John Banks.

Whom the Lord was pleased to place in this part of the country,
as he himself hath signified;
and he was very serviceable amongst us in the work of the ministry,
and also in settling a godly discipline in many places; encouraging the young men,
as well as the old and middle-aged, to come to our meetings for that service,
that they might be serviceable in their places.
He was very tender and loving to the well inclined, and a reprover of evil doers,
gainsayers, and backsliders, placing judgment upon the head of the transgressor.
He was very desirous that things might be kept savoury, and in good order amongst us,
often giving good advice and counsel to Friends out of meetings, as well as in meetings,
for it was his great delight to see them grow in the truth.
He gave way to strangers when we were visited,
although he was an able minister of the word of life, which dwelt plentifully in him,
and his bow abode in strength, and he would often hit the mark.
He was a great encourager of Friends to bear a faithful testimony against tithes,
and steeple-house rates, etc., and where he saw anything to the contrary,
he would show his dislike.
He was a faithful labourer in the work of the Lord, visiting Friends`' meetings abroad,
as long as he had strength of body; but was attended with weakness several years,
in which time he wrote several papers to Friends.
Some time before he died, he removed his habitation to Street, near the meeting-house;
and our meetings both for worship and business, were many times held at his house,
which was a great comfort to him, for he was very glad of the company of honest Friends;
and sometimes when they asked him how he did, he would say, "`Weak in body,
but strong in the Lord--all is well.`"
He was borne up in his spirit beyond what could be expected,
to bear a living testimony in our meetings,
being attended with that Divine power which made his soul sing praises to the Lord,
to the comforting of the faithful in Christ.

He was a great help to us in our Monthly Meetings, in managing the affairs of the church;
being favoured with the continuance of his understanding and memory.
We greatly miss him, and although it is our loss,
yet we believe it is his everlasting gain,
and that he is gone to rest with the faithful in Christ.
And now, since it hath pleased the only wise God, in his infinite wisdom,
to take unto himself this our dear friend, his faithful servant,
and minister of the everlasting Gospel, it is the desire and supplication of our hearts,
unto the great Lord of the harvest,
that it may please him to raise many more such labourers;
"`For the harvest indeed is great, but the true and faithful labourers are but few.`"

[.signed-section-closing]
Signed on behalf of our meeting, at Glastonbury and Street, the 13th of the Third month,
1711, by

[.signed-section-signature]
James Clothier, Sen.
Joseph Moore, Arthur Gundry, John Blackmore, James Clothier, Jan.
Tho. Freeman, Tho.
Marnard, Wm. Blackmoke.
Roger Jewell.

[.signed-section-context-close]
This was viewed and approved of by the Monthly Meeting.

[.blurb]
=== Hannah Banks`'footnote:[Second wife of John Banks] Account and Testimony Concerning Her Dear and Tender Husband, John Banks, Deceased.

I was married to him the 28th of the eighth month, 1696, being a widow,
and was convinced of God`'s truth in the time of my widowhood;
we were married at Glastonbury, and went to live at Mear, until the year 1708,
and then came to Street, where we continued until he died.
He was afflicted with much weakness in his latter time;
but a little before his death was raised to go to some meetings.

On the 5th of the sixth month he went from home to Somerton,
and the next day to their Monthly Meeting of worship, which was very large,
and he had a good meeting, to the satisfaction of Friends.
Afterward he had an evening meeting in the town, and went next day to Long Sutton,
to visit Friends; and to some other places; and was at the Monthly Meeting at Puddimoor,
and had a large testimony to Friends; and also at Yeovil, and was well accepted;
after which he returned home.
Most Friends thought he would not have been able to undertake such a journey,
being between twenty and thirty miles, by reason of his weakness;
but he could not be satisfied without it.
On the 2nd of the seventh month, as he was walking in the yard,
he was taken with a pain in his back, which, by degrees, went downward into his feet,
and proved to be the gout.
It was very painful for several days before his death; yet he would often say,
until the last, that notwithstanding all his pain,
his soul did praise and magnify the Lord, for his goodness towards him,
though he thought his pain sometimes sharper than death; and said,
how well it would be if the Lord would be pleased to remove him hence.
Many Friends and others coming to visit him, he had a large testimony to them,
by way of exhortation; and a few hours before his death,
said how well it was to have nothing to do but to die.
At another time he said,
he was assured it would be well with him and that he should end in the truth,
as he began.
He was very sensible to the last; and, after all his pains, had an easy passage,
on the 6th of the eighth month, 1710, and is gone to rest;
aged seventy-three years and two months.

He was a man that feared God, wrought righteousness, loved truth above all,
and his friends with all his heart, and served them faithfully to the end.
I am satisfied he hath laid down his head in peace, and rested from all his labours.
He was a true help-meet to me, and we lived almost fourteen years together;
five of which he was under great weakness, which he bore patiently to the end.
I cannot but lament my loss of so near a friend,
for he was a great strength to me in my weakness, who am poor and feeble of myself,
and do desire the prayers of the faithful, for my preservation,
that I may hold out to the end; who am his mournful widow,

[.signed-section-signature]
Hannah Banks.

[.signed-section-context-close]
Street, in Somersetshire, the place of my abode, this 4th of the Third month, 1711.
